<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @deprecated
 */

/**
 * @var $block \Branch8\Customer\Block\BrowsingHistory\Index
 */
?>
<?php
if ($exist = ($block->getRecentlyViewedProducts() && $block->getRecentlyViewedProducts()->getSize())) {
    $type = 'widget-viewed';
    $mode = 'grid';

    $type = $type . '-' . $mode;

    $image = 'recently_viewed_products_grid_content_widget';
    $title = __('Browsing History');
    $items = $block->getRecentlyViewedProducts();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $rating = 'short';
    $description = ($mode == 'list') ? true : false;
}
?>
<?php if ($exist) : ?>
    <?php $currentPage = $block->getRequest()->getParam('p'); ?>
    <?php $i = 0; foreach ($items as $_item) : ?>
        <?php $i++; ?>
        <li class="product-item <?= ($i === 1) ? 'page-first-item-'.$currentPage : '' ?>" data-page="<?= $currentPage ?>">
            <div class="product-item-remove" product-id="<?php echo $_item->getProductId()?>">
            </div>
            <div class="product-item-info">
                <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-photo">
                    <?= $block->getImage($_item, $image)->toHtml() ?>
                </a>
                <div class="product-item-details">
                    <strong class="product-item-name" data-item="<?php echo $_item->getId();?>">
                        <a title="<?= $block->escapeHtmlAttr($_item->getName()) ?>"
                           href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-link">
                            <?= $block->escapeHtml($_item->getName()) ?>
                        </a>
                    </strong>
                    <?= /* @noEscape */ $block->getProductPriceHtml(
                        $_item,
                        \Magento\Catalog\Pricing\Price\FinalPrice::PRICE_CODE,
                        \Magento\Framework\Pricing\Render::ZONE_ITEM_LIST,
                        [
                            'price_id_suffix' => '-' . $type
                        ]
                    ) ?>
                    <?php if ($rating) : ?>
                        <?= $block->getReviewsSummaryHtml($_item, $rating) ?>
                    <?php endif; ?>
                    <?php if ($showWishlist || $showCompare || $showCart) : ?>
                        <div class="product-item-actions">
                            <?php if ($showCart) : ?>
                                <div class="actions-primary">
                                    <?php if ($_item->isSaleable()) : ?>
                                        <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)) : ?>
                                            <button class="action tocart primary"
                                                    data-mage-init='{"redirectUrl": {"url": "<?= $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"}}'
                                                    type="button" title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                            </button>
                                        <?php else : ?>
                                            <?php
                                                $postDataHelper = $this->helper(\Magento\Framework\Data\Helper\PostHelper::class);
                                                $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                            ?>
                                            <button class="action tocart primary"
                                                    data-post='<?= /* @noEscape */ $postData ?>'
                                                    type="button" title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                            </button>
                                        <?php endif; ?>
                                    <?php else : ?>
                                        <?php if ($_item->isAvailable()) : ?>
                                            <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                        <?php else : ?>
                                            <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>
                            <?php if ($showWishlist || $showCompare) : ?>
                                <div class="actions-secondary" data-role="add-to-links">
                                    <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist) : ?>
                                        <a href="#"
                                           class="action towishlist" data-action="add-to-wishlist"
                                           data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>'
                                           title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                            <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                        </a>
                                    <?php endif; ?>
                                    <?php if ($block->getAddToCompareUrl() && $showCompare) : ?>
                                        <?php $compareHelper = $this->helper(\Magento\Catalog\Helper\Product\Compare::class);?>
                                        <a href="#" class="action tocompare"
                                           data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_item) ?>'
                                           title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                            <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                        </a>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </li>
    <?php endforeach ?>
<?php endif;?>
