<?php
/**
 *
 * @category    Branch8
 * @package     Branch8_Blog
 */

use Branch8\Blog\Block\Frontend;
use Branch8\Blog\Model\Post;
use Magento\Framework\Escaper;

/** @var Frontend $block */
/** @var Escaper $escaper */
?>
<?php if ($block->isAjax()): ?>
    <?php $postCollection = $block->getPostCollection(); ?>
    <?php if ($postCollection && $postCollection->getSize()) : ?>
        <div class="post-list-body <?= $block->isGridView() ? /* @noEscape */ 'grid' : '' ?>">
            <?php /** @var Post $post */
            foreach ($postCollection as $post) : ?>
                <div class="item post-list-item <?= $block->isGridView()
                    ? ' post-item-grid  ' : ' post-item-list  '; ?>">
                    <div class="post-item-wraper">
                        <div class="post-image-wrapper">
                            <?php $imageLayout =  $post->getImage() && $post->getImageTwo() && $post->getImageThree() ? 'layout-grid-3' : 'layout-grid' ?>
                            <a href="<?= $escaper->escapeUrl($post->getUrl()) ?>" class="post-view-image post-image-link <?= $imageLayout; ?>">
                                <?php if ($post->getImage()) : ?>
                                    <span class="post-image" style="background-image: url(<?= $escaper->escapeUrl($block->resizeImage($post->getImage(), '400x')) ?>);">
                                    </span>
                                <?php endif; ?>
                                <?php if ($post->getImageTwo()) : ?>
                                    <span class="post-image" style="background-image: url(<?= $escaper->escapeUrl($block->resizeImage($post->getImageTwo(), '400x')) ?>);">
                                    </span>
                                <?php endif; ?>
                                <?php if ($post->getImageThree()) : ?>
                                    <span class="post-image" style="background-image: url(<?= $escaper->escapeUrl($block->resizeImage($post->getImageThree(), '400x')) ?>);">
                                    </span>
                                <?php endif; ?>
                            </a>
                            <style>
                                .post-image-link .post-image{
                                    background-size: <?= $post->getBackgroundSize(); ?>;
                                    background-position: <?= $post->getBackgroundPosition(); ?>
                                }
                            </style>
                        </div>
                        <div class="post-info-wraper">
                            <h2 class="mp-post-title">
                                <a class="post-link-title" title="<?= $escaper->escapeHtml($post->getName()); ?>"
                                   href="<?= $escaper->escapeUrl($post->getUrl()) ?>">
                                    <?= $escaper->escapeHtml($post->getName()) ?>
                                </a>
                            </h2>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    <?php else : ?>
        <?= $escaper->escapeHtml(__('There are no posts at this moment')) ?>
    <?php endif; ?>
<?php else: ?>
<div class="blog-rss">
    <a href="<?= $escaper->escapeUrl($block->getRssUrl('post/rss')) ?>" class="bb-rss-icon">
        <img src="<?= $escaper->escapeUrl($block->getViewFileUrl('Branch8_Blog::media/images/rss.png')) ?>"
             width="16px">
    </a>
</div>
<div class="post-list-content" id="blog-list-container">
    <?php $postCollection = $block->getPostCollection(); ?>
    <?php if ($postCollection && $postCollection->getSize()) : ?>
        <div class="blog-toolbar-top">
            <?= $block->getPagerHtml() ?>
        </div>
        <div class="post-list-body <?= $block->isGridView() ? /* @noEscape */ 'grid' : '' ?>">
            <?php /** @var Post $post */
            foreach ($postCollection as $post) : ?>
                <div class="item post-list-item <?= $block->isGridView()
                    ? ' post-item-grid  ' : ' post-item-list  '; ?>">
                    <div class="post-item-wraper">
                        <div class="post-image-wrapper">
                            <?php $imageLayout =  $post->getImage() && $post->getImageTwo() && $post->getImageThree() ? 'layout-grid-3' : 'layout-grid' ?>
                            <a href="<?= $escaper->escapeUrl($post->getUrl()) ?>" class="post-view-image post-image-link <?= $imageLayout; ?>">
                                <?php if ($post->getImage()) : ?>
                                    <span class="post-image" style="background-image: url(<?= $escaper->escapeUrl($block->resizeImage($post->getImage(), '400x')) ?>);">
                                    </span>
                                <?php endif; ?>
                                <?php if ($post->getImageTwo()) : ?>
                                    <span class="post-image" style="background-image: url(<?= $escaper->escapeUrl($block->resizeImage($post->getImageTwo(), '400x')) ?>);">
                                    </span>
                                <?php endif; ?>
                                <?php if ($post->getImageThree()) : ?>
                                    <span class="post-image" style="background-image: url(<?= $escaper->escapeUrl($block->resizeImage($post->getImageThree(), '400x')) ?>);">
                                    </span>
                                <?php endif; ?>
                            </a>
                            <style>
                                .post-image-link .post-image{
                                    background-size: <?= $post->getBackgroundSize(); ?>;
                                    background-position: <?= $post->getBackgroundPosition(); ?>
                                }
                            </style>
                        </div>
                        <div class="post-info-wraper">
                            <h2 class="mp-post-title">
                                <a class="post-link-title" title="<?= $escaper->escapeHtml($post->getName()); ?>"
                                   href="<?= $escaper->escapeUrl($post->getUrl()) ?>">
                                    <?= $escaper->escapeHtml($post->getName()) ?>
                                </a>
                            </h2>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <div class="load-more-container">
            <button id="load-more" class="action primary action-loadmore" data-current-page="1">
                <span><?= __('顯示更多') ?></span></button>
        </div>
        <?php
        /** @var \Magento\Theme\Block\Html\Pager $pager */
        $pager = $block->getChildBlock('pager');
        ?>
        <?php if ($pager): ?>
        <div id="blog-page-count" style="display: none"><?= $pager->getLastPageNum() ?></div>
        <?php endif; ?>
        <div class="blog-toolbar-bottom">
            <?= $block->getPagerHtml() ?>
        </div>
        <script type="text/x-magento-init">
            {
                "*": {
                    "Branch8_Blog/js/loadmore": {}
                }
            }

        </script>
    <?php else : ?>
        <?= $escaper->escapeHtml(__('There are no posts at this moment')) ?>
    <?php endif; ?>
    <?= $block->getChildHtml('additional'); ?>
</div>
<?php endif; ?>
