<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<?php
    $_product = $block->getSellerProduct();
    $block->getFileUploaderJsonData();
    $viewModel = $block->getViewModel();
    $helper = $viewModel->getHelper();
?>
<?php
//$store_id = $_product->getStoreId();
$store_id = 0;
?>
<fieldset class="fieldset downloadable-form" data-ui-id="downloadable-samples">
    <legend class="legend"><span><?= /* @escapeNotVerified */ $escaper->escapeHtml(__('Samples'))?></span></legend><br>
    <p class="note"><?= /* @escapeNotVerified */ $escaper->escapeHtml(__('Add product preview files here.'))?></p>
    <div
    class="field"<?= /* @noEscape */ !$helper->getSingleStoreModeStatus()
    ? ' data-config-scope="' . __('[STORE VIEW]') . '"' : ''; ?>>
        <label class="field-label" for="downloadable_staging_samples_title">
            <span><?= /* @noEscape */ __('Title')?></span></label>
        <div class="field-control">
            <input type="text" class="control-text" id="downloadable_staging_samples_title"
             name="product[samples_title]" value="<?= /* @noEscape */ $_product->getSamplesTitle() ?>">
        </div>
    </div>
    <div class="field field-wide">
        <div class="field-control">
            <div class="control-table-wrapper">
                <table class="control-table">
                    <thead>
                        <tr>
                            <th class="col-sort"><span><?= /* @noEscape */ __('Sort Order') ?></span></th>
                            <th class="_required col-title"><span>
                                <?= /* @noEscape */ __('Title') ?></span></th>
                            <th class="col-file"><span>
                                <?= /* @noEscape */ __('Attach File or Enter Link') ?></span></th>
                            <th class="col-actions">&nbsp;</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <td colspan="4" class="col-actions-add">
                                <button data-ui-id="widget-button-8"
                                data-action="add-sample" class="action-default scalable action-add"
                                type="button" title="Add New Link" id="add_sample_staging_item">
                                    <span><?= $escaper->escapeHtml(__('Add New Link')) ?></span>
                                </button>
                            </td>
                        </tr>
                    </tfoot>
                    <tbody id="sample_staging_items_body">
                    </tbody>
                </table>
            </div>
            <div class="field-note">
                <?= /* @noEscape */ __('Alphanumeric, dash and underscore characters
                are recommended for filenames. Improper characters are replaced with \'_\'.')?>
            </div>
        </div>
    </div>
</fieldset>
<?php
$formData = [
    'uploadUrl' => $escaper->escapeUrl($block->getUrl('marketplace/product_downloadable_file/upload', ['type' => 'samples', '_secure' => $block->getRequest()->isSecure()])),
    'uploadJsonSampleData' => $block->getFileUploaderJsonData(),
    'downloadableLinkInfo' => $block->getDownloadableSampleInfo()
];
$serializedFormData = $viewModel->getJsonHelper()->jsonEncode($formData);
?>

<script type="text/x-magento-init">
    {
        "*": {
            "Branch8_MarketplaceStaging/js/downloadable/samples": <?= /* @noEscape */ $serializedFormData; ?>
        }
    }
</script>
