<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<?php if ($block->getCurrentCategory() && ($block->isContentMode() || $block->isMixedMode())) : ?>
  <div class="category-cms-banner">
    <?= $block->getCmsBlockHtml() ?>
  </div>
<?php endif; ?>