<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<?php if ($_name = $block->getCurrentCategory()->getName()) :?>
    <div class="category-name">
        <?= /* @noEscape */ $_name; ?>
    </div>
<?php endif; ?>
