<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Shop by Brand for Magento 2
 */
/** @var \Amasty\ShopbyBrand\Block\Widget\BrandList $block */
/** @var \Magento\Framework\Escaper $escaper */

$brandItemPadding = 20;
$brandItemBorder = 2;
$items = $block->getIndex();
$columns = abs((int)$block->getData('columns'));
$brandLetters = $block->getAllLetters();
$chAlphabet = ['ㄅ','ㄆ','ㄇ','ㄈ','ㄉ','ㄊ','ㄋ','ㄌ','ㄍ','ㄎ','ㄏ','ㄐ','ㄑ','ㄒ','ㄓ','ㄔ','ㄕ','ㄖ','ㄗ','ㄘ','ㄙ','ㄧ','ㄨ','ㄩ','ㄚ','ㄛ','ㄜ','ㄝ','ㄞ','ㄟ','ㄠ','ㄡ','ㄢ','ㄣ','ㄤ','ㄥ','ㄦ'];
$isShowCount = $block->isShowCount();
$isShowLogos = $block->isShowBrandLogo();
$imgWidth = $block->getImageWidth();
$imgHeight = $block->getImageHeight() ? $block->getImageHeight() . 'px' : 'inherit';
$imgHeightWithOffset = $block->getImageHeight() ? (($block->getImageHeight() + $brandItemPadding) . 'px') : 'inherit';
$filterDisplayAll = $block->isFilterDisplayAll();
$display_zero = $block->isDisplayZero();
$width = floor(100 / $columns);
$fontSizeMultiplier = 0.65;
$brandListClass = 'ambrands-widget-' . random_int(1, 1000);
?>
<?php if ($block->isShowSearch() || !$items): ?>
<div class="ambrands-brandlist-widget <?= /* @noEscape */ $brandListClass ?>">
    <div class="ambrands-brandlist-title">
        <span><?= __("品牌搜尋") ?></span>
    </div>
    <div class="content">
        <?php if ($items): ?>
            <?php $isShowSearch = $block->isShowSearch() ?>
            <?php $isShowFilter = $block->isShowFilter() ?>

            <?php if ($isShowSearch || $isShowFilter): ?>
                <div class="ambrands-filters-block">
                    <?= $block->getSearchHtml() ?>
                    <?php if ($isShowFilter): ?>
                        <div class="ambrands-letters-filter">
                            <div class="ambrands-letters">
                                <button class="ambrands-letter -letter-all -active"
                                        data-ambrands-js="filter-letter"
                                        title="<?= $escaper->escapeHtmlAttr(__('All Brands')) ?>">
                                    <?= $escaper->escapeHtml(__('All Brands')) ?>
                                </button>
                                <?php if ($filterDisplayAll): ?>
                                    <?php foreach (array_merge(range('A', 'Z'), ['#']) as $letter): ?>
                                        <button data-ambrands-js="filter-letter"
                                                class="ambrands-letter ambrands-letter-en <?= (!(in_array($letter, $brandLetters['en'])))
                                                    ? '-disabled'
                                                    : 'letter-' . $escaper->escapeHtmlAttr($letter) ?>">
                                            <span class="txt"><?= $escaper->escapeHtml($letter) ?></span>
                                        </button>
                                    <?php endforeach; ?>
                                    <?php foreach ($chAlphabet as $letter): ?>
                                        <button data-ambrands-js="filter-letter"
                                                class="ambrands-letter ambrands-letter-ch <?= (!(in_array($letter, $brandLetters['ch'])))
                                                    ? '-disabled'
                                                    : 'letter-' . $escaper->escapeHtmlAttr($letter) ?>">
                                            <span class="txt"><?= $escaper->escapeHtml($letter) ?></span>
                                        </button>
                                    <?php endforeach; ?>
                                <?php else: ?>
                                    <?php foreach ($brandLetters['en'] as $letter): ?>
                                        <button data-ambrands-js="filter-letter"
                                                class="ambrands-letter ambrands-letter-en letter-<?= $escaper->escapeHtmlAttr($letter) ?>">
                                            <?= $escaper->escapeHtml($letter) ?>
                                        </button>
                                    <?php endforeach; ?>
                                    <?php foreach ($brandLetters['ch'] as $letter): ?>
                                        <button data-ambrands-js="filter-letter"
                                                class="ambrands-letter ambrands-letter-ch letter-<?= $escaper->escapeHtmlAttr($letter) ?>">
                                            <?= $escaper->escapeHtml($letter) ?>
                                        </button>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </div>
                            <div class="ambrands-switch-box">
                                <div class="ambrands-switch-lang">
                                    <button class="ambrands-lang-en active">
                                        <span><?= __('En')?></span>
                                    </button>
                                    <button class="ambrands-lang-cn">
                                        <span><?= __('Cn')?></span>
                                    </button>
                                </div>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>
            <?php endif; ?>

            <?php foreach ($items['en'] as $letters): ?>
                <section class="ambrands-letters-list">
                    <?php foreach ($letters as $letter => $options): ?>
                        <div class="ambrands-letter ambrands-letter-en letter-<?= $escaper->escapeHtml($letter) ?>"
                             data-ambrands-js="brand-letter">
                            <h3 class="ambrands-title">
                                <span class="txt"><?= $escaper->escapeHtml($letter) ?></span>
                            </h3>
                            <ul class="ambrands-content">
                                <?php foreach ($options as $option): ?>
                                    <li class="ambrands-brand-item <?= /* @noEscape */ !$isShowLogos ? '-no-logo' : '' ?>"
                                        <?= /** @noEscape */ $block->getTooltipAttribute($option) ?>>
                                        <a href="<?= $escaper->escapeUrl($option['url']) ?>"
                                           class="ambrands-inner"
                                           title="<?= $escaper->escapeHtmlAttr($option['label']) ?>">
                                            <?php if ($isShowLogos): ?>
                                                <?php if ($option['img']): ?>
                                                    <span class="ambrands-image-block">
                                                <img class="ambrands-image"
                                                     src="<?= $escaper->escapeUrl($option['img']) ?>"
                                                     title="<?= $escaper->escapeHtmlAttr($option['alt']) ?>"
                                                     alt="<?= $escaper->escapeHtmlAttr($option['alt']) ?>" />
                                            </span>
                                                <?php else: ?>
                                                    <span class="ambrands-image-block">
                                                <span class="ambrands-empty"><?= $escaper->escapeHtml($option['label']) ?></span>
                                            </span>
                                                <?php endif ?>
                                            <?php endif ?>
                                            <span class="ambrands-label">
                                        <?= $escaper->escapeHtml($option['label']) ?>
                                                <?php if ($isShowCount): ?>
                                                    <span class="ambrands-count"><?= $escaper->escapeHtml($option['cnt']) ?></span>
                                                <?php endif; ?>
                                    </span>
                                        </a>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    <?php endforeach; ?>
                </section>
            <?php endforeach; ?>
            <?php foreach ($items['ch'] as $letters): ?>
                <section class="ambrands-letters-list">
                    <?php foreach ($letters as $letter => $options): ?>
                        <div class="ambrands-letter ambrands-letter-ch letter-<?= $escaper->escapeHtml($letter) ?>"
                             data-ambrands-js="brand-letter">
                            <h3 class="ambrands-title">
                                <span class="txt"><?= $escaper->escapeHtml($letter) ?></span>
                            </h3>
                            <ul class="ambrands-content">
                                <?php foreach ($options as $option): ?>
                                    <li class="ambrands-brand-item <?= /* @noEscape */ !$isShowLogos ? '-no-logo' : '' ?>"
                                        <?= /** @noEscape */ $block->getTooltipAttribute($option) ?>>
                                        <a href="<?= $escaper->escapeUrl($option['url']) ?>"
                                           class="ambrands-inner"
                                           title="<?= $escaper->escapeHtmlAttr($option['label']) ?>">
                                            <?php if ($isShowLogos): ?>
                                                <?php if ($option['img']): ?>
                                                    <span class="ambrands-image-block">
                                                <img class="ambrands-image"
                                                     src="<?= $escaper->escapeUrl($option['img']) ?>"
                                                     title="<?= $escaper->escapeHtmlAttr($option['alt']) ?>"
                                                     alt="<?= $escaper->escapeHtmlAttr($option['alt']) ?>" />
                                            </span>
                                                <?php else: ?>
                                                    <span class="ambrands-image-block">
                                                <span class="ambrands-empty"><?= $escaper->escapeHtml($option['label']) ?></span>
                                            </span>
                                                <?php endif ?>
                                            <?php endif ?>
                                            <span class="ambrands-label">
                                        <?= $escaper->escapeHtml($option['label']) ?>
                                                <?php if ($isShowCount): ?>
                                                    <span class="ambrands-count"><?= $escaper->escapeHtml($option['cnt']) ?></span>
                                                <?php endif; ?>
                                    </span>
                                        </a>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    <?php endforeach; ?>
                </section>
            <?php endforeach; ?>
        <?php else: ?>
            <?= $escaper->escapeHtml(__('Please select brand attribute in Stores -> Configuration -> Amasty Extensions ->
        Improved Layered Navigation: Brands.')) ?>
        <?php endif; ?>
    </div>

    <script type="text/x-magento-init">
        {
        <?php if ($block->isTooltipEnabled()): ?>
             ".ambrands-brand-item[data-amshopby-js='brand-tooltip']": {
                 "amShopbyTooltipInit": {
                    "position": {
                        "my": "left-25 bottom-15"
                    },
                    "selector": "li"
                 }
             },
         <?php endif ?>
        "*": {
            "amBrandsFilterInit": {
               "element": "[data-ambrands-js='filter-letter']",
               "target": "[data-ambrands-js='brand-letter']"
           }
        }
    }
    </script>
</div>
<?php else: ?>
<?php
foreach ($items['en'] as $k => $letters) {
    foreach ($letters as $letter => $options) {
        foreach ($options as $key => $option) {
            $items['en'][$k][$letter][$key] = [];
            $items['en'][$k][$letter][$key]['url'] = $option['url'] ?? '';
            $items['en'][$k][$letter][$key]['label'] = $option['label'] ?? '';
            $items['en'][$k][$letter][$key]['img'] = $option['img'] ?? '';
            $items['en'][$k][$letter][$key]['alt'] = $option['alt'] ?? '';
            $items['en'][$k][$letter][$key]['cnt'] = $option['cnt'] ?? '';
        }
    }
}
foreach ($items['ch'] as $k => $letters) {
    foreach ($letters as $letter => $options) {
        foreach ($options as $key => $option) {
            $items['ch'][$k][$letter][$key] = [];
            $items['ch'][$k][$letter][$key]['url'] = $option['url'] ?? '';
            $items['ch'][$k][$letter][$key]['label'] = $option['label'] ?? '';
            $items['ch'][$k][$letter][$key]['img'] = $option['img'] ?? '';
            $items['ch'][$k][$letter][$key]['alt'] = $option['alt'] ?? '';
            $items['ch'][$k][$letter][$key]['cnt'] = $option['cnt'] ?? '';
        }
    }
}
?>
<div id="react-brand-widget" class="react-brand-widget"></div>
<script>
    require([
        "Amasty_ShopbyBrand/js/brand-init-react",
        "Branch8_React/js/brand"
    ], function (callBackApplyBrandFilter) {
        window.CPBrand({ data: {
                items: <?= json_encode($items, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) ?>,
                isShowFilter: <?= $block->isShowFilter() ? 'true' : 'false' ?>,
                filterDisplayAll: <?= $filterDisplayAll ? 'true' : 'false' ?>,
                title: "<?= __('品牌搜尋')->render() ?>",
                labelAll: "<?= __('All Brands')->render() ?>",
                labelLangEn: "<?= __('En')->render() ?>",
                labelLangCh: "<?= __('Cn')->render() ?>",
                isShowLogos: <?= $isShowLogos ? 'true' : 'false' ?>,
                brandLetters: <?= json_encode($brandLetters, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) ?>,
                enAlphabet: <?= json_encode(array_merge(range('A', 'Z'), ['#'])) ?>,
                chAlphabet: <?= json_encode($chAlphabet, JSON_UNESCAPED_UNICODE) ?>
            }, elCls: "react-brand-widget", callBackApplyBrandFilter});
        });
</script>
<?php endif; ?>
