<?php
/** @var  $block \Magenest\NotificationBox\Block\Notification\Notification */
/** show icon notification when customer is login */
?>
<div class="notificationBox" data-bind="scope: 'notificationBox'" hidden>
    <div class="magenest-notification" data-bind="visible: visibleNotificationBox">
        <span class="magenest-notification-action">
            <span class="magenest-notification-icon" >
                <img src="<?=$block->getViewFileUrl('Magenest_NotificationBox::image/noti.png');?>" alt="">
                <span class="text"><?= $block->escapeHtml(__('Notif')) ?></span>
            </span>
            <span class="magenest-notification-count" data-bind="text: totalNotificationUnread"></span>
        </span>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "notificationBox": {
                        "component": "Magenest_NotificationBox/js/notification/notification",
                        "template" : "Magenest_NotificationBox/notification",
                        "config": {
                                    "url"                           : "<?=$block->getUrl("notification/customer/notification")?>",
                                    "currentUrl"                    : "<?=$block->getUrl()?>",
                                    "backgroundColorValue"          : "<?=$block->getThemeColor()?>",
                                    "boxPositionClass"              : "<?=$block->getBoxPosition()?>",
                                    "notificationBoxWidth"          : "<?=$block->getBoxWidth()?>"
                        }
                    }
                }
            }
        }
    }
</script>

