<?php

/** @var \Branch8\Sales\Block\ParentOrder\Items $block */

$data = json_encode([
    "updateUrl" => $block->getUrl('customsales/order/statusupdate'),
]);
?>
<?php if ($this->getItem()): ?>
    <tr>
        <td>
            <?php $subOrder = $block->getSubOrderById($this->getItem()->getOrderId());?>
            <?php $progressType = $block->getProgressType($subOrder);?>
            <?php $currentDotPhase = $block->getStatusDotPhase($this->getItem());?>

            <ol class="ProgressBar">
            <?php $stop = 0;?>
            <?php foreach ($block->getProgressBar($subOrder, $this->getItem()) as $key => $dot): ?>
                <li class="ProgressBar-step">
                    <?php if ($currentDotPhase == $dot['Status'] || $stop >= $key): ?>
                        <svg class="ProgressBar-icon"><use xlink:href="#checkmark-bold"/></svg>
                        <?php $stop = $key;?>
                    <?php endif;?>

                    <span class="ProgressBar-stepLabel"><?=$block->escapeHtml(__($dot['Label']))?></span>
                    <?php if (isset($dot['Time']) && $stop >= $key): ?>
                        <span class="ProgressBar-stepTime"><?=$block->formatDate($dot['Time'], \IntlDateFormatter::MEDIUM, true)?></span>
                    <?php endif;?>
                </li>
            <?php endforeach;?>
            </ol>
        </td>
    </tr>


    <!-- 可申請退換貨 Can Create Rma Request-->
    <?php if($block->canCreateRmaRequest($this->getItem())):?>
        <?php $rmaButtunLabel = __('Return or Exchange');?>
        <tr>
          <td>
            <button
            id="request_return_exchange"
            type="submit"
            data-item-id = "<?=$this->getItem()->getItemId()?>"
            data-order-id = "<?=$this->getItem()->getOrderId()?>"
            title="<?=$block->escapeHtml($rmaButtunLabel)?>"
            class="action-return-exchange-primary">

            <span> <?=$block->escapeHtml($rmaButtunLabel)?> </span>
            </button>
          </td>
        </tr>
    <?php endif;?>


    
    <!-- 取消退換貨 Cancel Rma Application-->
    <?php if($block->canCancelRmaRequest($this->getItem()->getFlowStatus())):?>
        <tr>
          <td>
            <form id="cancel_rma_request" action="/customsales/order/cancelrma" method="post">
            </form>
            <button
            id="request_cancel_return_exchange"
            type="submit"
            data-rma-id = "<?=$block->getRmaId($this->getItem())?>"
            data-item-id = "<?=$this->getItem()->getItemId()?>"
            title="<?=$block->escapeHtml('Cancel Rma Application')?>"
            class="action-cancel-return-exchange-primary">

            <span> <?=$block->escapeHtml('Cancel Rma Application')?> </span>
            </button>
           
          </td>
        </tr>
    <?php endif;?>


<?php endif;?>

<script type="text/x-magento-init">
    {
        "body": {
             "Branch8_Sales/js/updateOrderStatus": <?=/* @noEscape */$data?>
        }
    }
</script>
