<?php
/** @var \Magento\Backend\Block\Page\RequireJs $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

$escaper        = $escaper ?? $block;
$secureRenderer = $secureRenderer ?? $block->getData('secure_html_renderer_polyfill');
$alpineJsPath   = $block->getData('alpinejs_path');
?>
<?php if ($alpineJsPath): ?>
    <script src="<?php echo $block->getViewFileUrl($alpineJsPath); ?>" async></script>
<?php endif; ?>

<?php
$requireJsConfig = [
    'baseUrl' => $block->getViewFileUrl('/'),
];

$configModifier = $block->getConfigModifier();
$requireJsConfig = $configModifier instanceof \Magento\Backend\ViewModel\RequireJsConfigModifierInterface
    ? $configModifier->modify($requireJsConfig)
    : $requireJsConfig;

$scriptString = '
    var BASE_URL = \'' . /* @noEscape */ $block->getUrl('*') . '\';
    var FORM_KEY = \'' . /* @noEscape */ $block->getFormKey() . '\';
    var require = ' . /* @noEscape */ json_encode($requireJsConfig) .';';

echo /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false);
?>
