<?php

namespace Branch8\Customer\Block\Ticket;

use Branch8\HotaiCore\Model\Product\VirtualProductType;
use Branch8\HotaiCore\Model\Ticket\Status;

class TicketMockData
{

    // 增加TYPE後記得確認看看Helper
    const TYPE_DEFAULT                   = 1; // 預設
    const TYPE_YOXI_TICKET               = 2; // YOXI票券
    const TYPE_EDENRED_TICKET            = 3; // 宜睿票券
    const TYPE_FAMILY_BONUS_PIN_TICKET   = 4; // 全家紅利PIN票券
    const TYPE_GENERAL_NOTIFY_TICKET     = 5; // 通用型核銷票券
    const TYPE_GENERAL_NON_NOTIFY_TICKET = 6; // 通用型非核銷票券 product.is_offline_operation 1,0

   /**
    product = {
        id : 1,
        name: "FamilyMart 全家-中杯熱拿鐵",
        exchange_url: "https://www.google.com",
        is_offline_operation: 1, //0
   }
    */
    const TICKETS = [
        Status::STATUS_UNUSED => [
            [
                'record_id' => 1,
                'type' => VirtualProductType::TYPE_FAMILY_BONUS_PIN_TICKET,
                'batch_code' => 'ISD9D3C6',
                'customer_id' => 1,
                'belong_to_product_id' => 1,
                'ticket_unique_content' => "ISD9D3C6", //serial_number
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/11/02',
                'status' => Status::STATUS_UNUSED,
                'memo' => '',
            ],
            [
                'record_id' => 2,
                'type' => VirtualProductType::TYPE_YOXI_TICKET,
                'batch_code' => 'ZU85S1O0',
                'customer_id' => 1,
                'belong_to_product_id' => 2,
                'ticket_unique_content' => "ZU85S1O0",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/10/26',
                'status' => Status::STATUS_UNUSED,
                'memo' => '',
            ],
            [
                'record_id' => 3,
                'type' => VirtualProductType::TYPE_GENERAL_NON_NOTIFY_TICKET,
                'batch_code' => '1RODGEDU',
                'customer_id' => 1,
                'belong_to_product_id' =>  3,
                'ticket_unique_content' => "1RODGEDU",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/11/05',
                'status' => Status::STATUS_UNUSED,
                'memo' => '',
            ],
            [
                'record_id' => 4,
                'type' => VirtualProductType::TYPE_EDENRED_TICKET,
                'batch_code' => 'NLNKT92N',
                'customer_id' => 1,
                'belong_to_product_id' => 4,
                'ticket_unique_content' => "NLNKT92N",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/11/05',
                'status' => Status::STATUS_UNUSED,
                'memo' => '',
            ],
            [
                'record_id' => 5,
                'type' => VirtualProductType::TYPE_YOXI_TICKET,
                'batch_code' => 'ZU85S1O0',
                'customer_id' => 1,
                'belong_to_product_id' => 5,
                'ticket_unique_content' => "ZU85S1O0",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/10/26',
                'status' => Status::STATUS_UNUSED,
                'memo' => '',
            ],
            [
                'record_id' => 6,
                'type' => VirtualProductType::TYPE_GENERAL_NON_NOTIFY_TICKET,
                'batch_code' => 'OREYHMVE',
                'customer_id' => 1,
                'belong_to_product_id' => 6,
                'ticket_unique_content' => "OREYHMVE",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/11/05',
                'status' => Status::STATUS_UNUSED,
                'memo' => '',
            ],
            [
                'record_id' => 7,
                'type' => VirtualProductType::TYPE_FAMILY_BONUS_PIN_TICKET,
                'batch_code' => 'HA0O4Q7Q',
                'customer_id' => 1,
                'belong_to_product_id' => 7,
                'ticket_unique_content' => "HA0O4Q7Q", //serial_number
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/11/02',
                'status' => Status::STATUS_UNUSED,
                'memo' => '',
            ],
            [
                'record_id' => 8,
                'type' => VirtualProductType::TYPE_YOXI_TICKET,
                'batch_code' => '8TTDC2FJ',
                'customer_id' => 1,
                'belong_to_product_id' => 8,
                'ticket_unique_content' => "8TTDC2FJ",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/10/26',
                'status' => Status::STATUS_UNUSED,
                'memo' => '',
            ],
            [
                'record_id' => 9,
                'type' => VirtualProductType::TYPE_GENERAL_NON_NOTIFY_TICKET,
                'batch_code' => 'LQM8JA3I',
                'customer_id' => 1,
                'belong_to_product_id' => 9,
                'ticket_unique_content' => "1RODGEDU",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/11/05',
                'status' => Status::STATUS_UNUSED,
                'memo' => '',
            ],
            [
                'record_id' => 10,
                'type' => VirtualProductType::TYPE_DEFAULT,
                'batch_code' => 'NMQD2955',
                'customer_id' => 1,
                'belong_to_product_id' => 10,
                'ticket_unique_content' => "NLNKT92N",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/11/05',
                'status' => Status::STATUS_UNUSED,
                'memo' => '',
                'is_lottery' => true,
                'has_drawn' => false,
                'is_winner' => false,
            ],
            [
                'record_id' => 11,
                'type' => VirtualProductType::TYPE_GENERAL_NOTIFY_TICKET,
                'batch_code' => 'ISD9D3C6',
                'customer_id' => 1,
                'belong_to_product_id' => 11,
                'ticket_unique_content' => "ISD9D3C6", //serial_number
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/11/04',
                'status' => Status::STATUS_UNUSED,
                'memo' => '',
            ],
            [
                'record_id' => 12,
                'type' => VirtualProductType::TYPE_GENERAL_NOTIFY_TICKET,
                'batch_code' => 'ZU85S1O0',
                'customer_id' => 1,
                'belong_to_product_id' => 12,
                'ticket_unique_content' => "ZU85S1O0",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/11/04',
                'status' => Status::STATUS_UNUSED,
                'memo' => '',
            ],
            [
                'record_id' => 13,
                'type' => VirtualProductType::TYPE_GENERAL_NON_NOTIFY_TICKET,
                'batch_code' => '1RODGEDU',
                'customer_id' => 1,
                'belong_to_product_id' => 3,
                'ticket_unique_content' => "1RODGEDU",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/11/04',
                'status' => Status::STATUS_UNUSED,
                'memo' => '',
            ],
            [
                'record_id' => 14,
                'type' => VirtualProductType::TYPE_GENERAL_NON_NOTIFY_TICKET,
                'batch_code' => 'NLNKT92N',
                'customer_id' => 1,
                'belong_to_product_id' => 4,
                'ticket_unique_content' => "NLNKT92N",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/11/04',
                'status' => Status::STATUS_UNUSED,
                'memo' => '',
            ],
            [
                'record_id' => 15,
                'type' => VirtualProductType::TYPE_YOXI_TICKET,
                'batch_code' => 'ZU85S1O0',
                'customer_id' => 1,
                'belong_to_product_id' => 5,
                'ticket_unique_content' => "ZU85S1O0",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/11/04',
                'status' => Status::STATUS_UNUSED,
                'memo' => '',
            ],
            [
                'record_id' => 16,
                'type' => VirtualProductType::TYPE_GENERAL_NON_NOTIFY_TICKET,
                'batch_code' => 'OREYHMVE',
                'customer_id' => 1,
                'belong_to_product_id' => 6,
                'ticket_unique_content' => "OREYHMVE",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/11/04',
                'status' => Status::STATUS_UNUSED,
                'memo' => '',
            ],
            [
                'record_id' => 17,
                'type' => VirtualProductType::TYPE_FAMILY_BONUS_PIN_TICKET,
                'batch_code' => 'HA0O4Q7Q',
                'customer_id' => 1,
                'belong_to_product_id' => 7,
                'ticket_unique_content' => "HA0O4Q7Q", //serial_number
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/11/04',
                'status' => Status::STATUS_UNUSED,
                'memo' => '',
            ],
            [
                'record_id' => 18,
                'type' => VirtualProductType::TYPE_YOXI_TICKET,
                'batch_code' => '8TTDC2FJ',
                'customer_id' => 1,
                'belong_to_product_id' => 8,
                'ticket_unique_content' => "8TTDC2FJ",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/11/04',
                'status' => Status::STATUS_UNUSED,
                'memo' => '',
            ],
            [
                'record_id' => 19,
                'type' => VirtualProductType::TYPE_GENERAL_NON_NOTIFY_TICKET,
                'batch_code' => 'LQM8JA3I',
                'customer_id' => 1,
                'belong_to_product_id' => 9,
                'ticket_unique_content' => "1RODGEDU",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/11/04',
                'status' => Status::STATUS_UNUSED,
                'memo' => '',
            ],
            [
                'record_id' => 20,
                'type' => VirtualProductType::TYPE_GENERAL_NON_NOTIFY_TICKET,
                'batch_code' => 'NMQD2955',
                'customer_id' => 1,
                'belong_to_product_id' => 10,
                'ticket_unique_content' => "NLNKT92N",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/11/04',
                'status' => Status::STATUS_UNUSED,
                'memo' => '',
            ],
            [
                'record_id' => 21,
                'type' => VirtualProductType::TYPE_FAMILY_BONUS_PIN_TICKET,
                'batch_code' => 'ASMZE7ZC',
                'customer_id' => 1,
                'belong_to_product_id' => 1,
                'ticket_unique_content' => "ASMZE7ZC", //serial_number
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/11/04',
                'status' => Status::STATUS_UNUSED,
                'memo' => '',
            ],
            [
                'record_id' => 22,
                'type' => VirtualProductType::TYPE_YOXI_TICKET,
                'batch_code' => 'S1B5WVZK',
                'customer_id' => 1,
                'belong_to_product_id' => 2,
                'ticket_unique_content' => "S1B5WVZK",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/11/04',
                'status' => Status::STATUS_UNUSED,
                'memo' => '',
            ],
            [
                'record_id' => 23,
                'type' => VirtualProductType::TYPE_GENERAL_NON_NOTIFY_TICKET,
                'batch_code' => '4DKH061A',
                'customer_id' => 1,
                'belong_to_product_id' => 3,
                'ticket_unique_content' => "4DKH061A",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/11/04',
                'status' => Status::STATUS_UNUSED,
                'memo' => '',
            ],
            [
                'record_id' => 24,
                'type' => VirtualProductType::TYPE_GENERAL_NON_NOTIFY_TICKET,
                'batch_code' => '1AH3Z716',
                'customer_id' => 1,
                'belong_to_product_id' => 4,
                'ticket_unique_content' => "1AH3Z716",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/11/04',
                'status' => Status::STATUS_UNUSED,
                'memo' => '',
            ],
            [
                'record_id' => 25,
                'type' => VirtualProductType::TYPE_YOXI_TICKET,
                'batch_code' => 'WA8HW6RX',
                'customer_id' => 1,
                'belong_to_product_id' => 5,
                'ticket_unique_content' => "WA8HW6RX",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/11/04',
                'status' => Status::STATUS_UNUSED,
                'memo' => '',
            ],
            [
                'record_id' => 26,
                'type' => VirtualProductType::TYPE_GENERAL_NON_NOTIFY_TICKET,
                'batch_code' => 'CTE14RCZ',
                'customer_id' => 1,
                'belong_to_product_id' => 6,
                'ticket_unique_content' => "CTE14RCZ",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/11/04',
                'status' => Status::STATUS_UNUSED,
                'memo' => '',
            ],
            [
                'record_id' => 27,
                'type' => VirtualProductType::TYPE_FAMILY_BONUS_PIN_TICKET,
                'batch_code' => 'AMP8X4BH',
                'customer_id' => 1,
                'belong_to_product_id' => 7,
                'ticket_unique_content' => "AMP8X4BH", //serial_number
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/11/04',
                'status' => Status::STATUS_UNUSED,
                'memo' => '',
            ],
            [
                'record_id' => 28,
                'type' => VirtualProductType::TYPE_YOXI_TICKET,
                'batch_code' => '5B6G7FHY',
                'customer_id' => 1,
                'belong_to_product_id' => 8,
                'ticket_unique_content' => "5B6G7FHY",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/11/04',
                'status' => Status::STATUS_UNUSED,
                'memo' => '',
            ],
            [
                'record_id' => 29,
                'type' => VirtualProductType::TYPE_GENERAL_NON_NOTIFY_TICKET,
                'batch_code' => 'WV7XGWLH',
                'customer_id' => 1,
                'belong_to_product_id' => 9,
                'ticket_unique_content' => "WV7XGWLH",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/11/04',
                'status' => Status::STATUS_UNUSED,
                'memo' => '',
            ],
            [
                'record_id' => 30,
                'type' => VirtualProductType::TYPE_GENERAL_NON_NOTIFY_TICKET,
                'batch_code' => 'I9NV4B66',
                'customer_id' => 1,
                'belong_to_product_id' => 10,
                'ticket_unique_content' => "I9NV4B66",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/11/04',
                'status' => Status::STATUS_UNUSED,
                'memo' => '',
            ]
        ],
        Status::STATUS_USED => [
            [
                'record_id' => 31,
                'type' => VirtualProductType::TYPE_FAMILY_BONUS_PIN_TICKET,
                'batch_code' => 'ISD9D3C6',
                'customer_id' => 1,
                'belong_to_product_id' => 1,
                'ticket_unique_content' => "ISD9D3C6", //serial_number
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_USED,
                'memo' => '',
            ],
            [
                'record_id' => 32,
                'type' => VirtualProductType::TYPE_YOXI_TICKET,
                'batch_code' => 'ZU85S1O0',
                'customer_id' => 1,
                'belong_to_product_id' => 2,
                'ticket_unique_content' => "ZU85S1O0",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_USED,
                'memo' => '',
            ],
            [
                'record_id' => 33,
                'type' => VirtualProductType::TYPE_GENERAL_NON_NOTIFY_TICKET,
                'batch_code' => '1RODGEDU',
                'customer_id' => 1,
                'belong_to_product_id' => 3,
                'ticket_unique_content' => "1RODGEDU",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_USED,
                'memo' => '',
            ],
            [
                'record_id' => 34,
                'type' => VirtualProductType::TYPE_EDENRED_TICKET,
                'batch_code' => 'NLNKT92N',
                'customer_id' => 1,
                'belong_to_product_id' => 4,
                'ticket_unique_content' => "NLNKT92N",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_USED,
                'memo' => '',
            ],
            [
                'record_id' => 35,
                'type' => VirtualProductType::TYPE_YOXI_TICKET,
                'batch_code' => 'ZU85S1O0',
                'customer_id' => 1,
                'belong_to_product_id' => 5,
                'ticket_unique_content' => "ZU85S1O0",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_USED,
                'memo' => '',
            ],
            [
                'record_id' => 36,
                'type' => VirtualProductType::TYPE_GENERAL_NON_NOTIFY_TICKET,
                'batch_code' => 'OREYHMVE',
                'customer_id' => 1,
                'belong_to_product_id' => 6,
                'ticket_unique_content' => "OREYHMVE",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_USED,
                'memo' => '',
            ],
            [
                'record_id' => 37,
                'type' => VirtualProductType::TYPE_FAMILY_BONUS_PIN_TICKET,
                'batch_code' => 'HA0O4Q7Q',
                'customer_id' => 1,
                'belong_to_product_id' => 7,
                'ticket_unique_content' => "HA0O4Q7Q", //serial_number
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_USED,
                'memo' => '',
            ],
            [
                'record_id' => 38,
                'type' => VirtualProductType::TYPE_YOXI_TICKET,
                'batch_code' => '8TTDC2FJ',
                'customer_id' => 1,
                'belong_to_product_id' => 8,
                'ticket_unique_content' => "8TTDC2FJ",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_USED,
                'memo' => '',
            ],
            [
                'record_id' => 39,
                'type' => VirtualProductType::TYPE_GENERAL_NON_NOTIFY_TICKET,
                'batch_code' => 'LQM8JA3I',
                'customer_id' => 1,
                'belong_to_product_id' => 9,
                'ticket_unique_content' => "1RODGEDU",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_USED,
                'memo' => '',
            ],
            [
                'record_id' => 40,
                'type' => VirtualProductType::TYPE_DEFAULT,
                'batch_code' => 'NMQD2955',
                'customer_id' => 1,
                'belong_to_product_id' => 10,
                'ticket_unique_content' => "NLNKT92N",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_USED,
                'memo' => '',
                'is_lottery' => true,
                'has_drawn' => true,
                'is_winner' => true,
            ],
            [
                'record_id' => 41,
                'type' => VirtualProductType::TYPE_GENERAL_NOTIFY_TICKET,
                'batch_code' => 'ISD9D3C6',
                'customer_id' => 1,
                'belong_to_product_id' => 11,
                'ticket_unique_content' => "ISD9D3C6", //serial_number
                'use_start_time' => '2023/08/22',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_USED,
                'memo' => '',
            ],
            [
                'record_id' => 42,
                'type' => VirtualProductType::TYPE_GENERAL_NOTIFY_TICKET,
                'batch_code' => 'ZU85S1O0',
                'customer_id' => 1,
                'belong_to_product_id' => 12,
                'ticket_unique_content' => "ZU85S1O0",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_USED,
                'memo' => '',
            ],
            [
                'record_id' => 43,
                'type' => VirtualProductType::TYPE_GENERAL_NON_NOTIFY_TICKET,
                'batch_code' => '1RODGEDU',
                'customer_id' => 1,
                'belong_to_product_id' => 3,
                'ticket_unique_content' => "1RODGEDU",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_USED,
                'memo' => '',
            ],
            [
                'record_id' => 44,
                'type' => VirtualProductType::TYPE_GENERAL_NON_NOTIFY_TICKET,
                'batch_code' => 'NLNKT92N',
                'customer_id' => 1,
                'belong_to_product_id' => 4,
                'ticket_unique_content' => "NLNKT92N",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_USED,
                'memo' => '',
            ],
            [
                'record_id' => 45,
                'type' => VirtualProductType::TYPE_YOXI_TICKET,
                'batch_code' => 'ZU85S1O0',
                'customer_id' => 1,
                'belong_to_product_id' => 5,
                'ticket_unique_content' => "ZU85S1O0",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_USED,
                'memo' => '',
            ],
            [
                'record_id' => 46,
                'type' => VirtualProductType::TYPE_GENERAL_NON_NOTIFY_TICKET,
                'batch_code' => 'OREYHMVE',
                'customer_id' => 1,
                'belong_to_product_id' => 6,
                'ticket_unique_content' => "OREYHMVE",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_USED,
                'memo' => '',
            ],
            [
                'record_id' => 47,
                'type' => VirtualProductType::TYPE_FAMILY_BONUS_PIN_TICKET,
                'batch_code' => 'HA0O4Q7Q',
                'customer_id' => 1,
                'belong_to_product_id' => 7,
                'ticket_unique_content' => "HA0O4Q7Q", //serial_number
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_USED,
                'memo' => '',
            ],
            [
                'record_id' => 48,
                'type' => VirtualProductType::TYPE_YOXI_TICKET,
                'batch_code' => '8TTDC2FJ',
                'customer_id' => 1,
                'belong_to_product_id' => 8,
                'ticket_unique_content' => "8TTDC2FJ",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_USED,
                'memo' => '',
            ],
            [
                'record_id' => 49,
                'type' => VirtualProductType::TYPE_GENERAL_NON_NOTIFY_TICKET,
                'batch_code' => 'LQM8JA3I',
                'customer_id' => 1,
                'belong_to_product_id' => 9,
                'ticket_unique_content' => "1RODGEDU",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_USED,
                'memo' => '',
            ],
            [
                'record_id' => 50,
                'type' => VirtualProductType::TYPE_GENERAL_NON_NOTIFY_TICKET,
                'batch_code' => 'NMQD2955',
                'customer_id' => 1,
                'belong_to_product_id' => 10,
                'ticket_unique_content' => "NLNKT92N",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_USED,
                'memo' => '',
            ],
            [
                'record_id' => 51,
                'type' => VirtualProductType::TYPE_FAMILY_BONUS_PIN_TICKET,
                'batch_code' => '9OM7HK9O',
                'customer_id' => 1,
                'belong_to_product_id' => 1,
                'ticket_unique_content' => "9OM7HK9O", //serial_number
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_USED,
                'memo' => '',
            ],
            [
                'record_id' => 52,
                'type' => VirtualProductType::TYPE_YOXI_TICKET,
                'batch_code' => '0ODKK0SK',
                'customer_id' => 1,
                'belong_to_product_id' => 2,
                'ticket_unique_content' => "0ODKK0SK",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_USED,
                'memo' => '',
            ],
            [
                'record_id' => 53,
                'type' => VirtualProductType::TYPE_GENERAL_NON_NOTIFY_TICKET,
                'batch_code' => 'B06SD529',
                'customer_id' => 1,
                'belong_to_product_id' => 3,
                'ticket_unique_content' => "B06SD529",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_USED,
                'memo' => '',
            ],
            [
                'record_id' => 54,
                'type' => VirtualProductType::TYPE_GENERAL_NON_NOTIFY_TICKET,
                'batch_code' => 'WP8P6V3I',
                'customer_id' => 1,
                'belong_to_product_id' => 4,
                'ticket_unique_content' => "WP8P6V3I",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_USED,
                'memo' => '',
            ],
            [
                'record_id' => 55,
                'type' => VirtualProductType::TYPE_YOXI_TICKET,
                'batch_code' => '6M6TG67H',
                'customer_id' => 1,
                'belong_to_product_id' => 5,
                'ticket_unique_content' => "6M6TG67H",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_USED,
                'memo' => '',
            ],
            [
                'record_id' => 56,
                'type' => VirtualProductType::TYPE_GENERAL_NON_NOTIFY_TICKET,
                'batch_code' => 'N0CQJ2T3',
                'customer_id' => 1,
                'belong_to_product_id' => 6,
                'ticket_unique_content' => "N0CQJ2T3",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_USED,
                'memo' => '',
            ],
            [
                'record_id' => 57,
                'type' => VirtualProductType::TYPE_FAMILY_BONUS_PIN_TICKET,
                'batch_code' => '5SUU5WB9',
                'customer_id' => 1,
                'belong_to_product_id' => 7,
                'ticket_unique_content' => "5SUU5WB9", //serial_number
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_USED,
                'memo' => '',
            ],
            [
                'record_id' => 58,
                'type' => VirtualProductType::TYPE_YOXI_TICKET,
                'batch_code' => '2QM0Z2FI',
                'customer_id' => 1,
                'belong_to_product_id' => 8,
                'ticket_unique_content' => "2QM0Z2FI",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_USED,
                'memo' => '',
            ],
            [
                'record_id' => 59,
                'type' => VirtualProductType::TYPE_GENERAL_NON_NOTIFY_TICKET,
                'batch_code' => '8G5IYRA3',
                'customer_id' => 1,
                'belong_to_product_id' => 9,
                'ticket_unique_content' => "8G5IYRA3",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_USED,
                'memo' => '',
            ],
            [
                'record_id' => 60,
                'type' => VirtualProductType::TYPE_GENERAL_NON_NOTIFY_TICKET,
                'batch_code' => 'HX0GTLO6',
                'customer_id' => 1,
                'belong_to_product_id' => 10,
                'ticket_unique_content' => "HX0GTLO6",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_USED,
                'memo' => '',
            ]
        ],
        Status::STATUS_OVER_DUE => [
            [
                'record_id' => 61,
                'type' => VirtualProductType::TYPE_FAMILY_BONUS_PIN_TICKET,
                'batch_code' => 'ASMZE7ZC',
                'customer_id' => 1,
                'belong_to_product_id' => 1,
                'ticket_unique_content' => "ASMZE7ZC", //serial_number
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_OVER_DUE,
                'memo' => '',
            ],
            [
                'record_id' => 62,
                'type' => VirtualProductType::TYPE_YOXI_TICKET,
                'batch_code' => 'S1B5WVZK',
                'customer_id' => 1,
                'belong_to_product_id' => 2,
                'ticket_unique_content' => "S1B5WVZK",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_OVER_DUE,
                'memo' => '',
            ],
            [
                'record_id' => 63,
                'type' => VirtualProductType::TYPE_GENERAL_NON_NOTIFY_TICKET,
                'batch_code' => '4DKH061A',
                'customer_id' => 1,
                'belong_to_product_id' => 3,
                'ticket_unique_content' => "4DKH061A",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_OVER_DUE,
                'memo' => '',
            ],
            [
                'record_id' => 64,
                'type' => VirtualProductType::TYPE_EDENRED_TICKET,
                'batch_code' => '1AH3Z716',
                'customer_id' => 1,
                'belong_to_product_id' => 4,
                'ticket_unique_content' => "1AH3Z716",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_OVER_DUE,
                'memo' => '',
            ],
            [
                'record_id' => 65,
                'type' => VirtualProductType::TYPE_YOXI_TICKET,
                'batch_code' => 'WA8HW6RX',
                'customer_id' => 1,
                'belong_to_product_id' => 5,
                'ticket_unique_content' => "WA8HW6RX",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_OVER_DUE,
                'memo' => '',
            ],
            [
                'record_id' => 66,
                'type' => VirtualProductType::TYPE_GENERAL_NON_NOTIFY_TICKET,
                'batch_code' => 'CTE14RCZ',
                'customer_id' => 1,
                'belong_to_product_id' => 6,
                'ticket_unique_content' => "CTE14RCZ",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_OVER_DUE,
                'memo' => '',
            ],
            [
                'record_id' => 67,
                'type' => VirtualProductType::TYPE_FAMILY_BONUS_PIN_TICKET,
                'batch_code' => 'AMP8X4BH',
                'customer_id' => 1,
                'belong_to_product_id' => 7,
                'ticket_unique_content' => "AMP8X4BH", //serial_number
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_OVER_DUE,
                'memo' => '',
            ],
            [
                'record_id' => 68,
                'type' => VirtualProductType::TYPE_YOXI_TICKET,
                'batch_code' => '5B6G7FHY',
                'customer_id' => 1,
                'belong_to_product_id' => 8,
                'ticket_unique_content' => "5B6G7FHY",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_OVER_DUE,
                'memo' => '',
            ],
            [
                'record_id' => 69,
                'type' => VirtualProductType::TYPE_GENERAL_NON_NOTIFY_TICKET,
                'batch_code' => 'WV7XGWLH',
                'customer_id' => 1,
                'belong_to_product_id' => 9,
                'ticket_unique_content' => "WV7XGWLH",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_OVER_DUE,
                'memo' => '',
            ],
            [
                'record_id' => 70,
                'type' => VirtualProductType::TYPE_DEFAULT,
                'batch_code' => 'I9NV4B66',
                'customer_id' => 1,
                'belong_to_product_id' => 10,
                'ticket_unique_content' => "I9NV4B66",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_OVER_DUE,
                'memo' => '',
                'is_lottery' => true,
                'has_drawn' => true,
                'is_winner' => false
            ],
            [
                'record_id' => 71,
                'type' => VirtualProductType::TYPE_GENERAL_NOTIFY_TICKET,
                'batch_code' => '9OM7HK9O',
                'customer_id' => 1,
                'belong_to_product_id' => 11,
                'ticket_unique_content' => "9OM7HK9O", //serial_number
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_OVER_DUE,
                'memo' => '',
            ],
            [
                'record_id' => 72,
                'type' => VirtualProductType::TYPE_GENERAL_NOTIFY_TICKET,
                'batch_code' => '0ODKK0SK',
                'customer_id' => 1,
                'belong_to_product_id' => 12,
                'ticket_unique_content' => "0ODKK0SK",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_OVER_DUE,
                'memo' => '',
            ],
            [
                'record_id' => 73,
                'type' => VirtualProductType::TYPE_GENERAL_NON_NOTIFY_TICKET,
                'batch_code' => 'B06SD529',
                'customer_id' => 1,
                'belong_to_product_id' => 3,
                'ticket_unique_content' => "B06SD529",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_OVER_DUE,
                'memo' => '',
            ],
            [
                'record_id' => 74,
                'type' => VirtualProductType::TYPE_GENERAL_NON_NOTIFY_TICKET,
                'batch_code' => 'WP8P6V3I',
                'customer_id' => 1,
                'belong_to_product_id' => 4,
                'ticket_unique_content' => "WP8P6V3I",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_OVER_DUE,
                'memo' => '',
            ],
            [
                'record_id' => 75,
                'type' => VirtualProductType::TYPE_YOXI_TICKET,
                'batch_code' => '6M6TG67H',
                'customer_id' => 1,
                'belong_to_product_id' => 5,
                'ticket_unique_content' => "6M6TG67H",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_OVER_DUE,
                'memo' => '',
            ],
            [
                'record_id' => 76,
                'type' => VirtualProductType::TYPE_GENERAL_NON_NOTIFY_TICKET,
                'batch_code' => 'N0CQJ2T3',
                'customer_id' => 1,
                'belong_to_product_id' => 6,
                'ticket_unique_content' => "N0CQJ2T3",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_OVER_DUE,
                'memo' => '',
            ],
            [
                'record_id' => 77,
                'type' => VirtualProductType::TYPE_FAMILY_BONUS_PIN_TICKET,
                'batch_code' => '5SUU5WB9',
                'customer_id' => 1,
                'belong_to_product_id' => 7,
                'ticket_unique_content' => "5SUU5WB9", //serial_number
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_OVER_DUE,
                'memo' => '',
            ],
            [
                'record_id' => 78,
                'type' => VirtualProductType::TYPE_YOXI_TICKET,
                'batch_code' => '2QM0Z2FI',
                'customer_id' => 1,
                'belong_to_product_id' => 8,
                'ticket_unique_content' => "2QM0Z2FI",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_OVER_DUE,
                'memo' => '',
            ],
            [
                'record_id' => 79,
                'type' => VirtualProductType::TYPE_GENERAL_NON_NOTIFY_TICKET,
                'batch_code' => '8G5IYRA3',
                'customer_id' => 1,
                'belong_to_product_id' => 9,
                'ticket_unique_content' => "8G5IYRA3",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_OVER_DUE,
                'memo' => '',
            ],
            [
                'record_id' => 80,
                'type' => VirtualProductType::TYPE_GENERAL_NON_NOTIFY_TICKET,
                'batch_code' => 'HX0GTLO6',
                'customer_id' => 1,
                'belong_to_product_id' => 10,
                'ticket_unique_content' => "HX0GTLO6",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_OVER_DUE,
                'memo' => '',
            ],
            [
                'record_id' => 81,
                'type' => VirtualProductType::TYPE_FAMILY_BONUS_PIN_TICKET,
                'batch_code' => 'ASMZE7ZC',
                'customer_id' => 1,
                'belong_to_product_id' => 1,
                'ticket_unique_content' => "ASMZE7ZC", //serial_number
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_OVER_DUE,
                'memo' => '',
            ],
            [
                'record_id' => 82,
                'type' => VirtualProductType::TYPE_YOXI_TICKET,
                'batch_code' => 'S1B5WVZK',
                'customer_id' => 1,
                'belong_to_product_id' => 2,
                'ticket_unique_content' => "S1B5WVZK",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_OVER_DUE,
                'memo' => '',
            ],
            [
                'record_id' => 83,
                'type' => VirtualProductType::TYPE_GENERAL_NON_NOTIFY_TICKET,
                'batch_code' => '4DKH061A',
                'customer_id' => 1,
                'belong_to_product_id' => 3,
                'ticket_unique_content' => "4DKH061A",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_OVER_DUE,
                'memo' => '',
            ],
            [
                'record_id' => 84,
                'type' => VirtualProductType::TYPE_GENERAL_NON_NOTIFY_TICKET,
                'batch_code' => '1AH3Z716',
                'customer_id' => 1,
                'belong_to_product_id' => 4,
                'ticket_unique_content' => "1AH3Z716",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_OVER_DUE,
                'memo' => '',
            ],
            [
                'record_id' => 85,
                'type' => VirtualProductType::TYPE_YOXI_TICKET,
                'batch_code' => 'WA8HW6RX',
                'customer_id' => 1,
                'belong_to_product_id' => 5,
                'ticket_unique_content' => "WA8HW6RX",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_OVER_DUE,
                'memo' => '',
            ],
            [
                'record_id' => 86,
                'type' => VirtualProductType::TYPE_GENERAL_NON_NOTIFY_TICKET,
                'batch_code' => 'CTE14RCZ',
                'customer_id' => 1,
                'belong_to_product_id' => 6,
                'ticket_unique_content' => "CTE14RCZ",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_OVER_DUE,
                'memo' => '',
            ],
            [
                'record_id' => 87,
                'type' => VirtualProductType::TYPE_FAMILY_BONUS_PIN_TICKET,
                'batch_code' => 'AMP8X4BH',
                'customer_id' => 1,
                'belong_to_product_id' => 7,
                'ticket_unique_content' => "AMP8X4BH", //serial_number
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_OVER_DUE,
                'memo' => '',
            ],
            [
                'record_id' => 88,
                'type' => VirtualProductType::TYPE_YOXI_TICKET,
                'batch_code' => '5B6G7FHY',
                'customer_id' => 1,
                'belong_to_product_id' => 8,
                'ticket_unique_content' => "5B6G7FHY",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_OVER_DUE,
                'memo' => '',
            ],
            [
                'record_id' => 89,
                'type' => VirtualProductType::TYPE_GENERAL_NON_NOTIFY_TICKET,
                'batch_code' => 'WV7XGWLH',
                'customer_id' => 1,
                'belong_to_product_id' => 9,
                'ticket_unique_content' => "WV7XGWLH",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_OVER_DUE,
                'memo' => '',
            ],
            [
                'record_id' => 90,
                'type' => VirtualProductType::TYPE_GENERAL_NON_NOTIFY_TICKET,
                'batch_code' => 'I9NV4B66',
                'customer_id' => 1,
                'belong_to_product_id' => 10,
                'ticket_unique_content' => "I9NV4B66",
                'use_start_time' => '2023/08/11',
                'use_end_time' => '2024/09/04',
                'status' => Status::STATUS_OVER_DUE,
                'memo' => '',
            ],
        ]
    ];

    const PRODUCT_MOCK_DATA = [
        1 => [
            'id' => 1,
            'name' => 'FamilyMart全家-中杯 熱拿鐵',
            'small_image' => 'https://integration-5ojmyuq-2ntakmlqwmx4i.ap-3.magentosite.cloud/media/.thumbswysiwyg/1.png',
            'specification' => '',
            'display_serial_number' => 1,
            'display_barcode' => 1,
            'barcode_type' => 1,
        ],
        2 => [
            'id' => 2,
            'name' => 'yoxi 優惠券',
            'small_image' => 'https://integration-5ojmyuq-2ntakmlqwmx4i.ap-3.magentosite.cloud/media/.thumbswysiwyg/2.png',
            'specification' => '規格說明規格說明規格說明',
            'display_serial_number' => 1,
        ],
        3 => [
            'id' => 3,
            'name' => 'iRent汽車時數券600分鐘',
            'small_image' => 'https://integration-5ojmyuq-2ntakmlqwmx4i.ap-3.magentosite.cloud/media/.thumbswysiwyg/3.png',
            'specification' => '',
            'display_serial_number' => 1,
            'exchange_url' => "https://www.google.com",
            'is_offline_operation'=> 1
        ],
        4 => [
            'id' => 4,
            'name' => '張學友 60＋ 巡迴演唱會台北站雙人門票',
            'small_image' => 'https://integration-5ojmyuq-2ntakmlqwmx4i.ap-3.magentosite.cloud/media/.thumbswysiwyg/4.png',
            'specification' => '',
            'display_serial_number' => 1,
        ],
        5 => [
            'id' => 5,
            'name' => 'yoxi 優惠券',
            'small_image' => 'https://integration-5ojmyuq-2ntakmlqwmx4i.ap-3.magentosite.cloud/media/.thumbswysiwyg/2.png',
            'display_serial_number' => 0
        ],
        6 => [
            'id' => 6,
            'name' => 'iRent汽車時數券600分鐘',
            'small_image' => 'https://integration-5ojmyuq-2ntakmlqwmx4i.ap-3.magentosite.cloud/media/.thumbswysiwyg/3.png',
            'specification' => '',
            'display_serial_number' => 1,
            'exchange_hint' => '兌換文字提示輸入文字15字內，如無輸入不顯示',
            'is_offline_operation' => 1
        ],
        7 => [
            'id' => 7,
            'name' => 'FamilyMart全家-中杯 熱拿鐵',
            'small_image' => 'https://integration-5ojmyuq-2ntakmlqwmx4i.ap-3.magentosite.cloud/media/.thumbswysiwyg/1.png',
            'specification' => '',
            'display_serial_number' => 1,
        ],
        8 => [
            'id' => 8,
            'name' => 'yoxi 優惠券',
            'small_image' => 'https://integration-5ojmyuq-2ntakmlqwmx4i.ap-3.magentosite.cloud/media/.thumbswysiwyg/2.png',
            'specification' => '',
            'display_serial_number' => 1,
            'is_offline_operation' => 0
        ],
        9 => [
            'id' => 9,
            'name' => 'iRent汽車時數券600分鐘',
            'small_image' => 'https://integration-5ojmyuq-2ntakmlqwmx4i.ap-3.magentosite.cloud/media/.thumbswysiwyg/3.png',
            'specification' => '',
            'display_serial_number' => 1,
        ],
        10 => [
            'id' => 10,
            'name' => '張學友 60＋ 巡迴演唱會台北站雙人門票',
            'small_image' => 'https://integration-5ojmyuq-2ntakmlqwmx4i.ap-3.magentosite.cloud/media/.thumbswysiwyg/4.png',
            'specification' => '',
            'display_serial_number' => 1,
        ],
        11 => [
            'id' => 11,
            'name' => '票劵名稱',
            'small_image' => 'https://integration-5ojmyuq-2ntakmlqwmx4i.ap-3.magentosite.cloud/media/.thumbswysiwyg/11.png',
            'specification' => '',
            'display_serial_number' => 1,
            'is_offline_operation' => 1
        ],
        12 => [
            'id' => 12,
            'name' => '票劵名稱',
            'small_image' => 'https://integration-5ojmyuq-2ntakmlqwmx4i.ap-3.magentosite.cloud/media/.thumbswysiwyg/12.png',
            'specification' => '',
            'display_serial_number' => 1,
            'is_offline_operation' => 0
        ],
        13177 => [
            'id' => 6,
            'name' => 'iRent汽車時數券600分鐘',
            'small_image' => 'https://integration-5ojmyuq-2ntakmlqwmx4i.ap-3.magentosite.cloud/media/.thumbswysiwyg/3.png',
            'specification' => '',
            'display_serial_number' => 1,
            'exchange_hint' => '兌換文字提示輸入文字15字內，如無輸入不顯示',
            'is_offline_operation' => true
        ],
        13176 => [
            'id' => 6,
            'name' => 'iRent汽車時數券600分鐘',
            'small_image' => 'https://integration-5ojmyuq-2ntakmlqwmx4i.ap-3.magentosite.cloud/media/.thumbswysiwyg/3.png',
            'specification' => '',
            'display_serial_number' => 1,
            'exchange_hint' => '兌換文字提示輸入文字15字內，如無輸入不顯示',
            'is_offline_operation' => false
        ]
    ];
}
