<?php
/**
 * @var \Webkul\Marketplace\Block\Order\View $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Branch8\Sales\Helper\Config $b8salesConfigHelper
 */
$b8salesConfigHelper = $this->helper(\Branch8\Sales\Helper\Config::class);
?>
<table class="data-table orders wk-mp-list_table" id="my-orders-table">
    <col width="1" />
    <col width="1" />
    <tbody>
    <?php
    foreach ($block->getChildNames() as $key => $blockName) {
        if ($blockName != 'marketplace_order_items') { ?>
            <?= /* @noEscape */ $block->getChildHtml($blockName, false); ?>
            <?php
        }
    } ?>

    <tr>
        <td>
            <select name="carrier" class="required-entry carrier select" id="wk-mp-tracking-title">
                <option value=""><?= $escaper->escapeHtml(__('-- Please Select --'))?></option>
                <?php foreach ($b8salesConfigHelper->getLogisticsCompanies() as $name => $url):?>
                    <option value="<?= $escaper->escapeHtml($name) ?>" data-url="<?= $escaper->escapeHtml($url) ?>">
                        <?= $escaper->escapeHtml($name) ?>
                    </option>
                <?php endforeach; ?>
            </select>
            <input class="input-text" type="hidden" name="logistics_company_url" id="wk-mp-tracking-lcurl"/>
        </td>
    </tr>
    <tr id="logistics-provider-row" style="display:none;">
        <td>
            <input class="required-entry input-text" type="text" name="logistics_provider_name" id="wk-mp-logistics_provider_name"
                   placeholder="<?= /* @noEscape */ __("Logistics Provider's Name") ?>"/>
        </td>
    </tr>
    <tr>
        <td>
            <input class="required-entry input-text" type="text" name="tracking_id"
                   placeholder="<?= /* @noEscape */ __('Tracking Number') ?>"/>
        </td>
    </tr>
    </tbody>
</table>
<script type="text/javascript">
    require([
        'jquery'
    ], function($) {
        $(document).ready(function() {
            $('#wk-mp-tracking-title').on('change', function() {
                var selectedUrl = $(this).find(':selected').data('url');
                $('#wk-mp-tracking-lcurl').val(selectedUrl);
                if ($(this).val() === '其他：自行填寫名稱') {
                    $('#logistics-provider-row').show();
                    $('#logistics-provider-row td').css({
                        'background-color': '#f7f3eb',
                        'border-width': '0',
                        'padding': '5px 7px'
                    });
                } else {
                    $('#logistics-provider-row').hide();
                }
            });
        });
    });
</script>
