<?php

/** @var $block \Webkul\Marketplace\Block\Product\Create */

$viewModel = $block->getViewModel();
?>
<div id="general-ticket-block">
    <h3 class="title">
        <?= /* @noEscape */ $escaper->escapeHtml(__('General notify ticket record overview')); ?>
    </h3>
    <div id="general-ticket-block-loader" class="admin__data-grid-outer-wrap" style="display:block;">
        <div class="admin__data-grid-loading-mask">
            <div class="spinner">
                <span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span>
            </div>
        </div>
    </div>
    <div id="general-ticket-block-wrapper" style="display:none;">
        <?= $block->getChildHtml(); ?>
    </div>
</div>
<?php
$formData = [
    'generalTicket' => $viewModel->getJsonHelper()->jsonEncode([])
];
$serializedFormData = $viewModel->getJsonHelper()->jsonEncode($formData);
?>

<script type="text/x-magento-init">
    {
        "#general-ticket-block": {
            "generalTicket": <?= /* @noEscape */ $serializedFormData; ?>
    }
}
</script>


