<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpBundleProduct
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<?php
/**
 * @var $block \Branch8\MarketplaceStaging\Block\Product\Edit\Bundle\Catalog\Selection
 */
?>
<script id="staging-bundle-option-selection-box-template" type="text/x-magento-template">
    <table class="admin__control-table">
        <thead>
            <tr class="headings">
                <th class="col-draggable"></th>
                <th class="col-default"><?= $block->escapeHtml(__('Default')); ?></th>
                <th class="col-name"><?= $block->escapeHtml(__('Name')); ?></th>
                <th class="col-sku"><?= $block->escapeHtml(__('SKU')); ?></th>
            <?php if ($block->getCanReadPrice() !== false): ?>
                <th class="col-price price-type-box"><?= $block->escapeHtml(__('Price')) ?></th>
                <th class="col-price price-type-box"><?= $block->escapeHtml(__('Price Type')) ?></th>
            <?php endif; ?>
                <th class="col-qty"><?= $block->escapeHtml(__('Default Quantity')); ?></th>
                <th class="col-uqty qty-box"><?= $block->escapeHtml(__('User Defined')); ?></th>
                <th class="col-order type-order" style="display:none"><?= $block->escapeHtml(__('Position')); ?></th>
                <th class="col-actions"></th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</script>
<script id="staging-bundle-option-selection-row-template" type="text/x-magento-template">
<td class="col-draggable">
    <span data-role="draggable-handle" class="draggable-handle"></span>
    <input type="hidden" id="staging_<?= $block->escapeHtml($block->getFieldId()) ?>_id<%- data.index %>"
        name="bundle_options[bundle_options][<%- data.parentIndex %>][<?= $block->escapeHtml($block->getFieldName()) ?>][<%- data.index %>][selection_id]"
            value="<%- data.selection_id %>"/>
    <input type="hidden"
        name="bundle_options[bundle_options][<%- data.parentIndex %>][<?= $block->escapeHtml($block->getFieldName()) ?>][<%- data.index %>][option_id]"
            value="<%- data.option_id %>"/>
    <input type="hidden" class="product"
        name="bundle_options[bundle_options][<%- data.parentIndex %>][<?= $block->escapeHtml($block->getFieldName()) ?>][<%- data.index %>][product_id]"
            value="<%- data.product_id %>"/>
    <input type="hidden"
        name="bundle_options[bundle_options][<%- data.parentIndex %>][<?= $block->escapeHtml($block->getFieldName()) ?>][<%- data.index %>][delete]"
            value="" class="delete"/>
    <input type="hidden"
        name="bundle_options[bundle_options][<%- data.parentIndex %>][<?= $block->escapeHtml($block->getFieldName()) ?>][<%- data.index %>][name]"
            value="<%- data.name %>" class="delete"/>
    <input type="hidden"
        name="bundle_options[bundle_options][<%- data.parentIndex %>][<?= $block->escapeHtml($block->getFieldName()) ?>][<%- data.index %>][sku]"
            value="<%- data.sku %>" class="delete"/>
    <input type="hidden"
        name="bundle_options[bundle_options][<%- data.parentIndex %>][<?= $block->escapeHtml($block->getFieldName()) ?>][<%- data.index %>][price]"
            value="<%- data.price %>" class="delete"/>
</td>
<td class="col-default">
    <input type="<%- data.option_type %>" class="default"
        name="bundle_options[bundle_options][<%- data.parentIndex %>][<?= $block->escapeHtml($block->getFieldName()) ?>][<%- data.index %>][is_default]"
        value="1" <%- data.checked %> />
</td>
    <td class="col-name"><%- data.name %></td>
    <td class="col-sku"><%- data.sku %></td>
<?php if ($block->getCanReadPrice() !== false): ?>
<td class="col-price price-type-box">
<input id="staging_<?= $block->escapeHtml($block->getFieldId()) ?>_<%- data.index %>_price_value"
class="input-text required-entry validate-zero-or-greater" type="text"
name="bundle_options[bundle_options][<%- data.parentIndex %>][<?= $block->escapeHtml($block->getFieldName()) ?>][<%- data.index %>][selection_price_value]"
    value="<%- data.selection_price_value %>"
    <?php if ($block->getCanEditPrice() === false): ?>
    disabled="disabled"
    <?php endif; ?>/>
</td>
<td class="col-price price-type-box">
    <?= $block->getPriceTypeSelectHtml() ?>
    <div><?= $block->getCheckboxScopeHtml() ?></div>
</td>
<?php else: ?>
<input type="hidden" id="staging_<?= $block->escapeHtml($block->getFieldId()); ?>_<%- data.index %>_price_value"
name="bundle_options[bundle_options][<%- data.parentIndex %>][<?= $block->escapeHtml($block->getFieldName()) ?>][<%- data.index %>][selection_price_value]"
    value="0" />
<input type="hidden"
    id="staging_<?= $block->escapeHtml($block->getFieldId()); ?>_<%- data.parentIndex %>_<%- data.index %>_price_type"
name="bundle_options[bundle_options][<%- data.parentIndex %>][<?= $block->escapeHtml($block->getFieldName()) ?>][<%- data.index %>][selection_price_type]"
    value="0" />
    <?php if ($block->isUsedWebsitePrice()): ?>
<input type="hidden" id="staging_<?= $block->escapeHtml($block->getFieldId()); ?>_<%- data.index %>_price_scope"
name="bundle_options[bundle_options][<%- data.parentIndex %>][<?= $block->escapeHtml($block->getFieldName()) ?>][<%- data.index %>][default_price_scope]"
    value="1" />
<?php endif; ?>
<?php endif; ?>
<td class="col-qty">
    <input class="input-text required-entry validate-greater-zero-based-on-option validate-zero-or-greater"
        type="text"
    name="bundle_options[bundle_options][<%- data.parentIndex %>][<?= $block->escapeHtml($block->getFieldName()) ?>][<%- data.index %>][selection_qty]"
        value="<%- data.selection_qty %>" />
</td>
<td class="col-uqty qty-box">
    <input type="checkbox" class="is-user-defined-qty" checked="checked" />
    <span style="display:none"><?=  $block->getQtyTypeSelectHtml() ?></span>
</td>
<td class="col-order type-order" style="display:none">
    <input class="input-text required-entry validate-zero-or-greater" type="text"
        name="bundle_options[bundle_options][<%- data.parentIndex %>][<?= $block->escapeHtml($block->getFieldName()) ?>][<%- data.index %>][position]"
            value="<%- data.position %>" />
</td>
<td class="col-actions">
    <span title="Delete Row">
        <div class="actions">
            <button type="button" title="<?= $block->escapeHtml(__('Delete Option')); ?>"
                class="action-delete bundle-delete-options"
                id="<?= $block->escapeHtml('staging_selection_delete_button_') ?>
                <%- data.index %>" >
                <span><?= $block->escapeHtml(__('Delete Option')); ?></span>
            </button>
        </div>
    </span>
</td>
</script>


<?php
$optionElements = [
'idLabel' => $block->getFieldId(),
'scopePrice' => (int)$block->isUsedWebsitePrice(),
'selectionSearchUrl' => $block->getSelectionSearchUrl()

];
$serializedData = $block->jsonEncodeData($optionElements);
?>

<script type="text/x-magento-init">
{
"*":{
        "Branch8_MarketplaceStaging/js/bundle/bundle-product":<?= /* @noEscape */ $serializedData; ?>
    }
}
</script>

