<?php
/**
 *
 * @category    Branch8
 * @package     Branch8_Blog
 */

use Branch8\Blog\Block\Post\View;
use Magento\Framework\Escaper;

/** @var View $block */
/** @var Escaper $escaper */
$helper       = $block->getBlogHelper();
$_post        = $block->getPost();
$author       = $helper->getAuthorByPost($_post);
$authorName   = $author !== null ? $author->getName() : '';
$modifier     = $helper->getAuthorByPost($_post, true);
$modifierName = $modifier !== null ? $modifier->getName() : '';
?>
<?php if ($authorName && $helper->showAuthorInfo()) : ?>
    |
    <span><i class="fa fa-user">&nbsp;</i>
        <?= $escaper->escapeHtml(__('By:')) ?> <a class="mp-info" href="<?= $escaper->escapeHtml($author->getUrl()) ?>"><?= $escaper->escapeHtml($authorName) ?></a></span>
    <?php if ($authorName != $modifierName && $modifierName) : ?>
        |
        <span><i class="fa fa-edit">&nbsp;</i>
            <?= $escaper->escapeHtml(__('Modify By:')) ?>
            <a class="mp-info" href="<?= $escaper->escapeHtml($author->getUrl()) ?>"><?= $escaper->escapeHtml($authorName) ?></a>
            <?= $escaper->escapeHtml(__(' at ')) ?><?= $block->getDateFormat($_post->getUpdatedAt()) ?></span>
    <?php endif; ?>
<?php endif; ?>
