<?php
/**
 *
 * @category    Branch8
 * @package     Branch8_Blog
 */

use Branch8\Blog\Block\Post\View;
use Branch8\Blog\Helper\Image;
use Branch8\Blog\Model\Config\Source\Comments\Type;
use Magento\Framework\Escaper;

/** @var View $block */
/** @var Escaper $escaper */
$_post = $block->getPost();
?>
<?php if ($categoryHtml = $block->getPostCategoryHtml($_post)) : ?>
    |
    <span><i class="fa fa-folder-open-o">&nbsp;</i>
        <?= /* @noEscape */ (__('Categories: %1', $categoryHtml)); ?>
    </span>
<?php endif; ?>
