<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div data-bind="scope: 'messages'">
    <!-- ko if: cookieMessagesObservable() && cookieMessagesObservable().length > 0 -->
    <!-- ko ifnot: hasMessageObservable -->
        <div aria-atomic="true" role="alert" class="cookie-messages messages" data-bind="foreach: {
            data: cookieMessagesObservable(), as: 'message'
        }">
            <div data-bind="attr: {
                class: 'message-' + message.type + ' ' + message.type + ' message',
                'data-ui-id': 'message-' + message.type
            }">
                <div data-bind="html: $parent.prepareMessageForHtml(message.text), afterRender: $parent.toggleMessages($parent)"></div>
            </div>
        </div>
    <!-- /ko -->
    <!-- /ko -->
    <div aria-atomic="true" role="alert" class="core-messages messages" data-bind="foreach: {
        data: messages().messages, as: 'message'
    }, afterRender: purgeMessages">
        <div data-bind="attr: {
            class: 'message-' + message.type + ' ' + message.type + ' message',
            'data-ui-id': 'message-' + message.type
        }">
            <div data-bind="html: $parent.prepareMessageForHtml(message.text), afterRender: $parent.toggleMessages($parent)"></div>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                        "messages": {
                            "component": "Magento_Theme/js/view/messages"
                        }
                    }
                }
            }
    }
</script>
