<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Branch8\MarketplaceStaging\Block\Update\Preview */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>

<div data-role="share-modal" id="share-modal">
    <p>Please press CTRL+C for copying URL into buffer to share this Preview.</p>
    <input class="admin__legend" name="url" title="Preview Url" type="text" data-role="share-modal-input">
</div>
<?= /* @noEscape */
$secureRenderer->renderTag(
    'style',
    [],
    '#share-modal { display: none; }',
    true
); ?>
<div class="staging-preview-content" data-role="iframe-container">
    <div class="staging-preview-content-dynamic">
        <iframe data-role="preview-iframe"
                frameborder="0"
                src="<?= $block->escapeUrl($block->getPreviewFrontendUrl()) ?>">
        </iframe>
    </div>
</div>
