<?php
declare(strict_types=1);

namespace Branch8\HelpDesk\Model\ResourceModel\Ticket\Grid;

use Branch8\HelpDesk\Model\ResourceModel\Ticket as TicketResource;
use Magento\Framework\Api\Search\AggregationInterface;
use Magento\Framework\Api\Search\SearchResultInterface;
use Branch8\HelpDesk\Model\ResourceModel\Ticket\Collection as BaseCollection;
use Magento\Framework\App\ObjectManager;
use Magento\Framework\Data\Collection\Db\FetchStrategyInterface;
use Magento\Framework\Data\Collection\EntityFactoryInterface;
use Magento\Framework\DB\Adapter\AdapterInterface;
use Magento\Framework\Event\ManagerInterface;
use Magento\Framework\Model\ResourceModel\Db\AbstractDb;
use Magento\Framework\Stdlib\DateTime\TimezoneInterface;
use Magento\Framework\View\Element\UiComponent\DataProvider\Document;
use Psr\Log\LoggerInterface;
use Magento\Framework\DB\Sql\Expression as SqlExpression;

/**
 *Ticket Grid Collection
 */
class Collection extends BaseCollection implements SearchResultInterface
{
    /**
     * @var AggregationInterface
     */
    protected $aggregations;
    /**
     * @var TimezoneInterface
     */
    private $timeZone;

    /**
     * @param EntityFactoryInterface $entityFactory
     * @param LoggerInterface $logger
     * @param FetchStrategyInterface $fetchStrategy
     * @param ManagerInterface $eventManager
     * @param string $mainTable
     * @param string $resourceModel
     * @param string $model
     * @param \Magento\Customer\Model\Session\Proxy|null $customerSession
     * @param AdapterInterface|null $connection
     * @param AbstractDb|null $resource
     */
    public function __construct(
        \Magento\Framework\Data\Collection\EntityFactoryInterface    $entityFactory,
        \Psr\Log\LoggerInterface                                     $logger,
        \Magento\Framework\Data\Collection\Db\FetchStrategyInterface $fetchStrategy,
        \Magento\Framework\Event\ManagerInterface                    $eventManager,
        string                                                       $mainTable = 'branch8_helpdesk_ticket',
        string                                                       $resourceModel = TicketResource::class,
        string                                                       $model = Document::class,
        \Magento\Customer\Model\Session\Proxy                        $customerSession = null,
        \Magento\Framework\DB\Adapter\AdapterInterface               $connection = null,
        \Magento\Framework\Model\ResourceModel\Db\AbstractDb         $resource = null,
        TimezoneInterface                                            $timeZone = null
    )
    {
        parent::__construct(
            $entityFactory,
            $logger,
            $fetchStrategy,
            $eventManager,
            $connection,
            $resource
        );
        $this->_init($model, $resourceModel);
        $this->setMainTable($mainTable);
        $this->timeZone = $timeZone ?: ObjectManager::getInstance()->get(TimezoneInterface::class);
    }

    public function _initSelect()
    {
        parent::_initSelect(); // TODO: Change the autogenerated stub

        $this->getSelect()->joinLeft(['pr' => 'sales_parent_order_detail'], 'pr.parent_id = main_table.parent_order', []);
        $this->getSelect()->columns(
            [
            'is_gift' => new SqlExpression(
                'If(pr.is_gift_order is NULL, "0", pr.is_gift_order)'
            )
            ]
        );
    }

    /**
     * @inheritDoc
     */
    public function addFieldToFilter($field, $condition = null)
    {
        if ($field === 'created_at' || $field === 'updated_at') {
            if (is_array($condition)) {
                foreach ($condition as $key => $value) {
                    $condition[$key] = $this->timeZone->convertConfigTimeToUtc($value);
                }
            }
        }
        if($field == 'is_gift' && isset($condition['eq']) && $condition['eq'] == 0){
            $field = ['is_gift_order', 'is_gift_order'];
            $condition = [['eq' => 0],['null' => true]];
        }
        if($field == 'is_gift' && isset($condition['eq']) && $condition['eq'] == 1){
            $field = 'is_gift_order';

        }
        $helpDeskFields = [
            'status',
            'customer_name',
            'customer_email',
            'created_at'
        ];
        if (in_array($field, $helpDeskFields)) {
            $field = 'main_table' . '.' . $field;
        }
        return parent::addFieldToFilter($field, $condition);
    }

    /**
     * @inheritdoc
     */
    public function getAggregations()
    {
        return $this->aggregations;
    }

    /**
     * @inheritdoc
     */
    public function setAggregations($aggregations)
    {
        $this->aggregations = $aggregations;
    }

    /**
     * @return null
     */
    public function getSearchCriteria()
    {
        return null;
    }

    /**
     * @param \Magento\Framework\Api\SearchCriteriaInterface|null $searchCriteria
     * @return $this|CustomerTicketCollection
     */
    public function setSearchCriteria(\Magento\Framework\Api\SearchCriteriaInterface $searchCriteria = null)
    {
        return $this;
    }

    /**
     * @return int
     */
    public function getTotalCount()
    {
        return $this->getSize();
    }

    /**
     * @param $totalCount
     * @return $this|CustomerTicketCollection
     */
    public function setTotalCount($totalCount)
    {
        return $this;
    }

    /**
     * @param array|null $items
     * @return $this|CustomerTicketCollection
     */
    public function setItems(array $items = null)
    {
        return $this;
    }
}
