<?php
declare(strict_types=1);

namespace Branch8\HelpDesk\Model\ResourceModel\Ticket\Grid;

use Magento\Framework\Api\Search\SearchResultInterface;
use Branch8\HelpDesk\Model\ResourceModel\Ticket as TicketResource;
use Branch8\HelpDesk\Model\ResourceModel\Ticket\Collection as BaseCollection;
use Magento\Framework\App\ObjectManager;
use Magento\Framework\View\Element\UiComponent\DataProvider\Document;

/**
 *
 */
class CustomerTicketCollection extends BaseCollection implements SearchResultInterface
{
    /**
     * @var AggregationInterface
     */
    protected $aggregations;
    /**
     * @var \Magento\Customer\Model\Session|\Magento\Customer\Model\Session\Proxy|mixed
     */
    private $customerSession;

    /**
     * @param \Magento\Framework\Data\Collection\EntityFactoryInterface $entityFactory
     * @param \Psr\Log\LoggerInterface $logger
     * @param \Magento\Framework\Data\Collection\Db\FetchStrategyInterface $fetchStrategy
     * @param \Magento\Framework\Event\ManagerInterface $eventManager
     * @param \Magento\Customer\Model\Session $customerSession
     * @param string $mainTable
     * @param string $resourceModel
     * @param string $model
     * @param \Magento\Framework\DB\Adapter\AdapterInterface|null $connection
     * @param \Magento\Framework\Model\ResourceModel\Db\AbstractDb|null $resource
     */
    public function __construct(
        \Magento\Framework\Data\Collection\EntityFactoryInterface    $entityFactory,
        \Psr\Log\LoggerInterface                                     $logger,
        \Magento\Framework\Data\Collection\Db\FetchStrategyInterface $fetchStrategy,
        \Magento\Framework\Event\ManagerInterface                    $eventManager,
        string                                                       $mainTable = 'branch8_helpdesk_ticket',
        string                                                       $resourceModel = TicketResource::class,
        string                                                       $model = Document::class,
        \Magento\Customer\Model\Session\Proxy                        $customerSession = null,
        \Magento\Framework\DB\Adapter\AdapterInterface               $connection = null,
        \Magento\Framework\Model\ResourceModel\Db\AbstractDb         $resource = null
    )
    {
        $this->customerSession = $customerSession ?: ObjectManager::getInstance()->get(
            \Magento\Customer\Model\Session\Proxy::class
        );
        parent::__construct(
            $entityFactory,
            $logger,
            $fetchStrategy,
            $eventManager,
            $connection,
            $resource
        );
        $this->_init($model, $resourceModel);
        $this->setMainTable($mainTable);
    }

    /**
     * @return void
     */
    public function _initSelect()
    {
        parent::_initSelect(); // TODO: Change the autogenerated stub
        $this->addFilter('customer_id', (int)$this->customerSession->getCustomerId());
        $this->getSelect()->reset('columns')->columns([
            'code',
            'title',
            'ticket_id',
            'status',
            'frontend_status',
            'priority'
        ]);
    }

    /**
     * etAggregations
     * @inheritdoc
     */
    public function getAggregations()
    {
        return $this->aggregations;
    }

    /**
     * SetAggregations
     * @inheritdoc
     */
    public function setAggregations($aggregations)
    {
        $this->aggregations = $aggregations;
    }

    /**
     * @return null
     */
    public function getSearchCriteria()
    {
        return null;
    }

    /**
     * @param \Magento\Framework\Api\SearchCriteriaInterface|null $searchCriteria
     * @return $this|CustomerTicketCollection
     */
    public function setSearchCriteria(\Magento\Framework\Api\SearchCriteriaInterface $searchCriteria = null)
    {
        return $this;
    }

    /**
     * @return int
     */
    public function getTotalCount()
    {
        if (!$this->customerSession->getCustomerId()) {
            return 0;
        }
        return $this->getSize();
    }

    /**
     * @param $totalCount
     * @return $this|CustomerTicketCollection
     */
    public function setTotalCount($totalCount)
    {
        return $this;
    }

    /**
     * @param array|null $items
     * @return $this|CustomerTicketCollection
     */
    public function setItems(array $items = null)
    {
        return $this;
    }
}
