<?php
/**
 * @var Branch8\Quickview\Block\Product\View\PaymentMethod $block
 */
?>
<div class="pdp_payment_method">
        <div><?php echo __('Payment method');?></div>
        <div class="payment-methods">
            <div class="method">
                <div class="payment_method_name"><?= __('和泰PAY') ?></div>
                <a href="<?= $block->getUrl('hotaipay/creditcard/listaction') ?>"><?= __('前往綁定和泰Pay') ?></a>
            </div>
        </div>
    </div>
