<?php $jsonLoader = $this->getViewFileUrl('images/animation-order-success.json');
 ?>
<div class="checkout-success checkout-order-confirmation">
    <div class="success-messages order-confirmation-messages">
        <div class="order-confirmation-icon">
                <dotlottie-player class="player" src="<?= $jsonLoader ?>" background="transparent" speed="1" direction="1"
                playMode="normal" loop autoplay></dotlottie-player>
        </div>
        <h2 class="page-title"><?= $block->escapeHtml(__('Order has been established')); ?></h2>
        <p class="hidden"><?= $escaper->escapeHtml(__('Your order number is:')) ?>
            <a href="#"
                class="order-number">
                <strong>
                    00000591
                </strong>
            </a>
        </p>
        <p class="hidden">
            <?= $escaper->escapeHtml(__('Your order # is:')) ?>
            <span>
            00000591
            </span>
        </p>
        <div class="note"><?= $escaper->escapeHtml(__('Please check if your network connection is stable or if there is an issue with the payment method you have selected.')) ?></div>
        <p><?= $escaper->escapeHtml(__('If the problem is not due to the above reasons, please click the button below to try again or call customer service, and we will assist you with the issue.')) ?></p>
        <div class="actions-toolbar">
            <a class="action primary continue btn-icon-right btn-icon-arrow-right" href="<?= /* @noEscape */
                $block->getUrl() ?>">
                    <span><?= $escaper->escapeHtml(__('Continue Shopping')) ?></span>
                </a>
        </div>
    </div>

    <div class="block block-products-list block-cart-items">
        <style>
            .products-grid .product-item-inner{
                margin:unset;
            }
        </style>
        <div class="block-title">
            <h6>別讓好東西等太久，快點帶回家吧！</h6>
        </div>
        <div class="block-content">
            <div class="grid products-grid grid products-grid products-grid-carousel">
                <div class="items product-items slick-carousel">
                    <div class="item product product-item">
                        <div class="product-item-info item" data-container="product-grid">
                                                                                    <a href="http://magento-hotai.com/blue123-1.html" class="product-item-photo" tabindex="0">
                                <span class="product-image-container">
                                    <span class="product-image-wrapper" style="padding-bottom: 100%">
                                        <img class="product-image-photo" width="240" height="240" src="http://magento-hotai.com/media/catalog/product/i/m/img_13__10.png" alt="女装时尚 Yellow">
                                    </span>
                                </span>
                            </a>
                            <div class="product details product-item-details">
                                                                <strong class="product name product-item-name">
                                    <a class="product-item-link" href="http://magento-hotai.com/blue123-1.html" tabindex="0">
                                        女装时尚 Yellow                                    </a>
                                </strong>
                            </div>
                        </div>
                    </div>   
                    <div class="item product product-item">
                        <div class="product-item-info item" data-container="product-grid">
                                                                                    <a href="http://magento-hotai.com/121212-1.html" class="product-item-photo" tabindex="0">
                                <span class="product-image-container">
                                    <span class="product-image-wrapper" style="padding-bottom: 100%">
                                        <img class="product-image-photo" width="240" height="240" src="http://magento-hotai.com/media/catalog/product/i/m/img_1.jpg" alt="美味的即食火鍋">
                                    </span>
                                </span>
                            </a>
                            <div class="product details product-item-details">
                                                                <strong class="product name product-item-name">
                                    <a class="product-item-link" href="http://magento-hotai.com/121212-1.html" tabindex="0">
                                        美味的即食火鍋                                    </a>
                                </strong>
                            </div>
                        </div>
                    </div>   
                    <div class="item product product-item">
                        <div class="product-item-info item" data-container="product-grid">
                                                                                    <a href="http://magento-hotai.com/121212-1.html" class="product-item-photo" tabindex="0">
                                <span class="product-image-container">
                                    <span class="product-image-wrapper" style="padding-bottom: 100%">
                                        <img class="product-image-photo" width="240" height="240" src="http://magento-hotai.com/media/catalog/product/i/m/img_1.jpg" alt="美味的即食火鍋">
                                    </span>
                                </span>
                            </a>
                            <div class="product details product-item-details">
                                                                <strong class="product name product-item-name">
                                    <a class="product-item-link" href="http://magento-hotai.com/121212-1.html" tabindex="0">
                                        美味的即食火鍋                                    </a>
                                </strong>
                            </div>
                        </div>
                    </div>
                    <div class="item product product-item">
                        <div class="product-item-info item" data-container="product-grid">
                                                                                    <a href="http://magento-hotai.com/121212-1.html" class="product-item-photo" tabindex="0">
                                <span class="product-image-container">
                                    <span class="product-image-wrapper" style="padding-bottom: 100%">
                                        <img class="product-image-photo" width="240" height="240" src="http://magento-hotai.com/media/catalog/product/i/m/img_1.jpg" alt="美味的即食火鍋">
                                    </span>
                                </span>
                            </a>
                            <div class="product details product-item-details">
                                                                <strong class="product name product-item-name">
                                    <a class="product-item-link" href="http://magento-hotai.com/121212-1.html" tabindex="0">
                                        美味的即食火鍋                                    </a>
                                </strong>
                            </div>
                        </div>
                    </div>
                    <div class="item product product-item">
                        <div class="product-item-info item" data-container="product-grid">
                                                                                    <a href="http://magento-hotai.com/121212-1.html" class="product-item-photo" tabindex="0">
                                <span class="product-image-container">
                                    <span class="product-image-wrapper" style="padding-bottom: 100%">
                                        <img class="product-image-photo" width="240" height="240" src="http://magento-hotai.com/media/catalog/product/i/m/img_1.jpg" alt="美味的即食火鍋">
                                    </span>
                                </span>
                            </a>
                            <div class="product details product-item-details">
                                                                <strong class="product name product-item-name">
                                    <a class="product-item-link" href="http://magento-hotai.com/121212-1.html" tabindex="0">
                                        美味的即食火鍋                                    </a>
                                </strong>
                            </div>
                        </div>
                    </div> 
                    <div class="item product product-item">
                        <div class="product-item-info item" data-container="product-grid">
                                                                                    <a href="http://magento-hotai.com/121212-1.html" class="product-item-photo" tabindex="0">
                                <span class="product-image-container">
                                    <span class="product-image-wrapper" style="padding-bottom: 100%">
                                        <img class="product-image-photo" width="240" height="240" src="http://magento-hotai.com/media/catalog/product/i/m/img_1.jpg" alt="美味的即食火鍋">
                                    </span>
                                </span>
                            </a>
                            <div class="product details product-item-details">
                                                                <strong class="product name product-item-name">
                                    <a class="product-item-link" href="http://magento-hotai.com/121212-1.html" tabindex="0">
                                        美味的即食火鍋                                    </a>
                                </strong>
                            </div>
                        </div>
                    </div> 
                    <div class="item product product-item">
                        <div class="product-item-info item" data-container="product-grid">
                                                                                    <a href="http://magento-hotai.com/121212-1.html" class="product-item-photo" tabindex="0">
                                <span class="product-image-container">
                                    <span class="product-image-wrapper" style="padding-bottom: 100%">
                                        <img class="product-image-photo" width="240" height="240" src="http://magento-hotai.com/media/catalog/product/i/m/img_1.jpg" alt="美味的即食火鍋">
                                    </span>
                                </span>
                            </a>
                            <div class="product details product-item-details">
                                                                <strong class="product name product-item-name">
                                    <a class="product-item-link" href="http://magento-hotai.com/121212-1.html" tabindex="0">
                                        美味的即食火鍋                                    </a>
                                </strong>
                            </div>
                        </div>
                    </div> 
                    <div class="item product product-item">
                        <div class="product-item-info item" data-container="product-grid">
                                                                                    <a href="http://magento-hotai.com/121212-1.html" class="product-item-photo" tabindex="0">
                                <span class="product-image-container">
                                    <span class="product-image-wrapper" style="padding-bottom: 100%">
                                        <img class="product-image-photo" width="240" height="240" src="http://magento-hotai.com/media/catalog/product/i/m/img_1.jpg" alt="美味的即食火鍋">
                                    </span>
                                </span>
                            </a>
                            <div class="product details product-item-details">
                                                                <strong class="product name product-item-name">
                                    <a class="product-item-link" href="http://magento-hotai.com/121212-1.html" tabindex="0">
                                        美味的即食火鍋                                    </a>
                                </strong>
                            </div>
                        </div>
                    </div> 
                    <div class="item product product-item">
                        <div class="product-item-info item" data-container="product-grid">
                                                                                    <a href="http://magento-hotai.com/121212-1.html" class="product-item-photo" tabindex="0">
                                <span class="product-image-container">
                                    <span class="product-image-wrapper" style="padding-bottom: 100%">
                                        <img class="product-image-photo" width="240" height="240" src="http://magento-hotai.com/media/catalog/product/i/m/img_1.jpg" alt="美味的即食火鍋">
                                    </span>
                                </span>
                            </a>
                            <div class="product details product-item-details">
                                                                <strong class="product name product-item-name">
                                    <a class="product-item-link" href="http://magento-hotai.com/121212-1.html" tabindex="0">
                                        美味的即食火鍋                                    </a>
                                </strong>
                            </div>
                        </div>
                    </div>   
                </div>
            </div>
            <div class="actions-toolbar">
                <a class="action secondary" href="http://magento-hotai.com/checkout/cart/">
                    <span>返回購物車</span>
                </a>
            </div>
        </div>
            <script>
            require(['jquery', 'slickSlider'], function($) {
                $(".products-grid-carousel .product-items").slickSlider({
                    template: 'slick6Products'
                });
            });
        </script>
    </div>
    <div class="order-details-wrapper">
    <div class="block block-order-details">
        <!-- Order Header -->
        <div class="block-title">
            <strong>訂單資訊</strong>
            <span>No.000000662</span>
        </div>
        <div class="block-content">
            <div class="order-details-info">
                <div class="order-details-left">
                    <div class="order-details-row">
                        <strong>購買人</strong> glenn123                     </div>
                    <div class="order-details-row">
                        <strong>商城ID</strong> b16cba76-256c-45d1-aa23-ec5cf3d57445                    </div>
                    <div class="order-details-row">
                        <strong>支付方式</strong> 
                        <dl class="payment-method checkmemo">
    <dt class="title">Check / Money order</dt>
                        </dl>
                    </div>
                    <div class="order-details-row">
                        <strong>付款狀態</strong> pending                    </div>
                    <div class="order-details-row">
                        <strong>訂單成立時間</strong> 2024年9月8日                    </div>
                </div>

                <!-- Order Totals -->
                <div class="order-details-right">
                    <div class="order-details-row">
                        <strong>商品總額</strong> <span class="price">$3,200.00</span>                    </div>
                    <div class="order-details-row">
                        <strong>點數折抵</strong> <span class="price">$0.00</span>                    </div>
                    <div class="order-details-row">
                        <strong>運費</strong> <span class="price">$80.00</span>                    </div>
                    <div class="order-details-row">
                        <strong>實付金額</strong> <span class="price">$3,280.00</span>                    </div>
                    <div class="order-details-row">
                        <strong>訂單備註</strong>
                        <div class="order-note">
                            訂單備註訂單備註訂單備註訂單備註訂單備註訂單備註訂單備註訂單備註訂單備註                        </div>
                    </div>
                </div>
            </div>

            <!-- Action buttons -->
            <div class="order-actions">
                <a href="http://magento-hotai.com/sales/parentOrder/printPdf/id/575/" class="action secondary action-small">下載PDF</a>
                <a href="http://magento-hotai.com/sales/parentOrder/view/id/575/" class="action action-small primary">查詢訂單</a>
            </div>
        </div>
    </div>
    <div class="block block-order-shipping-info">
        <div class="block-title">
            <strong>收件人資訊</strong>
        </div>
        <div class="block-content">
            <div class="order-details-info">
                <div class="order-details-left">
                    <div class="order-details-row">
                        <strong>姓名</strong> glenn123                     </div>
                    <div class="order-details-row">
                        <strong>手機號碼</strong> 0987687217                    </div>
                </div>
                <div class="order-details-right">
                    <div class="order-details-row"><strong>物流方式</strong> Hotai Delivery - 宅配                </div>
                <div class="order-details-row">
                    <strong>地址</strong> 
                    <address>glenn123 wendy<br>

123 Hong Kong<br>



Hong Kong,  700000<br>
馬拉威<br>
T: <a href="tel:12345678">12345678</a>

</address>
                </div>
                </div>
            </div>
        </div>
    </div>  

<!--            --><!--            -->    
<div class="order-details-items ordered">
        <div class="order-title">
        <strong>購物明細</strong>
            </div>
    
<div class="order-items-wrapper">
    <!-- Display Items in List Format with Images -->
    <table class="data table table-order-items" id="my-orders-table" summary="Items Ordered">
                            <tbody>
                        <tr class="suborder-info">
                <td class="col">
                    <div class="seller-info">
                    高都                        <span class="seller-line">|</span>
                        <span class="seller-type">冷藏   </span>
                    </div>
                </td>
                <!-- Display Sub Order Number -->
                <td class="col order-info">
                    <div class="sub-order-number"><strong>No.</strong> 20231115043701001
</div>
                </td>
                
            </tr>

                            <tr>
                    <!-- Product Information for each item -->
                    <td class="col order-item" colspan="2">
                        <div class="order-item-info">
                            <div class="product-item-info">
                                <span class="product-item-photo">
                                    <span class="product-image-container">
                                        <span class="product-image-wrapper" style="padding-bottom: 100%">
                                            <img class="product-image-photo" width="240" height="240" src="http://magento-hotai.com/media/catalog/productno_selection" alt="POP MART Minico玩具派對系列公仔組合">
                                        </span>
                                    </span>
                                </span>
                                <div class="product-item-details-wrapper">
                                <div class="product-item-details">
                                    <p class="product-item-sku">23064836</p>
                                    <strong class="product-item-name">【王品集團】聚日式鍋物商品卡4張</strong>
                                    <dl class="item-options">
                                        <dt>規格</dt>
                                        <dd class="tooltip wrapper">
                                            <div class="tooltip content">
                                                <dl class="item options">
                                                    <dt>規格</dt>
                                                    <dd>5-6房/4KG原裝箱     </dd>
                                                </dl>
                                            </div>
                                        </dd>
                                    </dl>
                                    <div class="product-item-subtotal">
                                        <span class="product-qty">x1</span><span class="price-container">
                                            <span class="price">
                                                <span class="price">$690</span>                                            </span>
                                        </span>
                                    </div>
                                </div>
                                </div>
                            </div>
                                                    </div>
                    </td>
                </tr>
                            <tr>
                    <!-- Product Information for each item -->
                    <td class="col order-item" colspan="2">
                        <div class="order-item-info">
                            <div class="product-item-info">
                                <span class="product-item-photo">
                                    <span class="product-image-container">
                                        <span class="product-image-wrapper" style="padding-bottom: 100%">
                                            <img class="product-image-photo" width="240" height="240" src="http://magento-hotai.com/media/catalog/productno_selection" alt="POP MART Minico玩具派對系列公仔組合">
                                        </span>
                                    </span>
                                </span>
                            
                                <div class="product-item-details-wrapper">
                                <div class="product-item-details">
                                    <p class="product-item-sku">23064836</p>
                                    <strong class="product-item-name">【水果狼】韓國麝香葡萄</strong>
                                    <dl class="item-options">
                                                                    <dt>規格</dt>
                        <dd>
                        5-6房/4KG原裝箱                                                    </dd>
                                                                    <dt>容量</dt>
                        <dd>
                                                            200g                                                    </dd>
                                    </dl>
                                    <div class="product-item-subtotal">
                                        <span class="product-qty">x1</span><span class="price-container">
                                            <span class="price">
                                                <span class="price">$100.00</span>                                            </span>
                                        </span>
                                    </div>
                                </div>
        </div>
                                
                            </div>
                                                    </div>
                    </td>
                </tr>
                        </tbody>
                    <tbody>
                        <tr class="suborder-info">
                <td class="col">
                    <div class="seller-info">
                    和泰聯網                        <span class="seller-line">|</span>
                        <span class="seller-type">常溫</span>
                    </div>
                </td>
                <!-- Display Sub Order Number -->
                <td class="col order-info">
                    <div class="sub-order-number"><strong>No.</strong> 20231115043702002</div>
                </td>
                
            </tr>

                            <tr>
                    <!-- Product Information for each item -->
                    <td class="col order-item" colspan="2">
                        <div class="order-item-info">
                            <div class="product-item-info">
                                <span class="product-item-photo">
                                    <span class="product-image-container">
                                        <span class="product-image-wrapper" style="padding-bottom: 100%">
                                            <img class="product-image-photo" width="240" height="240" src="http://magento-hotai.com/media/catalog/product/i/m/img_10_.png" alt="智能手表 APPLO">
                                        </span>
                                    </span>
                                </span>
                                
                                <div class="product-item-details-wrapper">
                                    <div class="product-item-details">
                                        <p class="product-item-sku">23064836</p>
                                        <strong class="product-item-name">破盤價【家購網嚴選】石墨烯蓄熱保暖被 180x210cm</strong>
                                        <dl class="item-options">
                                <dt>規格</dt>
                                                            <dd>
                                                            5-6房/4KG原裝箱                                            </dd>
                                            </dl>
                                        <div class="product-item-subtotal">
                                            <span class="product-qty">x1</span><span class="price-container">
                                                <span class="price">
                                                    <span class="price">$690</span>                                            </span>
                                            </span>
                                        </div>
                                    </div>
                                    <a href="http://magento-hotai.com/member/ticket/index" class="action secondary action-small">前往我的票券</a>
                                </div>
                                
                            </div>
                                                            
                                                    </div>
                    </td>
                </tr>
                            <tr>
                     <!-- Product Information for each item -->
                     <td class="col order-item" colspan="2">
                        <div class="order-item-info">
                            <div class="product-item-info">
                                <span class="product-item-photo">
                                    <span class="product-image-container">
                                        <span class="product-image-wrapper" style="padding-bottom: 100%">
                                            <img class="product-image-photo" width="240" height="240" src="http://magento-hotai.com/media/catalog/product/i/m/img_10_.png" alt="智能手表 APPLO">
                                        </span>
                                    </span>
                                </span>
                                
                                <div class="product-item-details-wrapper">
                                    <div class="product-item-details">
                                        <p class="product-item-sku">23064836</p>
                                        <strong class="product-item-name">破盤價【家購網嚴選】石墨烯蓄熱保暖被 180x210cm</strong>
                                        <dl class="item-options">
                                <dt>規格</dt>
                                                            <dd>
                                                            5-6房/4KG原裝箱                                            </dd>
                                            </dl>
                                        <div class="product-item-subtotal">
                                            <span class="product-qty">x1</span><span class="price-container">
                                                <span class="price">
                                                    <span class="price">$690</span>                                            </span>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                                
                            </div>
                                                            
                                                    </div>
                    </td>
                </tr>
                        </tbody>
            </table>

    <!-- If Pagination is Displayed -->
    
</div>
</div>
</div>
</div>
