<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Framework\View\Element\Template $block */
?>
<p><?= $block->escapeHtml(__('You have signed out and will go to our homepage in 5 seconds.')) ?></p>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/logout-redirect": {
                "url": "<?= $block->escapeJs($block->escapeUrl($block->getUrl())) ?>"
            }
        }
    }
</script>
<script type="text/javascript">
    //post message to react-native webview
    console.log('Logout success');
    window.ReactNativeWebView?.postMessage(JSON.stringify({
        type: 'LOGOUT_SUCCESS'
    }));
</script>
