<?php
declare(strict_types=1);

namespace Branch8\MarketPlaceParentOrderAdminUi\Block\Adminhtml\Edit\Tab\Information\OrderInformation;

use  Ecpay\Invoice\Block\Adminhtml\Order\OrderInvoiceFactory;
use Magento\Sales\Model\Order;

class EcPayInvoices extends \Magento\Backend\Block\Template
{
    protected function _prepareLayout()
    {
        $suborders = $this->getParentBlock()->getSubOrders();
        if (!empty($suborders)) {
            /**
             * @var $suborder Order
             */
            foreach ($suborders as $suborder) {
                if (isset($suborder['orders'])) {
                    foreach ($suborder['orders'] as $order) {
                        $this->addChild('ECPAY_INVOICES_' . $order->getId(),
                            \Ecpay\Invoice\Block\Adminhtml\Order\OrderInvoice::class,
                            [
                                'order' => $order,
                                'template'=>'Branch8_MarketPlaceParentOrderAdminUi::tab/view/information/ecpay_invoices/order-invoice.phtml'
                            ]
                        );
                    }
                }

            }
        }
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }
}
