<?php
declare(strict_types=1);

namespace Branch8\MarketPlaceParentOrderAdminUi\Block\Adminhtml\Edit\Tab\Information\OrderInformation;

class SubOrders extends \Magento\Backend\Block\Template
{
    public function toHtml()
    {
        $suborders = $this->getParentBlock()->getSubOrders();
        if (empty($suborders)) {
            return '';
        }
        $html = [];
        $itemsBlock = $this->getChildBlock('order_items');
        $counter = 0;
        foreach ($suborders as $suborderData) {
            $seller = $suborderData['seller'];
            if (empty($suborderData['orders']))
                continue;
            foreach ($suborderData['orders'] as $order) {
                $counter++;
                $newItemsBlock = $this->getLayout()->createBlock(
                    \Branch8\MarketPlaceParentOrderAdminUi\Block\Adminhtml\Edit\Tab\Information\OrderInformation\SubOrders\Items::class
                )->setColumns($itemsBlock->getColumns())->setOrder($order);
                $html[] = $newItemsBlock
                    ->setData('orders', $suborderData['orders'])
                    ->setData('seller', $seller)
                    ->setClass($counter % 2 == 0 ? 'even' : 'odd')
                    ->setTemplate(
                        'Branch8_MarketPlaceParentOrderAdminUi::tab/view/information/sub_orders/items.phtml'
                    )->toHtml();
            }

        }
        $this->setData('items_html', join('<br/>', $html));
        return parent::toHtml(); // TODO: Change the autogenerated stub
    }
}
