<?php

use Magento\Catalog\Api\Data\ProductInterface;
use Magento\Catalog\Model\Product;

/**
 * Product view template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Description
 * @var $escaper \Magento\Framework\Escaper
 */
?>
<?php
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$_product = $block->getProduct();

if (!$_product instanceof Product) {
    return;
}

$_call = $block->getAtCall();
$_code = $block->getAtCode();
$_className = $block->getCssClass();
$_attributeLabel = $block->getAtLabel();
$_attributeType = $block->getAtType();
$_attributeTitle = $block->getTitle();
$_attributeAddAttribute = $block->getAddAttribute();

$renderLabel = true;
// if defined as 'none' in layout, do not render
if ($_attributeTitle == 'none') {
    $renderLabel = false;
}

if ($_attributeLabel == 'default') {
    $_attributeLabel = $_product->getResource()->getAttribute($_code)->getStoreLabel();
}
if ($_attributeType == 'text') {
    $_attributeValue = ($_helper->productAttribute($_product, $_product->$_call(), $_code))
        ? $_product->getAttributeText($_code)
        : '';
} else {
    if ($_className === ProductInterface::SKU && $_product->getData('new_sku')) {
        $_attributeValue = $_product->getData('new_sku');
    } else {
        $_attributeValue = $_helper->productAttribute($_product, $_product->$_call(), $_code);
    }
}
?>

<?php if ($_attributeValue) :?>
    <div class="product attribute <?= $escaper->escapeHtmlAttr($_className) ?>">
        <?php if ($renderLabel) :?>
            <strong class="label"><?= $escaper->escapeHtml($_attributeTitle) ?></strong>
        <?php endif; ?>
        <div class="value" <?= /* @noEscape */ $_attributeAddAttribute ?>><?= /* @noEscape */ $_attributeValue ?></div>
    </div>
<?php endif; ?>
