<?php declare(strict_types=1);

namespace Branch8\WebkulMpBuyerSellerChat\Model\ResourceModel;

use Branch8\WebkulMpBuyerSellerChat\Api\Data\ChatConversationInterface;
use Webkul\MpBuyerSellerChat\Model\ResourceModel\LocalizedException;

class ChatConversation extends \Magento\Framework\Model\ResourceModel\Db\AbstractDb
{
    /**
     * Initialize resource model
     *
     * @return void
     */
    protected function _construct()
    {
        $this->_init(
            'marketplace_chat_conversation',
            'conversation_id'
        );
    }

    /**
     * @param \Magento\Framework\DataObject $object
     * @return void
     * @throws \Magento\Framework\Exception\AlreadyExistsException
     */
    public function save(\Magento\Framework\DataObject $object)
    {
        /**
         * @var $object ChatConversationInterface
         */
        if (!$object->getConversationUniqueId()) {
            $object->setConversationUniqueId($this->randomString());
        }
        parent::save($object); // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     */
    private function randomString()
    {
        return uniqid('cv_');
    }

    /**
     * @param ChatConversationInterface $chatConversation
     * @return ChatConversationInterface
     * @throws \Magento\Framework\Exception\LocalizedException
     */
    public function findBetweenSenderAndReceiver(
        ChatConversationInterface $chatConversation, $senderId, $receiverId)
    {
        $select = $this->getConnection()->select();
        $select->from('marketplace_chat_participant as p1')
            ->join('marketplace_chat_participant as p2', 'p1.conversation_id = p2.conversation_id', '',)
            ->join('marketplace_chat_conversation as c', 'p1.conversation_id = c.conversation_id')
            ->where('p1.profile_id = ? ', $senderId)
            ->where('p2.profile_id = ? ', $receiverId);
        $row = $this->getConnection()->fetchRow($select);
        if ($row) {
            $chatConversation->setData($row);
        }
        return $chatConversation;
    }
}
