<?php declare(strict_types=1);

namespace Branch8\WebkulMpBuyerSellerChat\Model\ResourceModel;

use Branch8\WebkulMpBuyerSellerChat\Api\Data\ChatConversationInterface;
use Branch8\WebkulMpBuyerSellerChat\Api\Data\ChatProfileInfoInterface;

/**
 *
 */
class ChatProfileInformation extends \Magento\Framework\Model\ResourceModel\Db\AbstractDb
{
    /**
     * Initialize resource model
     *
     * @return void
     */
    protected function _construct()
    {
        $this->_init(
            'marketplace_chat_profile_info',
            'entity_id'
        );
    }

    /**
     * @param \Magento\Framework\DataObject $object
     * @return void
     * @throws \Magento\Framework\Exception\AlreadyExistsException
     */
    public function save(\Magento\Framework\DataObject $object)
    {
        /**
         * @var $object ChatConversationInterface
         */
        if (!$object->getUniqueId()) {
            $object->setUniqueId($this->randomString());
        }
        parent::save($object); // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     */
    private function randomString()
    {
        return uniqid('');
    }

    /**
     * @param ChatProfileInfoInterface $object
     * @param int $objectId
     * @param string $entityType
     * @param string $registerAs
     * @return ChatProfileInfoInterface
     * @throws \Magento\Framework\Exception\LocalizedException
     */
    public function loadByObjectIdAndEntitytype(
        ChatProfileInfoInterface $object,
        int                      $objectId,
        string                   $entityType,
        string                   $registerAs = null
    )
    {
        $select = $this->getConnection()->select()->from(
            $this->getMainTable(),
            '*'
        )->where('object_id = ?', $objectId)
            ->where('entity_type = ?', $entityType);
        if ($registerAs) {
            $select->where('registered_as = ?', $registerAs);
        }
        $row = $this->getConnection()->fetchRow($select);
        if ($row) {
            $object->setData($row);
        }
        return $object;
    }
}
