<script>
    require([
        'jquery',
        'mage/translate',
        'select2',
        'domReady!'
    ], function($, $t){
        console.log('select2 loaded');
        function matchCustom(params, data) {
            console.log('matchCustom called', params, data);
            // If there are no search terms, return all of the data
            if ($.trim(params.term) === '') {
            return data;
            }

            // Do not display the item if there is no 'text' property
            if (typeof data.text === 'undefined') {
            return null;
            }

            // // `params.term` should be the term that is used for searching
            // // `data.text` is the text that is displayed for the data object
            // if (data.text.indexOf(params.term) > -1) {
            // var modifiedData = $.extend({}, data, true);
            // modifiedData.text += ' (matched)';

            // // You can return modified objects from here
            // // This includes matching the `children` how you want in nested data sets
            // return modifiedData;
            // }

            // Return `null` if the term should not be displayed
            return null;
        }
        if ($("select[name='parameters[filter_brand][]']").length) {
            $("select[name='parameters[filter_brand][]']").parents('.admin__field-control').addClass('select2-brand-container');
            if ($("select[name='parameters[filter_brand][]").parents('aside').length) {
                $("select[name='parameters[filter_brand][]").select2({
                    placeholder: {
                        id: '', // the value of the option
                        text: $t('Search...'),
                    },
                    closeOnSelect : false,
                    allowClear: true,
                    dropdownParent: $("select[name='parameters[filter_brand][]").parent()
                });
            } else {
                $("select[name='parameters[filter_brand][]").select2({
                    placeholder: {
                        id: '', // the value of the option
                        text: $t('Search...'),
                    },
                    closeOnSelect: false,
                    allowClear: true,
                    dropdownParent: $("select[name='parameters[filter_brand][]").parent()
                });
            }
        }
    });
</script>
