<?php
/** @var $escaper Magento\Framework\Escaper */
?>
<div id="cancel-order-modal-<?=/* @noEscape */ $block->getOrder()->getId() ?>" class="cancel-order-modal-wrapper" >
    <div class="cancel-order-modal-body">
        <h3><?= $block->escapeHtml(__("Reason for cancellation")) ?></h3>
        <select id="cancel-order-reason-<?=/* @noEscape */ $block->getOrder()->getId() ?>"
                class="cancel-order-reason" name="reason">
            <?php foreach ($block->getReasons() as $key => $description): ?>
                <option value="<?= $escaper->escapeHtml(__($description)) ?>">
                    <?= $escaper->escapeHtml(__($description)) ?>
                </option>
            <?php endforeach; ?>
        </select>
        <textarea id="cancel-order-reason-description-<?=/* @noEscape */ $block->getOrder()->getId() ?>"
                  maxlength="20"
                  class="cancel-order-reason-description"
                  name="reason_description"
                  placeholder="<?= $escaper->escapeHtml(__("Please describe the reason, limited to 20 words (optional)")) ?>"></textarea>
        <div class="custom-notice">
            <p><?= $escaper->escapeHtml(__("Things to note")) ?></p>
            <ol>
                <li><?= $block->escapeHtml(__('After the application is cancelled, Hotai Points will return the points to the original account 30 minutes later.')) ?></li>
            </ol>
        </div>
    </div>
</div>



