<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

use Branch8\HotaiCore\Model\Order\Status;

/**
 * @var $block \Branch8\Marketplace\Block\Order\View
 * @var $maskedModel \Branch8\MaskCustomerInformation\ViewModel\MaskPersonal
 * @var $cancelModel \Branch8\Sales\ViewModel\CancelModel
 */
$maskedModel = $block->getMaskViewModel();
$viewModel = $block->getViewModel();
$helper = $viewModel->getHelper();
$orderHelper = $viewModel->getOrderHelper();
$orderId = $block->getRequest()->getParam('id');
$order = $block->getOrder();
$shippingAddress=$order->getShippingAddress();
$billingAddress=$order->getBillingAddress();
$coBrandedHelper = $this->helper(\Branch8\HotaiPay\Helper\CreditCard\CoBranded::class);
$cancelModel = \Magento\Framework\App\ObjectManager::getInstance()->get(\Branch8\Sales\ViewModel\CancelModel::class);
if ($order) {
    $order->setData($maskedModel->mask('market_place_orders', $order->getData()));
}
if ($shippingAddress) {
    $shippingAddress->setData($maskedModel->mask('market_place_orders', $shippingAddress->getData()));
}
if ($billingAddress) {
    $billingAddress->setData($maskedModel->mask('market_place_orders', $billingAddress->getData()));
}
$orderStatusLabel = $order->getStatusLabel();
$paymentCode = '';
$paymentMethod = '';
if ($order->getPayment()) {
    $paymentCode = $order->getPayment()->getMethod();
    $paymentMethod = $order->getPayment()->getMethodInstance()->getTitle();
}
$marketplaceOrders = $block->getSellerOrderInfo($orderId);
if (count($marketplaceOrders)) {
    $adminPayStatus = $block->getAdminPayStatus($orderId);
    $itemCollection = $block->getOrderItemCollection($orderId);
    $qtyToInvoiceAvail = $block->getQtyToInvoiceCount($itemCollection);
    $qtyToShipAvail = $block->getQtyToShipCount($itemCollection);
    $qtyToCancelAvail = $block->getQtyToCancelCount($itemCollection);
    //$qtyToRefundAvail = $block->getQtyToRefundCollection($orderId);
    $qtyToRefundAvail = $block->getQtyToRefundCount($itemCollection);

    $tracking = $orderHelper->getOrderinfo($orderId);
    if ($tracking != "") {
        $disabled = $tracking->getTrackingNumber()==''? "":"readonly='readonly'";
        $shipmentId = $tracking->getShipmentId();
        $invoiceId=$tracking->getInvoiceId();
        $creditmemoId=$tracking->getCreditmemoId();

        $isCanceled=$tracking->getIsCanceled();
        if ($isCanceled && !$qtyToCancelAvail) {
            $orderStatusLabel = 'Canceled';
        }

        if ($shipmentId) {
            $itemShipStatus = 'Shipped';
        } else {
            $itemShipStatus = '';
        }
        if ($invoiceId) {
            $itemInvoiceStatus = 'Invoiced';
        } else {
            $itemInvoiceStatus = '';
        }
        if ($creditmemoId && !$qtyToRefundAvail) {
            $shippingamount=$tracking->getShippingCharges();
            $refundedShippingAmount=$tracking->getRefundedShippingCharges();
            if ($shippingamount-$refundedShippingAmount == 0) {
                $itemRefundStatus = 'Refunded';
            } else {
                $itemRefundStatus = '';
            }
        } else {
            $itemRefundStatus = '';
        }

        $itemCancelStatus = $isCanceled;

        $invoiceId = $tracking->getInvoiceId();
    }

    $orderStatus = strtolower($marketplaceOrders->getData()[0]['order_status']);
    ?>
    <div class="wk-mp-design">
        <div class="fieldset wk-mp-fieldset">
            <div class="page-title-wrapper">
                <h1 class="page-title">
                    <span data-ui-id="page-title-wrapper" class="base">
                        <?= /* @noEscape */ __('Manage Order #%1', $order->getRealOrderId()) ?>
                    </span>
                </h1>
                <div class="wk-dash-orderstatus order-view">
                    <label for="name" class="wk-dash-label">
                            <div
                            class="status <?= $escaper->escapeHtml(strtolower($marketplaceOrders
                            ->getData()[0]['order_status'])); ?>">
                            <?= $escaper->escapeHtml(($order->getStatusLabel())); ?>
                            </div>
                    </label>
                </div>

                <div class="order-date">
                    <?= /* @noEscape */ __('<span class="label">Order Date:</span> %1', '<date>' . $block
                    ->formatDate($order->getCreatedAt(), \IntlDateFormatter::MEDIUM, true, $block
                    ->getTimezoneForStore($order->getStore())) . '</date>') ?>
                </div>
                <div class="actions-toolbar order-actions-toolbar">
                    <div class="actions">
                        <a onclick="this.target='_blank';" href="<?= $escaper->escapeUrl($block
                        ->getUrl('marketplace/order/printorder', ['id'=>$orderId, '_secure' => $block
                        ->getRequest()->isSecure()]));?>" class="action">
                            <button class="button wk-mp-btn " title="<?= /* @noEscape */ __('Print') ?>"
                             type="submit" id="save_butn" >
                                <span><span><?= /* @noEscape */ __('Print') ?></span></span>
                            </button>
                        </a>
                        <?php $excludeStatusForCancel = [Status::STATUS_PROCESSING, Status::STATUS_TALLYING, Status::STATUS_PENDING_PAYMENT] ?>
                        <?php if (false && $itemCancelStatus!="1" && !in_array($orderStatus, $excludeStatusForCancel)) {?>

                            <a href="#" class="cancel-order"
                               id="cancel-order-<?= /* @noEscape */
                               $order->getId() ?>" data-mage-init='{
                                       "cancelOrderModal":{
                                           "url": "<?= /* @noEscape */
                            $block->getBaseUrl(); ?>",
                                           "order_id": "<?= $block->escapeHtml(__($order->getId())); ?>"
                                       }
                                    }'>
                                <button class="button wk-mp-btn" title="<?= /* @noEscape */ __('Cancel Order') ?>"
                                 type="button">
                                    <span><span><?= /* @noEscape */ __('Cancel Order') ?></span></span>
                                </button>
                            </a>

                            <?= $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")
                                ->setOrder($order)
                                ->setReasons($block->getCancellationReasons())
                                ->setTemplate("Branch8_MaskCustomerInformationToSeller::order/cancel-order-modal.phtml")->toHtml()
                            ?>
                            <?php
                        } ?>

                        <?php if ($qtyToInvoiceAvail && $order->canInvoice()) {?>
                            <a href="<?= $escaper->escapeUrl($block
                            ->getUrl('marketplace/order_invoice/create', ['id'=>$orderId, '_secure' => $block
                            ->getRequest()->isSecure()]))?>" class="action">
                                <button class="button wk-mp-btn"
                                title="<?= /* @noEscape */
                                 __('Create Invoice to confirm collected amount from buyer for this order') ?>"
                                 onclick="return confirm('<?= /* @noEscape */
                                    __("Are you sure you want to create invoice?") ?>')" type="button">
                                    <span><span><?= /* @noEscape */ __('Invoice') ?></span></span>
                                </button>
                            </a>
                            <?php
                        }
                        if ($itemInvoiceStatus=="Invoiced" && $itemRefundStatus!="Refunded"
                         && $order->canCreditmemo()) {
                            if ($paymentCode == 'mpcashondelivery' && !$adminPayStatus) { ?>
                                <a href="<?= $escaper->escapeUrl($block
                                ->getUrl('mpcashondelivery/order/payadmin', ['id'=>$orderId, '_secure' => $block
                                ->getRequest()->isSecure()]))?>" class="action">
                                    <button class="button wk-mp-btn" title="<?= /* @noEscape */
                                     __('Pay Admin for his commission for this order') ?>"
                                     onclick="return confirm('<?= /* @noEscape */ __("If you pay admin
                                     commission then you can not do refund for buyer in future.
                                     Are you sure you want to pay admin for his commission?") ?>')" type="button">
                                        <span><span><?= /* @noEscape */ __('Pay Admin Commission') ?></span></span>
                                    </button>
                                </a>
                                <a href="<?= $escaper->escapeUrl($block
                                ->getUrl('marketplace/order_creditmemo/create', ['order_id'=>$orderId, '_secure'=>$block
                                ->getRequest()->isSecure()]))?>" class="action">
                                    <button class="button wk-mp-btn"
                                    title="<?= /* @noEscape */ __('Create Credit Memo') ?>"
                                     type="button">
                                        <span><span><?= /* @noEscape */ __('Credit Memo') ?></span></span>
                                    </button>
                                </a>
                                <?php
                            } elseif ($paymentCode != 'mpcashondelivery') { ?>
                                <a href="<?= $escaper->escapeUrl($block
                                ->getUrl('marketplace/order_creditmemo/create', ['order_id'=>$orderId, '_secure'=>$block
                                ->getRequest()->isSecure()]))?>" class="action">
                                    <button class="button wk-mp-btn"
                                    title="<?= /* @noEscape */ __('Create Credit Memo') ?>" type="button">
                                        <span><span><?= /* @noEscape */ __('Credit Memo') ?></span></span>
                                    </button>
                                </a>
                                <?php
                            }
                        } ?>
                        <?php
                        if ($qtyToShipAvail && $block->isOrderCanShip($order)) { ?>
                            <a href="<?= $escaper->escapeUrl($block
                                ->getUrl('marketplace/order_shipment/create', ['id'=>$orderId, '_secure' => $block
                                ->getRequest()->isSecure()]))?>" class="action">
                                <button class="button wk-mp-btn"
                                title="<?= /* @noEscape */ __('Create Shipment for Order') ?>"
                                type="button" id="mp-create-shipment-btn">
                                    <span><span><?= /* @noEscape */ __('Ship') ?></span></span>
                                </button>
                            </a>
                            <?php
                        } ?>
                        <?php
                        if ($block->canCreateRma($order)) { ?>
                            <a href="<?= $escaper->escapeUrl($block
                                ->getUrl('b8marketplace/order/rma', ['id'=>$orderId, '_secure' => $block
                                ->getRequest()->isSecure()]))?>" class="action">
                                <button class="button wk-mp-btn"
                                title="<?= /* @noEscape */ __('Create Rma for Order') ?>"
                                type="button" id="mp-create-rma-btn">
                                    <span><span><?= /* @noEscape */ __('Rma') ?></span></span>
                                </button>
                            </a>
                            <?php
                        } ?>
                        <?php
                        if ($block->canFailedDelivery($order)) { ?>
                             <a href="#" class="failed-delivery"
                               id="failed-delivery-<?= /* @noEscape */
                               $order->getId() ?>" data-mage-init='{
                                       "failedDeliveryModal":{
                                           "url": "<?= /* @noEscape */
                            $block->getBaseUrl(); ?>",
                                           "order_id": "<?= $block->escapeHtml(__($order->getId())); ?>"
                                       }
                                    }'>
                                <button class="button wk-mp-btn" title="<?= /* @noEscape */ __('Failed Delivery') ?>"
                                 type="button">
                                    <span><span><?= /* @noEscape */ __('Failed Delivery') ?></span></span>
                                </button>
                            </a>

                            <?= $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")
                                ->setOrder($order)
                                ->setTemplate("Branch8_MaskCustomerInformationToSeller::order/failed-delivery-modal.phtml")->toHtml()
                            ?>
                            <?php
                        } ?>
                    </div>
                </div>
            </div>
            <?php
            $_links = $block->getLinks();
            ?>
            <ul class="items order-links">
                <?php foreach ($_links as $_link): ?>
                    <?php if (strpos($_link['url'], "marketplace/order/view") === false): ?>
                        <li class="nav item">
                            <a href="<?= $escaper->escapeUrl($_link['url']) ?>">
                                <?= $escaper->escapeHtml($_link['label']) ?>
                            </a>
                        </li>
                    <?php else: ?>
                        <li class="nav item current"><strong><?= $escaper->escapeHtml($_link['label']) ?></strong></li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
            <div class="order-details-items ordered">
                <div class="order-title">
                    <strong><?= /* @noEscape */ __('Items Ordered') ?></strong>
                </div>
                <?= $block->getChildHtml('marketplace_order_items') ?>
            </div>
            <?php if ($helper->getSellerProfileDisplayFlag()) { ?>
                <div class="block block-order-details-view">
                    <div class="block-title">
                        <strong><?= /* @noEscape */
                            __('Buyer Information') ?></strong>
                    </div>
                    <div class="block-content">
                        <div class="box-content" >
                            <div class="box" style="width: 25%;float: left;clear: none">

                                    <span class="label"><?= /* @noEscape */
                                        __('Customer Name') ?> : </span>
                                    <span class="value"><?= $escaper->escapeHtml($order->getCustomerName()); ?></span>
                                    <br/>
                                    <span class="label"><?= /* @noEscape */
                                        __('Email') ?> : </span>
                                    <span class="value"><?= $escaper->escapeHtml($order->getCustomerEmail()); ?></span>

                            </div>
                        </div>
                        <div class="box-content">
                            <div class="box"  style="width: 25%;float: left;clear: none">

                                <span class="label"><?= /* @noEscape */
                                    __('Cancellation Reason') ?> : </span>
                                <span class="value"><?= $cancelModel->getOrderCancellation($order); ?></span>

                            </div>
                        </div>
                    </div>

                </div>
            <?php } ?>
            <div class="block block-order-details-view">
                <div class="block-title">
                    <strong><?= /* @noEscape */ __('Order Information') ?></strong>
                </div>
                <div class="block-content">
                    <?php if (!$order->getIsVirtual()):  ?>
                        <?php if ($helper->getSellerProfileDisplayFlag() && $order
                                ->getShippingAddress()) { ?>
                            <div class="box box-order-shipping-address">
                                <strong class="box-title"><span>
                                    <?= /* @noEscape */ __('Shipping Address') ?></span></strong>
                                <div class="box-content">
                                    <address><?= /* @noEscape */ $block->getFormattedAddress($order
                                    ->getShippingAddress()); ?></address>
                                </div>
                            </div>
                            <?php
                        } ?>
                        <div class="box box-order-shipping-method">
                            <strong class="box-title">
                                <span><?= /* @noEscape */ __('Shipping Method') ?></span>
                            </strong>
                            <div class="box-content">
                            <?php if ($order->getShippingDescription()): ?>
                                <?= $escaper->escapeHtml($order->getShippingDescription()) ?>
                            <?php else: ?>
                                <?= /* @noEscape */ __('No shipping information available'); ?>
                            <?php endif; ?>
                            </div>
                        </div>
                    <?php endif; ?>
                    <?php if ($helper->getSellerProfileDisplayFlag()) { ?>
                        <div class="box box-order-billing-address">
                            <strong class="box-title">
                                <span><?= /* @noEscape */ __('Billing Address') ?></span>
                            </strong>
                            <div class="box-content">
                                <address><?= /* @noEscape */ $block->getFormattedAddress($order->getBillingAddress());?>
                            </address>
                            </div>
                        </div>
                        <?php
                    } ?>
                    <div class="box box-order-billing-method">
                        <strong class="box-title">
                            <span><?= /* @noEscape */ __('Payment Method') ?></span>
                        </strong>
                        <div class="box-content">
                            <?= $escaper->escapeHtml($paymentMethod); ?>
                            <p>
                                <?php
                                if($paymentCode == 'hotaipay'){
                                    echo $coBrandedHelper->getCoBrandedForChildOrderId($orderId);
                                }
                                ?>
                            </p>
                        </div>
                    </div>
                    <?php if ($order->getReferrerCode() || $order->getOrderNote()): ?>
                        <div class="box box-order-extra">
                            <strong class="box-title">
                                <span><?= __('Extra Information') ?></span>
                            </strong>
                            <div class="box-content">
                                <div class="wk-row">
                                    <span class="label"><?= __('Referer Code') ?> : </span>
                                    <span class="value">
                                <?= $escaper->escapeHtml($order->getReferrerCode()); ?></span>
                                </div>
                            </div>
                            <div class="box-content">
                                <div class="wk-row">
                                    <span class="label"><?= __('Order Note') ?> : </span>
                                    <span class="value">
                                <?= $escaper->escapeHtml($order->getOrderNote()); ?></span>
                                </div>
                            </div>
                        </div>
                    <?php endif ?>
                </div>
            </div>
        </div>
    </div>
    <div class="buttons-set">
        <p class="back-link">
            <a href="<?= $escaper->escapeUrl($block
            ->getUrl('marketplace/order/history', ['_secure' => $block
            ->getRequest()->isSecure()]));?>"
            class="left">&laquo; <?= /* @noEscape */ __('Back To My Orders') ?></a>
        </p>
    </div>
    <?php
}
