<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/** @var \Magento\Wishlist\Block\Customer\Wishlist\Items $block */
$columns = $block->getColumns();
?>
<div class="products-grid wishlist">
    <?php if (count($block->getItems())) : ?>
        <ol class="product-items">
            <?php $i = 0; foreach ($block->getItems() as $item) : ?>
                <?php $i++; ?>
                <li data-row="product-item" class="product-item <?= ($i === 1) ? 'page-first-item-1' : '' ?>" data-page="1" id="item_<?= $block->escapeHtmlAttr($item->getId()) ?>" >
                    <div class="product-item-info" data-container="product-grid">
                        <?php echo $block->getLayout()->getBlock("customer.wishlist.item.image")->setItem($item)->toHtml(); ?>
                        <div class="product-item-details">
                            <?php echo $block->getLayout()->getBlock("customer.wishlist.item.name")->setItem($item)->toHtml(); ?>
                            <?php echo $block->getLayout()->getBlock("customer.wishlist.item.price")->setItem($item)->toHtml(); ?>
                            <?php echo $block->getLayout()->getBlock("customer.wishlist.item.cart")->setItem($item)->toHtml(); ?>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
        </ol>
    <?php else : ?>
        <div class="message info empty">
            <span><?= $block->escapeHtml(__('This Wish List has no Items')) ?></span>
        </div>
    <?php endif; ?>
</div>

<?php foreach ($columns as $column) : ?>
    <?= $column->getAdditionalHtml() ?>
<?php endforeach; ?>
