<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Branch8\PointMoneyConfig\Helper\Common as PointMoneyConfigHelper;
use Magento\Framework\App\Action\Action;

/** @var \Branch8\ProductPoint\Block\Widget\ProductPoint $block */

// phpcs:disable Generic.Files.LineLength.TooLong
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper
?>
<?php
/**
 * Product carousel widget template
 *
 * @var \Magento\Framework\Escaper $escaper
 */

?>
<?php if ($block->getData('isAjax')): ?>
    <?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
        <?php
        $type = 'widget-product-carousel';

        $image = 'new_products_content_widget_grid';
        $items = $block->getProductCollection();

        $showWishlist = true;
        $showCompare = true;
        $showCart = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        $listColumn = [];
        $listColumnPoint = [];
        $listColumnPointRange = [];
        $limit = $block->getPageSize();
        $i = 0;
        $filterRange = $block->getFilterRange();
        $preorderHelper = $this->helper(\Webkul\MarketplacePreorder\Helper\Data::class);
        $vipHelper = $this->helper(\Branch8\PromotionPage\Helper\Data::class);
        foreach ($filterRange as $pointRange) {
            $listColumn[$i] = $block->getCollectionByRangePoint($pointRange);
            $listColumnPoint[$i] = $pointRange['title'];
            $listColumnPointRange[$i] = $pointRange['from'].'--'.$pointRange['to'];
            $i++;
        }
        $subTitle = $block->getData('sub_title');
        $totalPoints = $this->helper(\Branch8\HotaiPoint\Helper\Data::class)->getHotaiPoint();
        if ($subTitle) $subTitle = str_replace('[user_point]',  __('<strong class="price">%1</strong>', $this->helper(\Branch8\HotaiPoint\Helper\Data::class)->formatPoints($totalPoints, false, false, false)), $subTitle);
        ?>
        <?php if ($block->hasData('title')): ?>
            <h3 class="heading ico-point"><?= $block->escapeHtml($block->getData('title')) ?></h3>
            <?php if ($subTitle): ?>
                <div>
                    <h6 class="sub-heading"><?= $subTitle ?></h6>
                </div>
            <?php endif; ?>
        <?php endif; ?>
        <?php $count = 0; ?>
        <?php $alphabet = range('A', 'Z'); $alphabetSize = count($alphabet); ?>
        <div class="product-point-row">
            <?php foreach ($listColumn as $column): ?>

            <?php
                $promotionId = 'pointsAndCash_' . $alphabet[$count % $alphabetSize];
                $promotionName = '點加金_' . $listColumnPoint[$count];
                $itemListId = 'home_pointsAndCash';
                $itemListName = '首頁_點加金';
            ?>

            <div class="product-point-col" data-tab-content="product-point-col-<?= /* @noEscape */ $count ?>"
                 data-promotion-id="<?= $block->escapeHtml($promotionId) ?>"
                 data-promotion-name="<?= $block->escapeHtml($promotionName) ?>"
                 data-item-list-id="<?= $block->escapeHtml($itemListId) ?>"
                 data-item-list-name="<?= $block->escapeHtml($itemListName) ?>"
            >
                <div class="point-range" data-tab-trigger="product-point-col-<?= /* @noEscape */ $count ?>">
                    <?= __('<span class="price">+%1</span> 元', $listColumnPoint[$count]) ?>
                </div>
                <ol class="product-items widget-product-grid">
                    <?php $iterator = 1; ?>
                    <?php foreach ($column as $_item): ?>
                        <?php
                            $index = $iterator - 1;
                            $additionalParams['_query'] = [
                                'promotion_id' => $promotionId,
                                'promotion_name' => $promotionName,
                                'item_list_id' => $itemListId,
                                'item_list_name' => $itemListName,
                                'referer' => 'card',
                                'section' => 'point',
                                'position' => $index,
                            ];
                            $ga4SettingsObject = new \Magento\Framework\DataObject($additionalParams['_query']);
                            $attrDataStr = "
                                data-item-list-id='{$itemListId}'
                                data-item-list-name='{$itemListName}'
                                data-promotion-id='{$promotionId}'
                                data-promotion-name='{$promotionName}'
                            ";
                        ?>
                        <?= /* @noEscape */ ($iterator++ == 1) ? '<li class="product-item" '.$attrDataStr.'>' : '</li><li class="product-item" '.$attrDataStr.'>' ?>

                        <div class="product-item-info">
                            <?php
                                $isPreorder = $preorderHelper->isPreorder($_item->getId());
                                $isVip = $vipHelper->isProductInVipCategory($_item);
                                $livesearch_instock = $_item->getData('livesearch_instock') === '0' ? false : true;
                                $index_stock_status_label = $_item->getAttributeText('index_stock_status');
                                $is_custom_oos = ($index_stock_status_label === '缺貨' || $index_stock_status_label === 'Out of Stock' || !$livesearch_instock);
                                
                                $isSaleableAllowed = $_item->isSaleable();
                                if ($index_stock_status_label === '預購') {
                                    $isSaleableAllowed = true;
                                }

                                if ($_item->isSaleable() && $isSaleableAllowed) {
                                    $limitPurchasedViewModel = \Magento\Framework\App\ObjectManager::getInstance()->get(\Branch8\LimitPurchased\ViewModel\Product\LimitPurchased::class);
                                    $maxQty = $limitPurchasedViewModel->getMaxAllowedQty($_item);
                                    if ($maxQty !== null && $maxQty <= 0) {
                                        $isSaleableAllowed = false;
                                    }
                                }

                                if ($is_custom_oos && !$isPreorder) {
                                    $isSaleableAllowed = false;
                                }

                                $isOOS = ($is_custom_oos && !$isPreorder);
                                $isSaleable = $isSaleableAllowed;
                            ?>
                            <input type="hidden" class="ga4-item-json" value='<?= $escaper->escapeHtmlAttr($block->getGA4ItemJson($_item, $index)) ?>'/>
                            <a href="<?= $block->escapeUrl($block->getProductUrl($_item, $additionalParams)) ?>" class="product-item-photo <?= $isOOS ? 'product-item-photo-oos' : '' ?>" data-section="point">
                                <?= $block->getImage($_item, $image)->toHtml() ?>
                                <?php if ($isOOS): ?>
                                    <div class="action-stock unavailable"><span><?= $block->escapeHtml(__('缺貨中')) ?></span></div>
                                <?php endif; ?>
                            </a>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <?php
                                    if($isVip || $isPreorder){
                                        if($isVip){
                                            echo '<span class="vip-label">'.$block->escapeHtml(__("VIP")).'</span>';
                                        }
                                        if($isPreorder){
                                            echo '<span class="product-badge preorder">'.$block->escapeHtml(__('Preorder')).'</span>';
                                        }
                                    }
                                    ?>
                                    <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                    href="<?= $block->escapeUrl($block->getProductUrl($_item, $additionalParams)) ?>"
                                    class="product-item-link" data-section="point">
                                        <?= $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>
                                <?php if ($templateType): ?>
                                    <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                <?php endif; ?>

                                <?= $block->getProductPriceHtml($_item, $type) ?>
                                <?php
                                    $_item->setData('ga4_settings', $ga4SettingsObject)
                                ?>
                                <?= $block->getProductDetailsHtml($_item) ?>

                                <?php if ($showWishlist || $showCompare || $showCart): ?>
                                    <div class="product-item-inner<?php if ($isOOS) { echo ' stock-unavailable'; } ?>">
                                        <div class="product-item-actions">
                                            <?php if ($showCart): ?>
                                                <div class="actions-primary">
                                                    <?php if ($isSaleable): ?>
                                                        <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                                        <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_item->getSku()) ?>" action="<?= $block->escapeUrl($postParams['action']) ?>" method="post">
                                                            <input type="hidden" name="product" value="<?= $block->escapeHtmlAttr($postParams['data']['product']) ?>">
                                                            <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                            <input type="hidden" name="item_list_id" value="<?= /* @noEscape */ $itemListId ?>">
                                                            <input type="hidden" name="item_list_name" value="<?= /* @noEscape */ $itemListName ?>">
                                                            <input type="hidden" name="promotion_id" value="<?= /* @noEscape */ $promotionId ?>">
                                                            <input type="hidden" name="promotion_name" value="<?= /* @noEscape */ $promotionName ?>">
                                                            <input type="hidden" name="form_type" value="product_card">
                                                            <input type="hidden" name="section" value="point">

                                                            <?= $block->getBlockHtml('formkey') ?>
                                                            <button type="submit"
                                                                    title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                                    class="action tocart primary">
                                                                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                            </button>
                                                        </form>
                                                        <script type="text/x-magento-init">
                                                            {
                                                                "[data-role=tocart-form], .form.map.checkout": {
                                                                    "catalogAddToCart": {
                                                                        "product_sku": "<?= $escaper->escapeJs($_item->getSku()); ?>"
                                                                }
                                                            }
                                                        }
                                                        </script>
                                                    <?php else: ?>
                                                    <?php if ($_item->getIsSalable()): ?>
                                                        <div class="stock available"><?php /* <span><?= $block->escapeHtml(__('In stock')) ?></span> */ ?></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><?php /* <span><?= $block->escapeHtml(__('Out of stock')) ?></span> */ ?></div>
                                                    <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                            <?php if ($showWishlist || $showCompare): ?>
                                                <div class="actions-secondary" data-role="add-to-links">
                                                    <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist): ?>
                                                        <a href="#"
                                                        data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>' class="action towishlist" data-action="add-to-wishlist" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                            <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                    <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                        <?php $compareHelper = $this->helper(\Magento\Catalog\Helper\Product\Compare::class);?>
                                                        <a href="#" class="action tocompare" data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_item) ?>' title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                                            <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?= ($iterator == count($column) + 1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
                <?php $count++; if ($iterator > $block->getProductsCount()): ?>
                    <div class="actions">
                        <a href="<?= $block->getViewAllUrl($listColumnPointRange[$count - 1]) ?>" class="product-point-actions view-all"><?= __('View All') ?></a>
                    </div>
                <?php endif; ?>
            </div>
            <?php endforeach ?>
        </div>
    <?php endif;?>
<?php else: ?>
    <div class="co-loading-ajax" id="product-point-container" data-src="<?= $block->getUrl('productpoint/ajax/widget') ?>" data-role="product-point" data-ga4-event-uid="<?= uniqid('product_point_container_')?>"></div>
    <script type="text/x-magento-init">
        {
            "*": {
                "Branch8_ProductPoint/js/productpoint": {
                    "info": <?php echo $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($block->getData()); ?>,
                    "selector": "#product-point-container"
                }
            }
        }
    </script>
<?php endif;?>
