<?php
/**
 * Google Fonts Preconnect and Stylesheet
 *
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>

<!-- Google Fonts Loader Start -->
    <!-- Preconnect to fonts.googleapis.com -->
    <link rel="preconnect" href="https://fonts.googleapis.com"/>

    <!-- Preconnect to fonts.gstatic.com with crossorigin -->
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="anonymous"/>

    <!-- Link to Google Font: Noto Sans TC and Outfit -->
    <link rel="preload" href="https://fonts.googleapis.com/css2?family=Noto+Sans+TC:wght@400..900&amp;family=Outfit:wght@400..700&amp;display=swap" as="style"/>
<!-- Google Fonts Loader End -->


