<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Pager template
 *
 * @var \Magento\Framework\View\Element\Template $block
 */
?>
<div class="page-loading-mask">
    <div class="page-loading-mask-loader">
        <!-- <img src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>" alt="<?php /* @escapeNotVerified */ echo __('Loading...') ?>"> -->
    </div>
</div>

