<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>
<div class="password-principle">
    <div class="password-formula">
        <span><?= $block->escapeHtml(__('Password encrypted principle: ')) ?></span>
        <?= $block->escapeHtml(__('"oD" in English + MM + DD (date of receipt) + last 4 digits of the Uniform Numbers ID.')) ?>
    </div>
    <div class="password-sample">
        <span><?= $block->escapeHtml(__('Example: ')) ?></span>
        <?= $block->escapeHtml(__('For a company with tax ID "55384114", the password would be "oD01024114" (*lowercase "o", uppercase "D").')) ?>
    </div>
</div>
