<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
/**
 * @var $maskedModel \Branch8\MaskCustomerInformation\ViewModel\MaskPersonal
 */
$maskedModel = $block->getMaskViewModel();
$viewModel = $block->getViewModel();
$helper = $viewModel->getHelper();
$isPartner = $helper->isSeller();

if ($isPartner == 1) {
    $orderId = $block->getRequest()->getParam('order_id');
    $invoiceId = $block->getRequest()->getParam('invoice_id');
    $order = $block->getOrder();
    $shippingAddress = $order->getShippingAddress();
    $billingAddress = $order->getBillingAddress();
    if ($order) {
        $order->setData($maskedModel->mask('market_place_orders', $order->getData()));
    }
    if ($shippingAddress) {
        $shippingAddress->setData($maskedModel->mask('market_place_orders', $shippingAddress->getData()));
    }
    if ($billingAddress) {
        $billingAddress->setData($maskedModel->mask('market_place_orders', $billingAddress->getData()));
    }
    $invoice = $block->getInvoice();
    $invoiceStatus = '';
    if ($invoice->getState() == 1) {
        $invoiceStatus = __('Pending');
    } elseif ($invoice->getState() == 2) {
        $invoiceStatus = __('Paid');
    } elseif ($invoice->getState() == 3) {
        $invoiceStatus = __('Canceled');
    }
    $paymentMethod = '';
    if ($order->getPayment()) {
        $paymentMethod = $order->getPayment()->getMethodInstance()->getTitle();
    }

    $marketplaceOrders = $block->getSellerOrderInfo($orderId);
    if (count($marketplaceOrders)) { ?>
        <div class="wk-mp-design">
            <div class="fieldset wk-mp-fieldset">
                <div class="page-title-wrapper">
                    <h1 class="page-title">
                        <span data-ui-id="page-title-wrapper" class="base">
                            <?= __('Invoice #%1', $invoice->getIncrementId()) ?>
                        </span>
                    </h1>
                    <span class="order-status"><?= $escaper->escapeHtml($invoiceStatus) ?></span>
                    <div class="order-date">
                        <?php
                        $date = $block->formatDate(
                            $invoice->getCreatedAt(),
                            \IntlDateFormatter::MEDIUM,
                            true,
                            $block->getTimezoneForStore($order->getStore())
                        );
                        ?>
                        <?= __(
                            '<span class="label">Order Date:</span> %1',
                            '<date>' . $date . '</date>'
                        ) ?>
                    </div>
                    <div class="actions-toolbar order-actions-toolbar">
                        <div class="actions">
                            <a href="<?= $escaper->escapeUrl($block
                                ->getUrl(
                                    'marketplace/order_invoice/email',
                                    ['order_id' => $orderId, 'invoice_id' => $invoiceId,
                                        '_secure' => $block->getRequest()->isSecure()]
                                )) ?>"
                               onclick="return confirm('<?= __("Are you sure you want to send
                              invoice email to customer?") ?>')" class="action">
                                <button class="button wk-mp-btn" title="<?=
                                __('Send Email To Customer') ?>" type="button">
                                    <span><span><?= __('Send Email') ?></span></span>
                                </button>
                            </a>
                            <a href="<?= $escaper->escapeUrl($block
                                ->getUrl(
                                    'marketplace/order_invoice/printpdf',
                                    ['order_id' => $orderId, 'invoice_id' => $invoiceId,
                                        '_secure' => $block->getRequest()->isSecure()]
                                )); ?>" class="action">
                                <button class="button wk-mp-btn" title="<?= __('Invoice Slip') ?>">
                                    <span><span><?= __('Print Invoice') ?></span></span>
                                </button>
                            </a>
                        </div>
                    </div>
                </div>

                <div class="block block-order-details-view">
                    <div class="block-title">
                        <strong><?= __('Order Information') ?></strong>
                    </div>
                    <div class="block-content">
                        <div class="box-content">
                            <div class="box wk-box">
                                <strong class="box-title wk-order-info-title">
                                    <a href="<?= $escaper->escapeUrl($block
                                        ->getUrl('marketplace/order/view', ['id' => $orderId, '_secure' => $block
                                            ->getRequest()->isSecure()])); ?>">
                                        <?= __('Order # %1', $order->getIncrementId()) ?>
                                    </a>
                                </strong>
                                <div class="box-content">
                                    <div class="wk-row">
                                        <span class="label"><?= __('Order Status') ?> : </span>
                                        <span class="value">
                                            <?= $escaper->escapeHtml(ucfirst($order->getStatus())); ?></span>
                                    </div>
                                    <div class="wk-row">
                                        <span class="label"><?= __('Order Date') ?> : </span>
                                        <span class="value">
                                            <?= $block->formatDate($order
                                                ->getCreatedAt(), \IntlDateFormatter::MEDIUM, true, $block
                                                ->getTimezoneForStore($order->getStore())); ?></span>
                                    </div>
                                </div>
                            </div>
                            <?php if ($helper->getSellerProfileDisplayFlag()) { ?>
                                <div class="box wk-box">
                                    <strong class="box-title"><span>
                                        <?= __('Buyer Information') ?></span></strong>
                                    <div class="box-content">
                                        <div class="box wk-box">
                                            <div class="wk-row">
                                                <span class="label"><?= __('Customer Name') ?> : </span>
                                                <span class="value">
                                                    <?= $escaper->escapeHtml($order->getCustomerName()); ?></span>
                                            </div>
                                            <div class="wk-row">
                                                <span class="label"><?= __('Email') ?> : </span>
                                                <span class="value">
                                                    <?= $escaper->escapeHtml($order->getCustomerEmail()); ?></span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <?php } ?>
                        </div>
                    </div>
                </div>
                <?php if ($helper->getSellerProfileDisplayFlag()) { ?>
                    <div class="block block-order-details-view">
                        <div class="block-title">
                            <strong><?= __('Address Information') ?></strong>
                        </div>
                        <div class="block-content">
                            <div class="box-content">
                                <div class="box box-order-billing-address wk-box">
                                    <strong class="box-title">
                                        <span><?= __('Billing Address') ?></span>
                                    </strong>
                                    <div class="box-content">
                                        <address><?= $block->getFormattedAddress($billingAddress); ?></address>
                                    </div>
                                </div>
                                <?php if ($block->isOrderCanShip($order)): ?>
                                    <div class="box box-order-shipping-address wk-box">
                                        <strong class="box-title"><span><?= __('Shipping Address') ?></span></strong>
                                        <div class="box-content">
                                            <address><?= $block->getFormattedAddress($shippingAddress); ?></address>
                                        </div>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                <?php } ?>
                <div class="block block-order-details-view">
                    <div class="block-title">
                        <strong><?= __('Payment & Shipping Method') ?></strong>
                    </div>
                    <div class="block-content">
                        <div class="box box-order-billing-method wk-box">
                            <strong class="box-title">
                                <span><?= __('Payment Information') ?></span>
                            </strong>
                            <div class="box-content">
                                <?= $escaper->escapeHtml($paymentMethod); ?>
                            </div>
                        </div>
                        <?php if ($block->isOrderCanShip($order)): ?>
                            <div class="box box-order-shipping-method wk-box">
                                <strong class="box-title">
                                    <span><?= __('Shipping and Tracking Information') ?></span>
                                </strong>
                                <div class="box-content">
                                    <?php if ($order->getShippingDescription()): ?>
                                        <?= $escaper->escapeHtml($order->getShippingDescription()) ?>
                                    <?php else: ?>
                                        <?= __('No shipping information available'); ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
                <div class="block block-order-details-view wk-order-title-block">
                    <div class="block-title">
                        <strong><?= __('Items Invoiced') ?></strong>
                    </div>
                </div>
                <div class="order-details-items ordered">
                    <div class="order-title">
                        <strong><?= __('Items Invoiced') ?></strong>
                    </div>
                    <?= $block->getChildHtml('marketplace_order_invoice_items') ?>
                </div>
            </div>
        </div>
        <div class="buttons-set">
            <p class="back-link">
                <a href="<?= $escaper->escapeUrl(
                    $block->getUrl(
                        'marketplace/order/history',
                        ['_secure' => $block->getRequest()->isSecure()]
                    )); ?>"
                   class="left">&laquo; <?= __('Back To My Orders') ?>
                </a>
            </p>
        </div>
        <script>
            require([
                "jquery",
                "mage/mage"
            ], function ($) {
                var dataForm = $('#marketplace-shipping-form');
                dataForm.mage('validation', {});

                $('#mp-create-shipment-btn').click(function () {
                    dataForm.submit();
                });
            });
        </script>
        <?php
    }
} else { ?>
    <h2 class="wk-mp-error_msg">
        <?= __("To Become Seller Please Contact to Admin."); ?>
    </h2>
    <?php
} ?>
