<?php
/**
 * @var Magento\Framework\View\Element\Template $block
 */
?>
<div id="modal-credit-card-delete" class="modal-hide">
  <div class="modal-custom-content">
    <p><?= $block->escapeHtml(__('是否確定刪除此信用卡？')) ?></p>
  </div>
</div>
<script type="text/x-magento-init">
  {
    "*": {
        "b8HotaiPayDeletePopup": {
          "modalId": "modal-credit-card-delete"
        }
    }
}
</script>