<?php
/** @var \Branch8\HotaiPoint\Block\Transfer\Index $block */
?>
<div id="confirm-transfer-modal" class="modal-hide">
    <div class="modal-custom-content">
        <p><?= $block->escapeHtml(__('請再次確認以下資料之正確性')) ?></p>
        <p class="transfer-info">
            <?= $block->escapeHtml(__('轉入對象手機號碼')) ?> : <span id="info-transfer-to" class="transfer-info-phone"></span>
        </p>
        <p class="transfer-info">
            <?= $block->escapeHtml(__('轉入點數')) ?> : <span class="transfer-info-point" id="info-transfer-point"></span> <?= $block->escapeHtml(__('點')) ?>
        </p>

        <div class="warning-message">
            <div class="message">
                <?= $block->escapeHtml(__('提醒：點數移轉一經申請，不得因任何理由要求取消。')) ?>
            </div>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
  {
    "*": {
        "b8HotaiPointConfirmPopup": {}
    }
}
</script>