<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Framework\View\Element\Template */
?>
<div class="customer-section" id="customer-section"></div>
<script>
require([
    "Branch8_React/js/customer"
  ],
  function () {
    window.CPCustomer({ data: {
      name: "John Smith",
      age: 27,
    }, elCls: "customer-section" });
  });
</script>
