<?php
/** @var \Branch8\MicrosoftClarity\Block\Adminhtml\AdminScript $block */
$userId = $block->getAdminUserId();
$email = $block->getAdminUserEmail();
$role = "admin";
$clarityCode = $block->getClarityCode();
?>
<?php if ($clarityCode): ?>
<script type="text/javascript">     
    (function(c,l,a,r,i,t,y){         
        c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)}; 
        c[a]("set", "user_id", "<?= $userId ?>");
        c[a]("set", "email", "<?= $email ?>");
        c[a]("set", "role", "<?= $role ?>");        
        t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;         
        y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);     
    })(window, document, "clarity", "script", "<?= $clarityCode ?>");
    
    // custom data（after script loaded）
    if(typeof clarity === "undefined") {
        console.error("Clarity script not loaded");
    } else {
        clarity("set", "user_id", "<?= $userId ?>");
        clarity("set", "email", "<?= $email ?>");
        clarity("set", "role", "<?= $role ?>");
    }
</script>
<?php endif; ?>