<?php
/**
 * @var $block \Magento\Framework\View\Element\Template
 * @var $rmaModel \Branch8\Rma\ViewModel\Rma
 * @var $rmaDetails \Webkul\MpRmaSystem\Model\Details
 * @var $escaper \Magento\Framework\Escaper
 */
?>
<?php
$rmaModel = $block->getData('rma_model');
$resolutionOptions = $rmaModel->getResolutionOptions();
$rmaDetails = $rmaModel->getRmaDetails();
$resolutionType = (int)$rmaDetails->getResolutionType();
$resolution = $rmaModel->getHelper()->getResolutionTypeTitle($resolutionType);
$canChange = $rmaModel->allowChangeResotionStype()
?>

<div class="wk-row action">
    <span><?= $escaper->escapeHtml(__("Resolution Type")); ?> :</span>
    <?php if ($canChange): ?>
    <a href="javascript:void(0)" data-role="trigger-show-resolution-popup">
        <?php endif ?>
        <?= $escaper->escapeHtml($resolution); ?>
        <span class="icon-edit edit" aria-hidden="true"></span>
        <?php if ($canChange): ?>
    </a>
<?php endif ?>
</div>
<?php if ($canChange): ?>
<?php
$data = [
    'rmaId' => $rmaModel->getHelper()->encrypt($rmaDetails->getId()),
    'submitUrl' => $rmaModel->getChangResolutionTypeUrl(),
    'currentResolutionType' => $resolutionType,
    'form_key' => $rmaModel->getFormKey(),
];
?>
<script type="text/x-magento-init">
    {
        "body": {
            "Branch8_Rma/js/SwitchResolution": <?= $rmaModel->jsonEncode($data) ?>
    }
}
</script>
<div data-role="resolution-modal-wrapper" style="display: none">
    <div class="content fieldset">
        <div class="required field">
            <div class="control">
                <input type="radio" name="resolutiontype[]"
                       id="resolution_<?= \Branch8\Rma\Model\Rma\Resolution::RESOLUTION_TYPE_RETURN_REFUND ?>"
                       value="<?= \Branch8\Rma\Model\Rma\Resolution::RESOLUTION_TYPE_RETURN_REFUND ?>"
                       <?php if ($resolutionType === \Branch8\Rma\Model\Rma\Resolution::RESOLUTION_TYPE_RETURN_REFUND): ?>checked<?php endif; ?>
                       aria-required="true">
                <label for="resolution_<?= \Branch8\Rma\Model\Rma\Resolution::RESOLUTION_TYPE_RETURN_REFUND ?>">
                    <span><?= __('Return') ?></span>
                </label>
            </div>
            <div class="control">
                <input type="radio" name="resolutiontype[]"
                       id="resolution_<?= \Branch8\Rma\Model\Rma\Resolution::RESOLUTION_TYPE_EXCHANGE ?>"
                       value="<?= \Branch8\Rma\Model\Rma\Resolution::RESOLUTION_TYPE_EXCHANGE ?>"
                       <?php if ($resolutionType === \Branch8\Rma\Model\Rma\Resolution::RESOLUTION_TYPE_EXCHANGE): ?>checked<?php endif; ?>
                       aria-required="true">
                <label for="resolution_<?= \Branch8\Rma\Model\Rma\Resolution::RESOLUTION_TYPE_EXCHANGE ?>">
                    <span><?= __('Replace') ?></span>
                </label>
            </div>
        </div>
    </div>
</div>
<?php endif?>
