<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpBundleProduct
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
/**
 * @var $block \Webkul\Marketplace\Block\Order\Items
 * @var $item \Magento\Sales\Model\Order\Item
 * @var $priceRender \Branch8\Marketplace\ViewModel\PriceRender
 */
?>
<?php $order = $block->getOrder() ?>
<?php $items = $block->getItems();?>
<?php
$priceRender = $block->getData('price_render_model')?:\Magento\Framework\App\ObjectManager::getInstance()->get(
    \Branch8\Marketplace\ViewModel\PriceRender::class
);
$priceRenderList = $block->getLayout()->getBlock('sales.order.items.renderers');
$priceRender->setRenderList($priceRenderList);
$paymentCode = '';
$colSpan = 8;
$viewModel = $block->getViewModel();
if ($order->getPayment()) {
    $colSpan = 9;
    $paymentCode = $order->getPayment()->getMethod();
}
?>
<div class="table-wrapper order-items">
    <table class="data table table-order-items"
           id="my-orders-table" summary="<?= $escaper->escapeHtml(__('Items Ordered')) ?>">
        <caption class="table-caption"><?= $escaper->escapeHtml(__('Items Ordered')) ?></caption>
        <?php if($order->getData('is_flagship_store_process_order')):?>
            <?php $flagshipHelper = $this->helper(\Branch8\FlagshipStore\Helper\Sales::class); ?>
                <tr>
                    <td>
                        <p><?php echo __('This is flagship process shipping order for');?></p>
                        <?php
                        $orders = $order->getData('is_flagship_store_process_order');
                        $incrementIds = explode(',', (string)$orders);
                        foreach ($incrementIds as $_incrementId){
                            echo $_incrementId.'<br />';
                        }
                        ?>
                    </td>
                </tr>
        <?php else: ?>
        <thead>
        <?php if ($block->isPagerDisplayed()): ?>
            <tr>
                <td colspan="<?= $escaper->escapeHtml($colSpan) ?>"
                    data-block="order-items-pager-top" class="order-pager-wrapper order-pager-wrapper-top">
                    <?= $block->getPagerHtml() ?>
                </td>
            </tr>
        <?php endif ?>
        <tr>
            <th class="col name"><?= $escaper->escapeHtml(__('Product Name')) ?></th>
            <th class="col sku"><?= $escaper->escapeHtml(__('SKU')) ?></th>
            <th class="col sku"><?= $escaper->escapeHtml(__('Cost')) ?></th>
            <th class="col sku"><?= $escaper->escapeHtml(__('Point')) ?></th>
            <th class="col price"><?= $escaper->escapeHtml(__('Sell Price')) ?></th>
            <th class="col qty"><?= $escaper->escapeHtml(__('Qty')) ?></th>
            <th class="col price"><?= $escaper->escapeHtml(__('Total Price')) ?></th>
            <?php
            if ($paymentCode == 'mpcashondelivery') {?>
                <th class="col price"><?= $escaper->escapeHtml(__('COD Charges')) ?></th>
                <?php
            } ?>
    <!--        <th class="col price"><?php /*= $escaper->escapeHtml(__('Admin Commission')) */?></th>
            <th class="col price"><?php /*= $escaper->escapeHtml(__('Vendor Total')) */?></th>-->
            <th class="col price"><?= $escaper->escapeHtml(__('Subtotal')) ?></th>
            <th class="col flow-status"><?= $escaper->escapeHtml(__('Flow Status')) ?></th>
            <th class="col tran-ssn"><?= $escaper->escapeHtml(__('TransSN')) ?></th>

        </tr>
        </thead>
        <?php
        $i = 0;
        $count = count($items);
        /**
         * @var $item \Magento\Sales\Model\Order\Item
         */
        foreach ($items as $item) {
            if ($item->getParentItem()) {
                continue;
            }
            $i++;
            $rowTotal = $item->getMageproPrice() * $item->getQtyOrdered();
            $rowTotalIncludeTax = $item->getRowTotalInclTax();
            $sellerItemCost = $item->getActualSellerAmount();
            $sellerItemCommission = $item->getTotalCommission();
            $currencyRate = $item->getCurrencyRate();

            $result = [];
            if ($options = $item->getProductOptions()) {
                if (isset($options['options'])) {
                    $result = $viewModel->mergeArray($result, $options['options']);
                }
                if (isset($options['additional_options'])) {
                    $result = $viewModel->mergeArray($result, $options['additional_options']);
                }
                if (isset($options['attributes_info'])) {
                    $result = $viewModel->mergeArray($result, $options['attributes_info']);
                }
            }
            // for bundle product
            $bundleitems = $viewModel->mergeArray([$item], $item->getChildrenItems());
            $count = count($bundleitems);
            $index = 0;
            $prevOptionId = '';
            ?>
            <tbody>
            <?php
            $calculationStatus = true;
            if ($item->getProductType() == \Magento\Bundle\Model\Product\Type::TYPE_CODE) {
                $productOptions = $item->getProductOptions();
                $calculationStatus = $productOptions['product_calculations'] ? true : false;
            }
            if ($calculationStatus) { ?>
                <tr class="border" id="order-item-row-<?= $escaper->escapeHtml($item->getId()) ?>">
                    <?php
                    if ($item->getProductType()=='downloadable') { ?>
                        <td class="col name" data-th="<?= $escaper->escapeHtml(__('Product Name')); ?>">
                            <strong class="product name product-item-name">
                                <?= $escaper->escapeHtml($item->getName()) ?>
                            </strong>
                            <?php if ($options = $block->getItemOptions($item)): ?>
                                <dl class="item-options links">
                                    <?php foreach ($options as $option): ?>
                                        <dt><?= $escaper->escapeHtml($option['label']) ?></dt>
                                        <?php if (!$block->getPrintStatus()): ?>
                                            <?php $formatedOptionValue = $block->getFormatedOptionValue($option) ?>
                                            <dd>
                                                <?php if (isset($formatedOptionValue['full_view'])): ?>
                                                    <?= /* @noEscape */ $formatedOptionValue['full_view'] ?>
                                                <?php else: ?>
                                                    <?=/* @noEscape */ $formatedOptionValue['value'] ?>
                                                <?php endif; ?>
                                            </dd>
                                        <?php else: ?>
                                            <dd>
                                                <?= $escaper->escapeHtml(
                                                    (isset($option['print_value']) ?
                                                        $option['print_value'] : $option['value'])
                                                ) ?></dd>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                </dl>
                            <?php endif; ?>
                            <?php /* downloadable */?>
                            <?php if ($links = $block->getDownloadableLinks($item->getId())): ?>
                                <dl class="item-options links">
                                    <dt>
                                        <?= $escaper->escapeHtml(
                                            $block->getLinksTitle($item->getId())
                                        ) ?>
                                    </dt>
                                    <?php foreach ($links->getPurchasedItems() as $link): ?>
                                        <dd><?= $escaper->escapeHtml($link->getLinkTitle()); ?></dd>
                                    <?php endforeach; ?>
                                </dl>
                            <?php endif; ?>
                            <?php /* EOF downloadable */?>

                            <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                            <?php if ($addInfoBlock):?>
                                <?= $addInfoBlock->setItem($item->getOrderItem())->toHtml(); ?>
                            <?php endif; ?>
                            <?= $escaper->escapeHtml($item->getDescription()) ?>
                            <?php $addInfoBlock = $block->getOrderItemAdditionalInfoBlock(); ?>
                            <?php if ($addInfoBlock): ?>
                                <?= $addInfoBlock->setItem($item)->toHtml() ?>
                            <?php endif;?>
                        </td>
                        <?php
                    } else { ?>
                        <td class="col name" data-th="<?= $escaper->escapeHtml(__('Product Name')); ?>">
                            <strong class="product name product-item-name">
                                <?= $escaper->escapeHtml($item->getName()) ?>
                            </strong>
                            <?php if ($options = $result): ?>
                                <dl class="item-options">
                                    <?php foreach ($options as $option): ?>
                                        <dt><?= $escaper->escapeHtml($option['label']) ?></dt>
                                        <?php if (!$block->getPrintStatus()): ?>
                                            <?php $formatedOptionValue = $block->getFormatedOptionValue($option) ?>
                                            <dd>
                                                <?php if (isset($formatedOptionValue['full_view'])): ?>
                                                    <?= /* @noEscape */ $formatedOptionValue['full_view'] ?>
                                                <?php else: ?>
                                                    <?= /* @noEscape */ $formatedOptionValue['value'] ?>
                                                <?php endif; ?>
                                            </dd>
                                        <?php else: ?>
                                            <dd>
                                                <?= /* @noEscape */ nl2br($escaper->escapeHtml(
                                                    (isset($option['print_value']) ?
                                                        $option['print_value'] : $option['value'])
                                                )) ?>
                                            </dd>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                </dl>
                            <?php endif; ?>
                            <?php $addInfoBlock = $block->getOrderItemAdditionalInfoBlock(); ?>
                            <?php if ($addInfoBlock): ?>
                                <?= $addInfoBlock->setItem($item)->toHtml() ?>
                            <?php endif;?>
                        </td>
                    <?php }?>
                    <td class="col sku" data-th="<?= $escaper->escapeHtml(__('SKU')); ?>">
                        <?= $escaper->escapeHtml($item->getSku()) ?>
                    </td>
                    <td class="col cost" data-th="<?= $escaper->escapeHtml(__('Cost')); ?>">
                        <?= $order->formatPrice($item->getData('base_cost')) ?>
                    </td>
                    <td class="col point" data-th="<?= $escaper->escapeHtml(__('Point')); ?>">
                        <?php
                            $rowPointUsed = ($item->getData('row_total_point_used') == null) ? 0 : $item->getData('row_total_point_used');
                        ?>
                        <?= $escaper->escapeHtml(number_format($rowPointUsed, 2, '.', ',')) ?>
                    </td>
                    <td class="col price" data-th="<?= $escaper->escapeHtml(__('Price')); ?>">
                        <?= /* @noEscape */ $priceRender->renderItemPrice($item); ?>
                    </td>
                    <td class="col qty" data-th="<?= $escaper->escapeHtml(__('Qty')); ?>">
                        <ul class="items-qty">
                            <?php if ($item->getQtyOrdered() > 0): ?>
                                <li class="item">
                                    <span class="title"><?= $escaper->escapeHtml(__('Ordered')); ?></span>
                                    <span class="content"><?= $escaper->escapeHtml($item->getQtyOrdered()*1) ?></span>
                                </li>
                            <?php endif; ?>
                            <?php if ($item->getQtyInvoiced() > 0): ?>
                                <li class="item">
                                    <span class="title"><?= $escaper->escapeHtml(__('Invoiced')); ?></span>
                                    <span class="content">
                                        <?= $escaper->escapeHtml($item->getQtyInvoiced()*1) ?>
                                    </span>
                                </li>
                            <?php endif; ?>
                            <?php if ($item->getQtyShipped() > 0): ?>
                                <li class="item">
                                    <span class="title"><?= $escaper->escapeHtml(__('Shipped')); ?></span>
                                    <span class="content"><?= $escaper->escapeHtml($item->getQtyShipped()*1) ?></span>
                                </li>
                            <?php endif; ?>
                            <?php if ($item->getQtyCanceled() > 0): ?>
                                <li class="item">
                                    <span class="title"><?= $escaper->escapeHtml(__('Canceled')); ?></span>
                                    <span class="content">
                                        <?= $escaper->escapeHtml($item->getQtyCanceled()*1) ?>
                                    </span>
                                </li>
                            <?php endif; ?>
                            <?php if ($item->getQtyRefunded() > 0): ?>
                                <li class="item">
                                    <span class="title"><?= $escaper->escapeHtml(__('Refunded')); ?></span>
                                    <span class="content">
                                        <?= $escaper->escapeHtml($item->getQtyRefunded()*1) ?>
                                    </span>
                                </li>
                            <?php endif; ?>
                        </ul>
                    </td>
                    <td class="col price" data-th="<?= $escaper->escapeHtml(__('Total Price')); ?>">
                        <?= /* @noEscape */ $priceRender->renderItemRowTotalHtml($item); ?>
                    <?php
                    if ($paymentCode == 'mpcashondelivery') {?>
                        <td class="col price" data-th="<?= $escaper->escapeHtml(__('COD Charges')) ?>">
                            <?= /* @noEscape */ $order->formatPrice(
                                $block->getOrderedPricebyorder($currencyRate, $item->getCodCharges())
                            );?></td>
                        <?php
                    } ?>
                    <!--<td class="col price" data-th="<?php /*= $escaper->escapeHtml(__('Admin Commission')); */?>">
                        <?php /*= $order->formatPrice(
                            $block->getOrderedPricebyorder($currencyRate, $sellerItemCommission)
                        );*/?></td>-->
                  <!--  <td class="col price" data-th="<?php /*= $escaper->escapeHtml(__('Vendor Total')); */?>">
                        <?php /*=  $order->formatPrice(
                            $block->getOrderedPricebyorder($currencyRate, $sellerItemCost)
                        );*/?></td>-->
                    <td style="text-align:center" class="col subtotal" data-th="<?= $escaper->escapeHtml(__('Subtotal')); ?> text-center">
                        <?= /* @noEscape */ $order->formatPrice(
                            $block->getOrderedPricebyorder($currencyRate, $rowTotalIncludeTax)
                        );?>
                    </td>
                    <td class="col flow-status" data-th="<?= $escaper->escapeHtml(__('Flow Status')); ?>">
                        <?= $escaper->escapeHtml($item->getFlowStatus()) ?></td>
                    <td class="col flow-status" data-th="<?= $escaper->escapeHtml(__('TransSN')); ?>">
                        <?= $escaper->escapeHtml($item->getData('hotai_point_deduction_point_trans_s_n')) ?></td>
                </tr>
                <?php
                if (count($bundleitems) > 0
                    &&
                    $item->getProductType() == \Magento\Bundle\Model\Product\Type::TYPE_CODE
                ) {
                    foreach ($bundleitems as $bundleitem) {
                        if ($bundleitem->getParentItem()) {
                            $attributes = $block->getSelectionAttribute($bundleitem);
                            ?>
                            <tr class="options-label">
                                <td class="col label" colspan="<?= $escaper->escapeHtml($colSpan) ?>"
                                    data-th="<?= $escaper->escapeHtml(__('Product Name')); ?>">
                                    <?= /* @noEscape */ $attributes['option_label'] ?>
                                </td>
                            </tr>
                            <tr class="border bundle"
                                id="order-item-row-<?= $escaper->escapeHtml($bundleitem->getId()) ?>">
                                <td class="col value" data-th="<?= $escaper->escapeHtml(__('Product Name')); ?>">
                                    <?= $viewModel->getValueHtml($bundleitem)?>
                                    <?php $addInfoBlock = $block->getOrderItemAdditionalInfoBlock(); ?>
                                    <?php if ($addInfoBlock): ?>
                                        <?= $addInfoBlock->setItem($bundleitem)->toHtml() ?>
                                    <?php endif;?>
                                </td>
                                <td class="col sku" data-th="<?= $escaper->escapeHtml(__('SKU')); ?>">
                                    <?= $escaper->escapeHtml($bundleitem->getSku()) ?></td>

                                <td class="col price" data-rwd-label="<?= $escaper->escapeHtml(__('Price')) ?>">
                                    &nbsp;</td>
                                <td class="col qty item_status"
                                    data-rwd-label="<?= $escaper->escapeHtml(__('Status')) ?>">
                                    <ul class="items-qty">
                                        <?php if ($bundleitem->getQtyOrdered() > 0): ?>
                                            <li class="item">
                                                <span class="title"><?= $escaper->escapeHtml(__('Ordered')); ?></span>
                                                <span class="content">
                                                    <?= $escaper->escapeHtml($bundleitem->getQtyOrdered()*1) ?></span>
                                            </li>
                                        <?php endif; ?>
                                        <?php if ($bundleitem->getQtyInvoiced() > 0): ?>
                                            <li class="item">
                                                <span class="title"><?= $escaper->escapeHtml(__('Invoiced'));?></span>
                                                <span class="content">
                                                    <?= $escaper->escapeHtml($bundleitem->getQtyInvoiced()*1) ?>
                                                </span>
                                            </li>
                                        <?php endif; ?>
                                        <?php if ($bundleitem->getQtyShipped() > 0 &&
                                            !$block->isShipmentSeparately()): ?>
                                            <li class="item">
                                                <span class="title"><?= $escaper->escapeHtml(__('Shipped')); ?></span>
                                                <span class="content">
                                                    <?= $escaper->escapeHtml($bundleitem->getQtyShipped()*1) ?></span>
                                            </li>
                                        <?php endif; ?>
                                        <?php if ($bundleitem->getQtyCanceled() > 0): ?>
                                            <li class="item">
                                                <span class="title"><?= $escaper->escapeHtml(__('Canceled')); ?>
                                            </span>
                                                <span class="content">
                                                    <?= $escaper->escapeHtml($bundleitem->getQtyCanceled()*1) ?>
                                                </span>
                                            </li>
                                        <?php endif; ?>
                                        <?php if ($bundleitem->getQtyRefunded() > 0): ?>
                                            <li class="item">
                                                <span class="title"><?= $escaper->escapeHtml(__('Refunded')); ?>
                                            </span>
                                                <span class="content">
                                                    <?= $escaper->escapeHtml($bundleitem->getQtyRefunded()*1) ?>
                                                </span>
                                            </li>
                                        <?php endif; ?>
                                    </ul>
                                </td>
                                <td class="lin-hide">&nbsp;</td>
                                <td class="lin-hide">&nbsp;</td>
                                <td class="lin-hide">&nbsp;</td>
                                <td class="lin-hide">&nbsp;</td>
                            </tr>
                            <?php
                        } } } ?>
                <?php
            } else { ?>
                <?php foreach ($bundleitems as $bundleitem): ?>
                    <?php
                    $bundleItemTotals = $block->getSellerOrdersList(
                        $order->getId(),
                        $bundleitem->getProductId(),
                        $bundleitem->getId()
                    );
                    $codCharges = 0;
                    foreach ($bundleItemTotals as $bundleItemTotal) {
                        $rowTotal = $bundleItemTotal->getMageproPrice() * $bundleitem->getQtyOrdered();
                        $sellerItemCost = $bundleItemTotal->getActualSellerAmount();
                        $sellerItemCommission = $bundleItemTotal->getTotalCommission();
                        $currencyRate = $bundleItemTotal->getCurrencyRate();
                        if ($paymentCode == 'mpcashondelivery') {
                            $codCharges = $bundleItemTotal->getCodCharges();
                        }
                    }
                    ?>
                    <?php $attributes_option = $block->getSelectionAttribute($bundleitem); ?>
                    <?php if ($bundleitem->getParentItem()): ?>
                        <?php $attributes = $attributes_option ?>
                        <?php if ($prevOptionId != $attributes['option_id']): ?>
                            <tr class="options-label">
                                <td class="col label" colspan="<?= $escaper->escapeHtml($colSpan) ?>"
                                    data-th="<?= $escaper->escapeHtml(__('Product Name')); ?>">
                                    <?= $escaper->escapeHtml($attributes['option_label']) ?>
                                </td>
                            </tr>
                            <?php $prevOptionId = $attributes['option_id'] ?>
                        <?php endif; ?>
                    <?php endif; ?>
                    <tr<?= (++$index==$count)?' class="border bundle"':' class="bundle"' ?>
                        id="order-item-row-<?= $escaper->escapeHtml($bundleitem->getId()) ?>">
                        <?php
                        if (!$bundleitem->getParentItem()) {?>
                            <td><h3 class="product-name"><?= $escaper->escapeHtml($bundleitem->getName()) ?></h3></td>
                            <td class="col sku" data-th="<?= $escaper->escapeHtml(__('SKU')); ?>">
                                <?= $escaper->escapeHtml($bundleitem->getSku()) ?></td>
                            <td class="col price" data-rwd-label="<?= $escaper->escapeHtml(__('Price')) ?>">
                                <span class="price-excluding-tax"
                                      data-label="<?= $escaper->escapeHtml(__('Excl. Tax')); ?>">
                                    <?= /* @noEscape */ $order->formatPrice($item->getPrice());?>
                                </span>
                            </td>
                            <td class="col qty item_status"
                                data-rwd-label="<?= $escaper->escapeHtml(__('Status')) ?>">
                                <ul class="items-qty">
                                    <?php if ($item->getQtyOrdered() > 0): ?>
                                        <li class="item">
                                            <span class="title"><?= $escaper->escapeHtml(__('Ordered')); ?></span>
                                            <span class="content">
                                                <?= $escaper->escapeHtml($item->getQtyOrdered()*1) ?></span>
                                        </li>
                                    <?php endif; ?>
                                </ul>
                            </td>
                            <td class="lin-hide">&nbsp;</td>
                            <td class="lin-hide">&nbsp;</td>
                            <td class="lin-hide">&nbsp;</td>
                            <td class="lin-hide">&nbsp;</td>
                            <?php
                        } else { ?>
                            <?php
                            $i++;
                            ?>
                            <td class="col value" data-th="<?= $escaper->escapeHtml(__('Product Name')); ?>">
                                <?= $block->getValueHtml($bundleitem)?>
                                <?php $addInfoBlock = $block->getOrderItemAdditionalInfoBlock(); ?>
                                <?php if ($addInfoBlock): ?>
                                    <?= $addInfoBlock->setItem($bundleitem)->toHtml() ?>
                                <?php endif;?>
                            </td>
                            <td class="col sku" data-th="<?= $escaper->escapeHtml(__('SKU')); ?>">
                                <?= $escaper->escapeHtml($bundleitem->getSku()) ?></td>
                            <td class="col price" data-rwd-label="<?= $escaper->escapeHtml(__('Price')) ?>">
                                <?= /* @noEscape */ $order->formatPrice($bundleitem->getPrice());?></td>
                            <td class="col qty item_status"
                                data-rwd-label="<?= $escaper->escapeHtml(__('Status')) ?>">
                                <ul class="items-qty">
                                    <?php if ($bundleitem->getQtyOrdered() > 0): ?>
                                        <li class="item">
                                            <span class="title"><?= $escaper->escapeHtml(__('Ordered')); ?></span>
                                            <span class="content">
                                                <?= $escaper->escapeHtml($bundleitem->getQtyOrdered()*1) ?></span>
                                        </li>
                                    <?php endif; ?>
                                    <?php if ($bundleitem->getQtyInvoiced() > 0): ?>
                                        <li class="item">
                                            <span class="title"><?= $escaper->escapeHtml(__('Invoiced')); ?></span>
                                            <span class="content">
                                                <?= $escaper->escapeHtml($bundleitem->getQtyInvoiced()*1) ?></span>
                                        </li>
                                    <?php endif; ?>
                                    <?php if ($bundleitem->getQtyShipped() > 0 &&
                                        !$block->isShipmentSeparately()): ?>
                                        <li class="item">
                                            <span class="title"><?= $escaper->escapeHtml(__('Shipped')); ?></span>
                                            <span class="content">
                                                <?= $escaper->escapeHtml($bundleitem->getQtyShipped()*1) ?></span>
                                        </li>
                                    <?php endif; ?>
                                    <?php if ($bundleitem->getQtyCanceled() > 0): ?>
                                        <li class="item">
                                            <span class="title"><?= $escaper->escapeHtml(__('Canceled')); ?></span>
                                            <span class="content">
                                                <?= $escaper->escapeHtml($bundleitem->getQtyCanceled()*1) ?></span>
                                        </li>
                                    <?php endif; ?>
                                    <?php if ($bundleitem->getQtyRefunded() > 0): ?>
                                        <li class="item">
                                            <span class="title"><?= $escaper->escapeHtml(__('Refunded')); ?></span>
                                            <span class="content">
                                                <?= $escaper->escapeHtml($bundleitem->getQtyRefunded()*1) ?></span>
                                        </li>
                                    <?php endif; ?>
                                </ul>
                            </td>
                            <td class="col price" data-th="<?= $escaper->escapeHtml(__('Total Price')); ?>">
                                <?= /* @noEscape */ $order->formatPrice(
                                    $block->getOrderedPricebyorder($currencyRate, $rowTotal)
                                );?></td>
                            <?php if ($paymentCode == 'mpcashondelivery') { ?>
                                <td class="col price" data-th="<?= $escaper->escapeHtml(__('COD Charges')) ?>">
                                    <?= /* @noEscape */ $order->formatPrice($block->getOrderedPricebyorder(
                                        $currencyRate,
                                        $codCharges
                                    ));?></td>
                                <?php
                            } ?>
                           <!-- <td class="col price" data-th="<?php /*= $escaper->escapeHtml(__('Admin Commission')); */?>">
                                <?php /*=  $order->formatPrice($block->getOrderedPricebyorder(
                                    $currencyRate,
                                    $sellerItemCommission
                                ));*/?>
                            </td>-->
                           <!-- <td class="col price" data-th="<?php /*= $escaper->escapeHtml(__('Vendor Total')); */?>">
                                <?php /*=  $order->formatPrice($block->getOrderedPricebyorder(
                                    $currencyRate,
                                    $sellerItemCost
                                ));*/?>
                            </td>-->
                            <td class="col subtotal" data-th="<?= $escaper->escapeHtml(__('Subtotal')); ?>">
                                <?= /* @noEscape */ $order->formatPrice($block->getOrderedPricebyorder(
                                    $currencyRate,
                                    $rowTotal
                                ));?></td>
                            <?php
                        }?>
                    </tr>
                <?php endforeach; ?>
                <?php
            }?>
            </tbody>

            <?php
        } ?>
        <?php endif;?>
        <tfoot>
        <?php if ($block->isPagerDisplayed()): ?>
            <tr>
                <td colspan="<?= $escaper->escapeHtml($colSpan) ?>"
                    data-block="order-items-pager-bottom"
                    class="order-pager-wrapper order-pager-wrapper-bottom">
                    <?= $block->getPagerHtml() ?>
                </td>
            </tr>
        <?php endif ?>
        <?= $block->getChildHtml('marketplace_order_totals') ?>
        </tfoot>
    </table>
</div>
