<?php

namespace Branch8\HotaiCore\Model\Ticket;

class Reason
{
    const REASON_FOR_OOS_CHECK_BATCH_SETTING_NOT_FOUND = 1;
    const REASON_FOR_OOS_CHECK_OUT_OF_SALE_TIME_WINDOW = 2;
    const REASON_FOR_OOS_CHECK_QUANTITY_NOT_ENOUGH = 3;
    const REASON_FOR_OOS_CHECK_BATCH_SETTING_EXIST_BUT_ZERO_QUANTITY_LEFT = 4;
    const REASON_FOR_OOS_CHECK_PRODUCT_NOT_A_BATCH_IMPORT_TICKET = 98;
    const REASON_FOR_OOS_CHECK_QUANTITY_VIRTUAL_PRODUCT_TYPE_NOT_SUPPORTED = 99;
}