<?php
/** @var $block \Branch8\SellerContactInformation\Block\Adminhtml\Customer\Edit\Tab\DestructionDocument */
$sellerInfo = $block->getSellerInfo();
?>
<?= $block->getGridHtml() ?>
<script>
    require([
        'jquery'
    ], function($){
        $("input[type='file']").attr('form','customer_form');
        $("#marketplace_personal_data_destruction_affidavit").attr('accept','application/pdf, application/msword, .doc, .docx');
        $("#marketplace_personal_data_destruction_certificate").attr('accept','image/*');
    });
</script>