<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Update Cart'); ?>

<?php
// 限購功能 - 使用 ViewModel
$viewModel = \Magento\Framework\App\ObjectManager::getInstance()->get(\Branch8\LimitPurchased\ViewModel\Product\LimitPurchased::class);
$limitPurchasedQty = $viewModel->getMaxAllowedQty($_product);

// 決定是否啟用數量限制 (如果 $limitPurchasedQty 不為 null 且 > 0)
$shouldLimitQty = ($limitPurchasedQty !== null && $limitPurchasedQty >= 0);
?>
<?php if ($_product->isSaleable()) :?>
    <div class="box-tocart update">
        <fieldset class="fieldset">
            <?php if ($block->shouldRenderQuantity()) :?>
            <div class="field qty">
                <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
                <div class="control">
                    <span class="increase down"><?php /* @escapeNotVerified */ echo __('Down') ?></span>
                    <input type="hidden" name="template-version" value="4">
                    <input type="number"
                           name="qty"
                           id="qty"
                           min="0"
                           value=""
                           title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                           class="input-text qty"
                           data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"/>
                    <span class="increase up"><?php /* @escapeNotVerified */ echo __('Up') ?></span>
                </div>
                <?php if ($shouldLimitQty): ?>
                    <div class="limit-qty-text-popup">
                        <?php echo __('A single order for this product (including all its variations) is limited to %1 pieces.', $limitPurchasedQty) ?>
                    </div>
                <?php endif; ?>
            </div>
            <?php endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                        class="action primary tocart"
                        id="product-updatecart-button">
                    <span><?= $block->escapeHtml($buttonTitle) ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </fieldset>
    </div>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "Magento_Catalog/js/validate-product": {}
            }
        }
    </script>

<?php endif; ?>
