<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/* @var \Magento\Wishlist\Block\Link $block */
?>
<li class="link wishlist" data-bind="scope: 'wishlist'">
    <a <?= /* @noEscape */ $block->getLinkAttributes() ?>>
        <span>
            <?= $block->escapeHtml($block->getLabel()) ?>
            <!-- ko if: wishlist().counter -->
            <span data-bind="text: wishlist().counter.replace(/ items?| item?/, '')" class="counter qty"></span>
            <!-- /ko -->
        </span>
    </a>
</li>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "wishlist": {
                        "component": "Magento_Wishlist/js/view/wishlist"
                    }
                }
            }
        }
    }

</script>
