<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Branch8\MarketplaceStaging\Block\CustomOption\Options */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
$productType = $block->getRequest()->getParam('type');
$productId = (int)$block->getRequest()->getParam('id');
$productTypeEdit = $block->getProductType();
$marketplaceStagingHelper = $this->helper('Branch8\MarketplaceStaging\Helper\Data');
$product = $block->getProduct();
$set = $product?->getAttributeSetId();
$set = $block->getRequest()->getParam('set') ?? $set;
$allowedSets = $this->helper(\Webkul\Marketplace\Helper\Data::class)->getAllowedSets();
$hideCustomOptions = false;
$virtualImportSetMap = ['ticket_yoxi', 'ticket_fami', 'ticket_redeem', 'ticket_non_redeem'];
foreach ($allowedSets as $allowedSet) {
    if ($allowedSet['value'] == $set && in_array($allowedSet['label'], $virtualImportSetMap)) {
        $hideCustomOptions = true;
        break;
    }
}
?>

<?php if ($productType != 'grouped' && $productTypeEdit != 'grouped'): ?>
<?php $hint = $marketplaceStagingHelper->getHintHtml('custom_option') ?>
<div class="fieldset-wrapper" id="product-custom-options-wrapper" data-block="product-custom-options"<?php if ($hideCustomOptions): ?> style="display: none;"<?php endif ?>>
    <div class="fieldset-wrapper-title<?php if ($hint): ?> _with-tooltip-top<?php endif ?>">
        <strong class="title">
            <span><?= $block->escapeHtml(__('Custom Options')) ?></span>
        </strong>
        <?= $hint ?>
    </div>
    <div class="fieldset-wrapper-content" id="product-custom-options-content"
         data-role="product-custom-options-content">
        <fieldset class="fieldset">
            <div class="messages">
                <div class="message message-error" id="dynamic-price-warning">
                    <div class="message-inner">
                        <div class="message-content">
                            <?= $block->escapeHtml(__(
                                'We can\'t save custom-defined options for bundles with dynamic pricing.'
                            )) ?></div>
                    </div>
                </div>
                <?= /* @noEscape */ $secureRenderer->renderStyleAsTag("display: none;", '#dynamic-price-warning') ?>
            </div>

            <div id="product_options_container" class="sortable-wrapper">
                <div id="product_options_container_top"></div>
                <?= $block->getOptionsBoxHtml() ?>
            </div>

            <div class="actions">
                <?php if (!$block->isBought()): ?>
                <?= $block->getChildHtml('import_button') ?>
                <?= $block->getAddButtonHtml() ?>
                <?php endif; ?>
                <?= $block->getAddWKButtonHtml() ?>
            </div>
        </fieldset>
    </div>
</div>

<?php $scriptString = <<<script
require(['jquery'], function($){
    var priceType = $('#price_type');
    var priceWarning = $('#dynamic-price-warning');
    if (priceType && priceType.val() == 0 && priceWarning) {
        priceWarning.show();
    }
});
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
<?php endif; ?>
