<?php
/**
 *
 * @category    Branch8
 * @package     Branch8_Blog
 */

use Branch8\Blog\Block\Tag\Widget;
use Magento\Framework\Escaper;

/** @var Widget $block */
/** @var Escaper $escaper */
$tags = $block->getTagList();

if ($tags && $tags->getSize()) : ?>
    <div class="mp-sidebar mpcss">
        <div class="row">
            <div class="block-title col-xs-12 sidebar-tags">
                <p class="block-mp-sidebar-heading" role="heading" aria-level="2"><?= $escaper->escapeHtml(__('Tags')) ?></p>
            </div>
            <div class="col-xs-12">
                <?php foreach ($tags as $tag) : ?>
                    <a class="label label-default tags-list"
                       style="font-size:<?= $escaper->escapeHtmlAttr($block->getTagSize($tag)) . 'px'; ?>"
                       href="<?= $escaper->escapeUrl($block->getTagUrl($tag)) ?>">
                        <?= $escaper->escapeHtml($tag->getName()) ?>
                    </a>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
<?php endif; ?>
