<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Cookie\Block\Html\Notices $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
$b8CustomerHelper = $this->helper(\Branch8\Customer\Helper\Data::class);
?>
<?php
/** @var \Magento\Cookie\Helper\Cookie $cookieHelper */
$cookieHelper = $block->getData('cookieHelper');
if ($cookieHelper->isCookieRestrictionModeEnabled()): ?>
    <div role="alertdialog" aria-label="<?= $block->escapeHtml(__('Allow Cookies')) ?>"
         tabindex="-1"
         class="message global cookie"
         id="notice-cookie-block" style="display: none;">
        <div role="document" class="content" tabindex="0">
            <?= $b8CustomerHelper->getCookieBlock(); ?>
            <div class="actions">
                <button id="btn-cookie-allow" class="action allow primary">
                    <span><?= $block->escapeHtml(__('Allow Cookies')) ?></span>
                </button>
            </div>
        </div>
    </div>
    <script type="text/x-magento-init">
        {
            "#notice-cookie-block": {
                "cookieNotices": {
                    "cookieAllowButtonSelector": "#btn-cookie-allow",
                    "cookieName": "user_checked_cookie",
                    "cookieValue": <?= /* @noEscape */ $cookieHelper->getAcceptedSaveCookiesWebsiteIds() ?>,
                    "cookieLifetime": <?= /* @noEscape */ $cookieHelper->getCookieRestrictionLifetime() ?>,
                    "noCookiesUrl": "<?= $block->escapeJs($block->getUrl('cookie/index/noCookies')) ?>"
                }
            }
        }
    </script>
<?php endif; ?>
