<fieldset>
    <legend><?php echo __('Notification Preview');?></legend>
    <div class="placeholder_notification_title notification_title"><?php echo __('Title');?></div>
    <div id="preview_notification_title" class="notification_title"></div>
    <div class="placeholder_notification_content notification_content"><?php echo __('Content');?></div>
    <div id="preview_notification_content" class="notification_content"></div>
</fieldset>
