<div class="condition_item">
    <div class="clear-action"><div class="close_condition"><span><?php echo __('Close');?></span></div></div>
    <div class="title"><?php echo __('Compound logic');?></div>
    <div class="admin__field field field-condition  required _required">
        <label class="label admin__field-label"><span><?php echo __('Trigger condition');?></span></label>
        <div class="admin__field-control control">
            <select name='condition[<?php echo $this->getData('condKey');?>]' class="condition required-entry">
                <option value="">- - - <?php echo __('Please select');?> - - -</option>
                <?php
                $conditions = $this->getAllConditions();
                $condVal = $this->getData('condVal');
                foreach($conditions as $_cond){
                    $selected = '';
                    if(isset($condVal['condition']) && $_cond['value'] == $condVal['condition']){
                        $selected = 'selected';
                    }
                    echo '<option '.$selected.' value="'.$_cond['value'].'">'.$_cond['label'].'</option>';
                }
                ?>
            </select>
            <div class="note admin__field-note"><?php echo __('If you select "First Purchase Trigger" the limit for users will be "Total Usage Limit per User" and the number of wins for each account during the campaign is 1.');?></div>
        </div>
    </div>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get(\Magento\Store\Model\StoreManagerInterface::class);
$homepageUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
$fields = [];
if($condVal){
    $fields = $condVal['fields'];
}
?>
    <div class="admin__field field field-api_url">
        <label class="label admin__field-label"><span>API URL</span></label>
        <div class="admin__field-control control">
            <input type="text" name="api_url[<?php echo $this->getData('condKey');?>]" value="<?php echo $homepageUrl.'rest/V1/automated-reward-system';?>" disabled readonly/>
        </div>
    </div>
    <div class="admin__field field field-api_key">
        <label class="label admin__field-label"><span>API Key</span></label>
        <div class="admin__field-control control">
            <?php ?>
            <input type="text" name="api_key[<?php echo $this->getData('condKey');?>]" value="<?php echo isset($fields['api_key']) ? $fields['api_key'] :'';?> " disabled readonly />
        </div>
    </div>
    <div class="admin__field field field-url  required _required">
        <label class="label admin__field-label"><span>URL</span></label>
        <div class="admin__field-control control">
            <input type="text" name="url[<?php echo $this->getData('condKey');?>]" value="<?php echo isset($fields['url']) ? $fields['url'] :'';?>" class="required-entry" />
            <?php
            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $storeManager = $objectManager->get(\Magento\Store\Model\StoreManagerInterface::class);
            $baseUrl = $storeManager->getStore()->getBaseUrl();
            $secureBaseUrl = $storeManager->getStore(1)->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB, true);
            ?>
            <div class="note admin__field-note"><?php echo __('Must start with %1', $secureBaseUrl);?></div> 
        </div>
    </div>
    <div class="admin__field field field-first_order_status  required _required">
        <label class="label admin__field-label"><span><?php echo __('Order Status');?></span></label>
        <div class="admin__field-control control">
            <select name="first_order_status[<?php echo $this->getData('condKey');?>]" class="required-entry">
                <option value="">- - - <?php echo __('Please select');?> - - -</option>
                <?php 
                $orderStatuses = $this->getOrderStatusOptions();
                foreach($orderStatuses as $_status){
                    $selectedOrderStatus = '';
                    if(isset($fields['first_order_status']) && $fields['first_order_status'] == $_status['value']){
                        $selectedOrderStatus = 'selected';
                    }
                    echo '<option '.$selectedOrderStatus.' value="'.$_status['value'].'">'.$_status['label'].'</option>';
                }?>
            </select>
        </div>
    </div>
    <div class="admin__field field field-level  required _required">
        <label class="label admin__field-label"><span>Level</span></label>
        <div class="admin__field-control control">
            <select name="to_level[<?php echo $this->getData('condKey');?>]" class="required-entry">
                <option value="">- - - <?php echo __('Please select');?> - - -</option>
                <?php 
                $levels = $this->getCustomerGroupsOptionArray();
                foreach($levels as $_level){
                    $selectedToLevel = '';
                    if(isset($fields['to_level']) && $fields['to_level'] == $_level['value']){
                        $selectedToLevel = 'selected';
                    }
                    echo '<option '.$selectedToLevel.' value="'.$_level['value'].'">'.$_level['label'].'</option>';
                }?>
            </select>
        </div>
    </div>
    <div class="admin__field field field-issue_reward  required _required">
        <label class="label admin__field-label"><span>Issue reward</span></label>
        <div class="admin__field-control control">
            <select name="issue_reward[<?php echo $this->getData('condKey');?>]" class="required-entry issue-reward-validate">
                <?php $issueReward = isset($fields['issue_reward']) ? $fields['issue_reward']: 1;?>
                <option value="1" <?php echo ($issueReward == 1) ? 'selected' : '' ;?>>Yes</option>
                <option value="0" <?php echo ($issueReward == 0) ? 'selected' : '' ;?>>No</option>
            </select>
        </div>
    </div>
    <div class="admin__field field field-is_onetime_trigger  required _required">
        <label class="label admin__field-label"><span>Is One Time Trigger</span></label>
        <div class="admin__field-control control">
            <select name="is_onetime_trigger[<?php echo $this->getData('condKey');?>]" class="required-entry">
                <?php $isOnetimeTrigger = isset($fields['is_onetime_trigger']) ? $fields['is_onetime_trigger'] : 0;?>
                <option value="0" <?php echo ($isOnetimeTrigger == 0) ? 'selected' : '';?>>No</option>
                <option value="1" <?php echo ($isOnetimeTrigger == 1) ? 'selected' : '';?>>Yes</option>
            </select>
        </div>
    </div>
</div>
