<?php 

namespace Branch8\HotaiCore\Model\Item;

use Branch8\HotaiCore\Model\Order\Status;

class FlowStatus {

    const CREDITMEMO_AVAIL_STATUS = [
        STATUS::STATUS_PROCESSING_RETURN_CANCEL_BEFORE_SHIPPING,
        STATUS::STATUS_PROCESSING_RETURN_AND_REFUND,
        STATUS::STATUS_PROCESSING_NOT_RETURN_BUT_REFUND
    ];

    const SELLER_DECLINE_REASON = [
        STATUS::STATUS_APPLYING_REPLACE_REJECT,
        STATUS::STATUS_APPLYING_REPLACE_REVIEW_REJECT,
        STATUS::STATUS_APPLYING_RETURN_REJECT,
        STATUS::STATUS_APPLYING_RETURN_REVIEW_REJECT,
        STATUS::STATUS_FINANCIAL_REVIEW_REJECT,
    ];

    
}