<?php
/** @var $escaper Magento\Framework\Escaper */
?>
<div id="cancel-order-modal-<?=/* @noEscape */ $block->getOrder()->getId() ?>" class="cancel-order-modal-wrapper" >
    <div class="cancel-order-modal-body">
        <form action="/sales/parentOrder/cancelorder" method="post" id="cancel-form-<?=/* @noEscape */ $block->getOrder()->getId() ?>" data-mage-init='{"validation":{}}'>
            <h3><?= $block->escapeHtml(__("Reason for cancellation")) ?></h3>
            <select id="cancel-order-reason-<?=/* @noEscape */ $block->getOrder()->getId() ?>"
                    class="cancel-order-reason required-entry" name="reason" required>
                <option value="" selected disabled hidden><?= __('Select Reason') ?></option>
                <?php foreach ($block->getReasons() as $key => $description): ?>
                    <option value="<?= $escaper->escapeHtml(__($description)) ?>">
                        <?= $escaper->escapeHtml(__($description)) ?>
                    </option>
                <?php endforeach; ?>
            </select>
            <input type="hidden" value="<?=/* @noEscape */ $block->getOrder()->getId() ?>" name="order_id" />
            <textarea id="cancel-order-reason-description-<?=/* @noEscape */ $block->getOrder()->getId() ?>"
                      maxlength="20"
                      name="reason_description"
                      class="cancel-order-reason-description"
                      placeholder="<?= $escaper->escapeHtml(__("Please describe the reason, limited to 20 words (optional)")) ?>"></textarea>
            <div class="custom-notice">
                <p><?= $escaper->escapeHtml(__("Things to note")) ?></p>
                <ol>
                    <li><?= $block->escapeHtml(__('Orders can be canceled before 23:59 today.')) ?></li>
                    <li><?= $block->escapeHtml(__('After the application is cancelled, Hotai Points will return the points to the original account 30 minutes later.')) ?></li>
                </ol>
            </div>
        </form>
    </div>
</div>



