<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Branch8\MarketPlaceParentOrderFrontendUi\Block\ParentOrder\Info */ ?>
<?php
$_order = $block->getOrder();
$allowedAddressHtmlTags = ['b', 'br', 'em', 'i', 'li', 'ol', 'p', 'strong', 'sub', 'sup', 'ul'];
?>
<div class="block block-order-details-view">
    <div class="block-title">
        <strong><?= $block->escapeHtml(__('Order Information')) ?></strong>
    </div>
    <div class="block-content">
        <?php if (!$_order->isVirtual()) : ?>
            <div class="box box-order-shipping-address">
                <strong class="box-title"><span><?= $block->escapeHtml(__('Shipping Address')) ?></span></strong>
                <div class="box-content">
                    <address><?= $block->escapeHtml($block->getFormattedAddress($_order->getShippingAddress()), $allowedAddressHtmlTags) ?></address>
                </div>
            </div>

            <div class="box box-order-shipping-method">
                <strong class="box-title">
                    <span><?= $block->escapeHtml(__('Shipping Method')) ?></span>
                </strong>
                <div class="box-content">
                <?php if ($_order->getDetail()->getShippingDescription()) : ?>
                    <?= $block->escapeHtml($_order->getDetail()->getShippingDescription()) ?>
                <?php else : ?>
                    <?= $block->escapeHtml(__('No shipping information available')) ?>
                <?php endif; ?>
                </div>
            </div>
        <?php endif; ?>

        <div class="box box-order-billing-address">
            <strong class="box-title">
                <span><?= $block->escapeHtml(__('Billing Address')) ?></span>
            </strong>
            <div class="box-content">
                <address><?= $block->escapeHtml($block->getFormattedAddress($_order->getBillingAddress()), $allowedAddressHtmlTags) ?></address>
            </div>
        </div>
        <div class="box box-order-billing-method">
            <strong class="box-title">
                <span><?= $block->escapeHtml(__('Payment Method')) ?></span>
            </strong>
            <div class="box-content">
                <?= $block->getPaymentInfoHtml() ?>
            </div>
        </div>
    </div>
</div>
