<?php
/**
 * @var \Branch8\WebkulMpBuyerSellerChatCustomerUi\Block\Customer\AbstractChatBlock\FullScreenChat $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

?>

<div data-role="customer-minichat-wrapper"  class="customer-minichat-wrapper"
     data-bind="scope:'customerMiniChat'">
<!-- ko template: getTemplate() --><!-- /ko -->
    <?php // phpcs:ignore Magento2.Legacy.PhtmlTemplate ?>
    <script type="text/x-magento-init">
        {
            "[data-role='customer-minichat-wrapper']": {
                "Magento_Ui/js/core/app": <?= $block->getJsLayout() ?>
        }
    }
    </script>
</div>
