<?php
/**
 * @var $block Branch8\Rma\Block\Seller\Rma
 * @var $rmaModel \Branch8\Rma\ViewModel\Rma
 */
?>
<?php
$helper = $block->helper();
$rmaDetails = $block->helper()->getRmaDetails();
$orderRef = $rmaDetails->getOrderRef();
$orderId = $rmaDetails->getOrderId();
$order = $block->helper()->getOrder($orderId);
$rmaId = $rmaDetails->getId();
$images = $block->helper()->getImages($rmaId);
$sellerId = $rmaDetails->getSellerId();
$date = $rmaDetails->getCreatedDate();
$conversations = $block->getAllConversations();
$date = $block->formatDate($date, \IntlDateFormatter::MEDIUM, true);
$sellerName = $block->helper()->getCustomerName($rmaId, true);
$customerName = $block->helper()->getCustomerName($rmaId, false);
$status = $rmaDetails->getStatus();
$finalStatus = $rmaDetails->getFinalStatus();
$resolutionType = $rmaDetails->getResolutionType();
$rmaStatus = $block->helper()->getAdminAndSellerPanelRmaStatusTitle($status);
$sellerStatus = $block->helper()->getSellerStatusTitle($rmaDetails->getSellerStatus());
$orderStatus = $block->helper()->getOrderStatusTitle($rmaDetails->getOrderStatus());
$resolution = $block->helper()->getResolutionTypeTitle($resolutionType);
$productDetails = $block->helper()->getRmaProductDetails($rmaId);
$totalPrice = 0;
$totalPric = 0;
$totalPoint = 0;
$totalRefundableShippingFee = (int) $order->getShippingInclTax() - (int)$order->getShippingRefunded() - (int)$order->getShippingTaxRefunded();
$orderUrl = $block->getUrl("marketplace/order/view/") . "id/" . $orderId;
$invoiceId = $block->helper()->getMpOrder($orderId, $sellerId)->getInvoiceId();
$invoice = $block->helper()->getInvoiceData($invoiceId);
$rmaItemId = $block->helper()->getRmaItems($rmaId)->getItemId();
$rmaRefundQty = $block->helper()->getRmaItems($rmaId)->getQty();
$senderType = $block->helper()->encrypt('1');
$canRefundStatus = $block->canRefund($status);
$shippingMethod = $order->getShippingMethod();
$canReturnStock = true;
foreach ($productDetails as $product) {
    $isQtyReturned = $product->getIsQtyReturned();
    $totalPric += $block->helper()->getItemFinalPrice($product);
    $returnStockAvailCheck = $block->canReturnStock($product->getItemId());
    if ($returnStockAvailCheck == false) {
        $canReturnStock = false;
    }
}

$isTicket = $block->isTicket($rmaItemId);
$allStatus = $block->getAllNextStatusOptions($status, $isTicket, $rmaDetails->getIsReplaceAgain());
$readyToBeShipped = $block->isReadyToBeShipped($status);

$rmaModel = $block->getRmaModel();
$canshowShippingForm=$rmaModel->canShowShippingForm($rmaDetails);
$reasonsToDecline = $rmaModel->getAllReasonsForDecline();
$declineReasonId = $rmaDetails->getDeclineReasonId();
$b8salesConfigHelper = $block->getB8salesConfigHelper();
$memo = $block->helper()->getCreditMemoForRmaDetail($rmaDetails);
$alertStatus = [
     \Branch8\Rma\Model\Rma\Status::REPLACE_REVIEW_PROCESSING,
     \Branch8\Rma\Model\Rma\Status::REPLACE_SHIPPING_ARRIVED,
    \Branch8\Rma\Model\Rma\Status::RETURN_REVIEW_PROCESSING
];
?>
<div class="wk-mprma-container wk-mprma-view">
<a href="<?=$escaper->escapeUrl($block->getUrl('mprmasystem/seller/allrma'));?>"
    class="wk-date-info" ><?=$escaper->escapeHtml(__("Back"));?></a>
<a class="wk-date-info" aria-hidden="true" target="_blank" title="<?=$escaper->escapeHtml(__('Print Rma'))?>" href = "<?=$escaper->escapeUrl($block->getUrl(
                        'mprmasystem/customer/printpdf/',
                        [
                            'rma_id' => $rmaId,
                            '_secure' => $block->getIsSecure(),
                        ]
                    ))?>"
    login-url = "<?=$escaper->escapeUrl($block->getUrl('customer/account/login'));?>">
<?=$escaper->escapeHtml(__('Print Rma'))?>

</a>
    <div class="wk-title">
        <?=$escaper->escapeHtml(__("RMA Details"));?>
        <span class="wk-date-info"><?=$escaper->escapeHtml($date);?></span>
    </div>
    <form method="post"
        action="<?=$escaper->escapeUrl($block->getUrl('mprmasystem/customer/create'));?>"
        id="wk_new_rma_form" enctype="multipart/form-data" data-mage-init='{"validation":{}}'>
        <fieldset class="fieldset wk-mprma-fieldset">
            <div class="field">
                <label for="Ordrer Id" class="label">
                    <span><?=$escaper->escapeHtml(__("Order Id"));?></span>
                </label>
                <div class="control">
                    <a target="_blank"
                        href="<?=$escaper->escapeUrl($orderUrl);?>">
                        <?=$escaper->escapeHtml($orderRef);?>
                    </a>
                </div>
            </div>
            <div class="field">
                <label for="Status" class="label">
                    <span><?=$escaper->escapeHtml(__("Rma Status"));?></span>
                </label>
                <div class="control">
                    <div class="wk-row">
                        <span><?=$escaper->escapeHtml(__("RMA Processing Status"));?> :</span>
                        <?=$escaper->escapeHtml($rmaStatus);?>
                    </div>
                    <?php if($declineReasonId):?>
                        <div class="wk-row">
                            <span><?=$escaper->escapeHtml(__("RMA Decline Reason"));?> :</span>
                            <?=$escaper->escapeHtml($block->helper()->getReasonById($declineReasonId));?>
                        </div>
                        <div class="wk-row">
                            <span><?=$escaper->escapeHtml(__("RMA Decline Reason Details"));?> :</span>
                            <?=$escaper->escapeHtml($rmaDetails->getDeclineReasonDetail());?>
                        </div>
                    <?php endif;?>
                </div>
            </div>
            <div class="field">
                <label for="Rma Application Content" class="label">
                    <span><?=$escaper->escapeHtml(__("Rma Application Content"));?></span>
                </label>
                <div class="control">
                    <?= $block->getChildHtml('switch_resolution') ?>

                    <div class="wk-row">
                        <span><?= $escaper->escapeHtml(__("Customer Has Received Goods Or Not")); ?> :</span>
                        <?= $escaper->escapeHtml($orderStatus); ?>
                    </div>
                </div>
            </div>
            <?php if ($resolutionType == \Webkul\MpRmaSystem\Helper\Data::RESOLUTION_REFUND): ?>
                <div class="field wk-refund-block wk-display-none">
                    <label for="Refund Details" class="label">
                        <span><?= $escaper->escapeHtml(__("Refund Details")); ?></span>
                    </label>
                    <div class="control">
                        <div class="wk-row">
                            <span><?= $escaper->escapeHtml(__("Refundable Amount")); ?> :</span>
                            <span class="wk-refundable-amount"></span>
                            <?php if ($shippingMethod == "mpfixrate_mpfixrate") { ?>
                                <span><?= $escaper->escapeHtml(__("+ Shipping")); ?></span>
                            <?php } ?>
                        </div>
                        <div class="wk-row">
                            <span><?= $escaper->escapeHtml(__("Refundable Point")); ?> :</span>
                            <span class="wk-refundable-point"></span>
                        </div>
                        <?php if ($rmaDetails->getRefundedAmount() > 0): ?>
                            <div class="wk-row">
                                <span><?= $escaper->escapeHtml(__("Refunded Amount")); ?> :</span>
                                <span class="wk-refunded-amount">
                                    <?= /* @noEscape */
                                    $order->formatPrice($rmaDetails->getRefundedAmount()); ?>
                                </span>
                            </div>
                        <?php endif; ?>
                        <?php if ($rmaDetails->getRefundedPoint() > 0): ?>
                            <div class="wk-row">
                                <span><?= $escaper->escapeHtml(__("Refunded Point")); ?> :</span>
                                <span class="wk-refunded-amount">
                                    <?= /* @noEscape */
                                    $rmaDetails->getRefundedPoint() ?>
                                </span>
                            </div>
                        <?php endif; ?>
                        <?php if ($memo && $memo->getShippingInclTax() > 0): ?>
                            <div class="wk-row">
                                <span><?= $escaper->escapeHtml(__("Refunded Shipping")); ?> :</span>
                                <span class="wk-refunded-amount"><?= $order->formatPrice((int)$memo->getShippingInclTax()); ?></span>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
            <?php endif; ?>
            <div class="field wk-shipping-block">
                <label for="Shipping Details" class="label">
                    <span><?= $escaper->escapeHtml(__("RMA Shipping Details")); ?></span>
                </label>
                <div class="control">
                    <div class="wk-row">
                        <span><?= $escaper->escapeHtml(__("RMA Shipping Receiver")); ?> :</span>
                        <?= $escaper->escapeHtml($rmaDetails->getRmaReceiver()); ?>
                    </div>
                    <div class="wk-row">
                        <span><?= $escaper->escapeHtml(__("RMA Shipping Phone")); ?> :</span>
                        <?= $escaper->escapeHtml($rmaDetails->getRmaPhone()); ?>
                    </div>
                    <div class="wk-row">
                        <span><?= $escaper->escapeHtml(__("RMA Shipping Delivery Time")); ?> :</span>
                        <?= $escaper->escapeHtml($block->getRmaDeliveryTime($rmaDetails->getRmaDeliveryTime())); ?>
                    </div>
                    <div class="wk-row">
                        <span><?= $escaper->escapeHtml(__("RMA Shipping Address")); ?> :</span>
                        <?= $escaper->escapeHtml($rmaDetails->getRmaAddress()); ?>
                    </div>
                    <div class="wk-row">
                        <span><?= $escaper->escapeHtml(__("Return/Exchange Reason")); ?> :</span>
                        <?= $rmaDetails->getRmaReason()? $escaper->escapeHtml($rmaDetails->getRmaReason()):'N/A'; ?>
                        <?php if ($rmaDetails->getData('rma_reason_additional_info')): ?>
                            (<small><?= $escaper->escapeHtml($rmaDetails->getData('rma_reason_additional_info')) ?></small>)
                        <?php endif ?>
                    </div>
                </div>
            </div>
        </fieldset>
    </form>
</div>
<div class="wk-mprma-container wk-mprma-view">
    <div class="wk-title">
        <?=$escaper->escapeHtml(__("Item(s) Requested for RMA"));?>
    </div>
    <div class="wk-table-wrapper">
        <table id="mprma-items-table" class="data table">
            <thead>
                <tr>
                    <th class="col" scope="col"><?=$escaper->escapeHtml(__("Product Name"));?></th>
                    <th class="col" scope="col"><?=$escaper->escapeHtml(__("Sku"));?></th>
                    <th class="col" scope="col"><?=$escaper->escapeHtml(__("Product Price"));?></th>
                    <th class="col" scope="col"><?=$escaper->escapeHtml(__("Qty"));?></th>
                    <th class="col" scope="col"><?=$escaper->escapeHtml(__("Reason"));?></th>
                    <th class="col" scope="col"><?=$escaper->escapeHtml(__("Additional Info"));?></th>
                </tr>
            </thead>
            <?php foreach ($productDetails as $product): ?>
                <?php
                    $totalPrice += $block->helper()->getItemFinalPrice($product);
                    $totalPoint += $block->helper()->getItemFinalPoint($product);
                ?>
                <tbody>
                    <tr>
                        <td class="col">
                            <?=$escaper->escapeHtml($product->getName());?>
                            <?=/* @noEscape */$block->helper()->getOptionsHtml($product);?>
                        </td>
                        <td class="col"><?=$escaper->escapeHtml($product->getSku());?></td>
                        <td class="col"><?=/* @noEscape */$order->formatPrice($product->getData("price_incl_tax"));?></td>
                        <td class="col"><?=$escaper->escapeHtml($product->getQty());?></td>
                        <td class="col"><?=$escaper->escapeHtml($block->helper()->getReasonById($product->getReasonId()));?>
                        <td class="col"><?=$escaper->escapeHtml($rmaDetails->getAdditionalInfo());?>
                        </td>
                    </tr>
                </tbody>
            <?php endforeach;?>
        </table>
    </div>
</div>

<?php if ($allStatus): ?>
<div class="wk-mprma-container wk-mprma-view">
    <div class="wk-title wk-close-title">
        <?=$escaper->escapeHtml(__("Change RMA Status"));?>
    </div>
    <fieldset class="fieldset wk-mprma-fieldset wk-close-filedset">
        <div class="field">
            <?php if ($finalStatus == 0): ?>
                <form method="post"
                    action="<?=$escaper->escapeUrl($block->getUrl('reqrma/rma/change'));?>"
                        id="wk_rma_close_form" enctype="multipart/form-data"
                        data-mage-init='{"validation":{}}'>
                    <input type="hidden" value="<?=$escaper->escapeHtml($block->helper()->encrypt($rmaId));?>" name="rma_id">
                    <div class="control">
                        <div class="field required">
                            <div class="wk-action-content">
                                <select id="changed_status" name="changed_status"
                                        data-validate="{required:true}"
                                        class="input-text required-entry"
                                        data-role="changed-status"
                                >
                                    <?php foreach ($allStatus as $key => $status): ?>
                                        <option value="<?= $escaper->escapeHtml($key); ?>">
                                            <?= $escaper->escapeHtml(__($status)); ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                            <?php if (in_array($key, $alertStatus)): ?>
                                <div>
                                    <span style="font-style:oblique;Color:red;"><?php echo $escaper->escapeHtml(__('Press the button to skip shipping to customer stage.'));?></span>
                                </div>
                            <?php endif;?>
                        </div>
                        <div class="wk-action-content" data-role="decline-reasons-wrapper"
                             style="display: none">
                            <div class="field required">
                                <div class="control">
                                    <label for="decline_reasons" class="label"><?=__('Decline Reason:')?></label>
                                    <select id="decline_reasons" name="decline_reason_id"
                                            data-validate="{required:true}"
                                            class="input-text required-entry"
                                            data-group="decline-field"
                                    >
                                        <option value=""><?= __('Please select') ?></option>
                                        <?php foreach ($reasonsToDecline as $key => $reason): ?>
                                            <option value="<?= $escaper->escapeHtml($key); ?>">
                                                <?= $escaper->escapeHtml($reason); ?>
                                            </option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                            </div>
                            <div class="field required">
                                <div class="control">
                                    <label for="decline_reason_detail" class="label"><?=__('Decline Reason Detail:')?></label>
                                    <textarea name="decline_reason_detail" data-validate="{required:true}"
                                          class="wk-rma-msg input-text required-entry
                                    validate-no-html-tags"      data-group="decline-field"></textarea>
                                </div>
                            </div>
                        </div>
                        <div class="wk-action-btn">
                            <button title="Save" class="action save primary wk-save" type="submit">
                                <span><?=$escaper->escapeHtml(__("Save"));?></span>
                            </button>
                        </div>
                    </div>
                </form>

            <?php else: ?>
                <?=$escaper->escapeHtml($block->helper()->getCloseRmaLabel($finalStatus, $sellerName));?>
            <?php endif;?>
        </div>
    </fieldset>
</div>
<?php endif;?>

<?php if ($readyToBeShipped && $canshowShippingForm): ?>
<div class="wk-mprma-container wk-mprma-view">
    <div class="wk-title wk-close-title">
        <?=$escaper->escapeHtml(__("Shipping Number"));?>
    </div>
    <fieldset class="fieldset wk-mprma-fieldset wk-close-filedset">
        <div class="field">
            <?php if ($finalStatus == 0): ?>
                <form method="post"
                    action="<?=$escaper->escapeUrl($block->getUrl('reqrma/rma/shipping'));?>"
                        id="wk_rma_close_form" enctype="multipart/form-data"
                        data-mage-init='{"validation":{}}'>
                    <input type="hidden" value="<?=$escaper->escapeHtml($block->helper()->encrypt($rmaId));?>" name="rma_id">
                    <div class="shipping-info">
                        <select name="shipping_carrier"
                                id="shipping_carrier"
                                class="select admin__control-select number-title required-entry wk-mprma-shipping-tracking-carrier">
                            <option value=""><?= $escaper->escapeHtml(__('-- Please Select --'))?></option>
                            <?php foreach ($b8salesConfigHelper->getLogisticsCompanies() as $name => $url):?>
                                <option value="<?= $escaper->escapeHtml($name) ?>" data-url="<?= $escaper->escapeHtml($url) ?>">
                                    <?= $escaper->escapeHtml($name) ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                        <input type="text" name="logistics_provider_name" class="input-text wk-mprma-shipping-tracking-logistics-name"
                               placeholder="<?= /* @noEscape */ __("Logistics Provider's Name") ?>" style="display:none;">
                        <input type="text" name="shipping_number" class="required-entry" placeholder="<?= __('Tracking number')?>">
                    </div>
                    <div class="control">
                        <div class="wk-action-btn">
                            <button title="Save" class="action save primary wk-save" type="submit">
                                <span><?=$escaper->escapeHtml(__("Save"));?></span>
                            </button>
                        </div>
                    </div>
                </form>
            <?php else: ?>
                <?=$escaper->escapeHtml($block->helper()->getCloseRmaLabel($finalStatus, $sellerName));?>
            <?php endif;?>
        </div>
    </fieldset>
</div>
<?php endif;?>

<?php if ($canRefundStatus): ?>
        <div class="wk-mprma-container wk-mprma-view">
            <div class="wk-title wk-close-title">
                <?=$escaper->escapeHtml(__("Refund Amount"));?>
            </div>
            <form method="post"
                action="<?=$escaper->escapeUrl($block->getUrl('reqrma/rma/refund'));?>"
                id="wk_rma_refund_form" enctype="multipart/form-data"
                data-mage-init='{"validation":{}}'>
                <input type="hidden" value="<?=$escaper->escapeHtml($block->helper()->encrypt($rmaId));?>" name="rma_id">
                <input type="hidden" value="1" class="payment_status" name="do_offline">
                <input type="hidden" name="invoice_id" value="<?=$escaper->escapeHtml($invoiceId);?>">
                <input type="hidden" name="id" value="<?=/* @noEscape */$orderId?>">
                <input type="hidden" name="creditmemo[adjustment_positive]" value="0">
                <input type="hidden" name="creditmemo[adjustment_negative]" value="0">
                <input type="hidden" name="total_refundable_shipping_amount" value="<?=$totalRefundableShippingFee?>">
                <input type="hidden"
                    name="creditmemo[items][<?=/* @noEscape */$escaper->escapeHtml($rmaItemId);?>][qty]"
                    value="<?=/* @noEscape */$escaper->escapeHtml($rmaRefundQty);?>">
                <fieldset class="fieldset wk-mprma-fieldset wk-close-filedset">
                    <div class="field">
                        <label for="Payment Type" class="label">
                            <span><?=$escaper->escapeHtml(__("Payment Type"));?></span>
                        </label>
                        <div class="control">
                            <select id="payment_type" name="payment_type"
                                data-validate="{required:true}" class="input-text required-entry">
                                <option value="1" ><?=$escaper->escapeHtml(__("Full Amount"));?></option>
                                <option value="2" ><?=$escaper->escapeHtml(__("Partial Amount"));?></option>
                            </select>
                            <div class="wk-partial-amount">
                                <input type="text" value="0" id="partial_amount"
                                    name="partial_amount" data-validate="{required:true}"
                                    class="input-text required-entry">
                            </div>
                        </div>
                        <div class="wk-refund-note">
                            <span class="wk-refund-label">
                                <?=$escaper->escapeHtml(__("Total Refundable Amount"));?> :
                            </span>
                            <span class="wk-refund-amount"></span>
                            <?php if ($shippingMethod == "mpfixrate_mpfixrate") {?>
                                    <span><?=$escaper->escapeHtml(__("+ Shipping"));?></span>
                            <?php }?>
                        </div>
                        <div class="wk-refund-note">
                            <span class="wk-refund-label">
                                <?=$escaper->escapeHtml(__("Total Refundable Point"));?> :
                            </span>
                            <span class="wk-refund-point"></span>
                        </div>
                        <?php if ($canReturnStock) :?>
                            <div class="wk-refund-note">
                                <span class="wk-refund-label">
                                    <?=$escaper->escapeHtml(__("Return to Stock"));?> :
                                </span>
                                <span class=""><input type="checkbox" name="back_to_stock" value="1"></span>
                            </div>
                        <?php endif;?>

                        <div class="wk-action-btn wk-refund-button">
                            <button title="Refund Offline"
                                class="action save primary wk-refund"
                                id="wk-refund-offline" type="submit">
                                <span><?=$escaper->escapeHtml(__("Refund Offline"));?></span>
                            </button>
                        </div>
                        <?php if ($invoice && $invoice->getTransactionId()) {?>
                        <div class="wk-action-btn">
                            <button title="Refund Online"
                                class="action save primary wk-refund"
                                id="wk-refund-online" type="submit">
                                <span><?=$escaper->escapeHtml(__("Refund"));?></span>
                            </button>
                        </div>
                        <?php }?>
                    </div>
                </fieldset>
            </form>
        </div>
<?php endif;?>

<?php if ($conversations->getSize()): ?>
    <div class="wk-mprma-container wk-mprma-view">
        <div class="wk-title">
            <?=$escaper->escapeHtml(__("Conversations"));?>
        </div>
        <?php foreach ($conversations as $conversation): ?>
            <?php
                $date = $conversation->getCreatedTime();
                $date = $block->formatDate($date, \IntlDateFormatter::MEDIUM, true);
                $type = $conversation->getSenderType();
                if ($type == 1) {
                    $text = __("Seller") . " : " . $sellerName;
                    $class = "wk-mprma-seller-section";
                } elseif ($type == 2) {
                    $text = __("Customer") . " : " . $customerName;
                    $class = "wk-mprma-customer-section";
                } elseif ($type == 3) {
                    $text = __("Guest");
                    $class = "wk-mprma-customer-section";
                } else {
                    $text = __("Administrator");
                    $class = "wk-mprma-admin-section";
                }
            ?>
            <div class="wk-mprma-conversation">
                <div class="wk-mprma-conversation-head <?=$escaper->escapeHtml($class);?>">
                    <div class="wk-mprma-conversation-head-left">
                        <?=$escaper->escapeHtml($date);?>
                    </div>
                    <div class="wk-mprma-conversation-head-right">
                        <?=$escaper->escapeHtml($text);?>
                    </div>
                </div>
                <div class="wk-mprma-conversation-body">
                    <?=$escaper->escapeHtml(__($conversation->getMessage()));?>
                </div>
            </div>
        <?php endforeach;?>
        <?php if ($block->getPagerHtml()): ?>
            <div class="order-products-toolbar toolbar bottom"><?=/* @noEscape */$block->getPagerHtml();?></div>
        <?php endif?>
    </div>
<?php endif?>
<div class="wk-mprma-container wk-mprma-view">
    <div class="wk-title">
        <?=$escaper->escapeHtml(__("Send Message"));?>
    </div>
    <form method="post"
        action="<?=$escaper->escapeUrl($block->getUrl('mprmasystem/rma/conversation'));?>"
        id="wk_rma_conversation_form" data-mage-init='{"validation":{}}'>
        <input type="hidden" value="<?=$escaper->escapeHtml($senderType);?>" name="sender_type">
        <input type="hidden" value="<?=$escaper->escapeHtml($block->helper()->encrypt($rmaId));?>" name="rma_id">
        <fieldset class="fieldset wk-mprma-fieldset wk-close-filedset">
            <div class="field required">
                <label for="Enter Message" class="label">
                    <span><?=$escaper->escapeHtml(__("Enter Message"));?></span>
                </label>
                <div class="control">
                    <textarea name="message" data-validate="{required:true}"
                        class="wk-rma-msg input-text required-entry
                        validate-no-html-tags"></textarea>
                </div>
                <div class="wk-action-btn">
                    <button title="Save" class="action save primary wk-send" type="submit">
                        <span><?=$escaper->escapeHtml(__("Send Message"));?></span>
                    </button>
                </div>
            </div>
        </fieldset>
    </form>
</div>
<?php
$data = $block->helper()->jsonEncodeData([
    "totalPrice" => $totalPrice,
    "totalPriceWithCurrency" => $order->formatPrice($totalPrice),
    "errorMsg" => __("The amount you entered cannot exceed the refundable amount. %1", $order->formatPrice($totalPrice)),
    "warningLable" => __("Warning"),
    "totalPoint" => $totalPoint,
    "totalRefundableShippingFee" => $order->formatPrice($totalRefundableShippingFee),
    "RmaDeclineStatus" => $rmaModel->getDeclineRmaStatuses()
]);
?>
<script type="text/x-magento-init">
    {
        "body": {
            "Branch8_Rma/js/rma": <?=/* @noEscape */$data?>
        }
    }
</script>

<script type="text/javascript">
    require([
        'jquery'
    ], function($) {
        $(document).ready(function() {
            $('#shipping_carrier.wk-mprma-shipping-tracking-carrier').on('change', function() {
                if ($(this).val() === '其他：自行填寫名稱') {
                    $('.wk-mprma-shipping-tracking-logistics-name').show().addClass('required-entry');
                } else {
                    $('.wk-mprma-shipping-tracking-logistics-name').hide().removeClass('required-entry');
                }
            });
            $("#wk_rma_refund_form").on('submit', function () {
                // prevent duplicate form submissions
                $(this).find(":submit").attr('disabled', 'disabled');
            });
            $("#wk_rma_close_form").on('submit', function () {
                // prevent duplicate form submissions
                $(this).find(":submit").attr('disabled', 'disabled');
            });
        });
    });
</script>
