<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product view template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Description
 */
?>
<?php
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$_product = $block->getProduct();

if (!$_product instanceof \Magento\Catalog\Model\Product) {
    return;
}

$_call = $block->getAtCall();
$_code = $block->getAtCode();
$_className = $block->getCssClass();
$_attributeLabel = $block->getAtLabel();
$_attributeType = $block->getAtType();
$_attributeTitle = $block->getTitle();
$_attributeAddAttribute = $block->getAddAttribute();

$renderLabel = true;
// if defined as 'none' in layout, do not render
if ($_attributeTitle == 'none') {
    $renderLabel = false;
}

if ($_attributeLabel && $_attributeLabel == 'default') {
    $_attributeLabel = $_product->getResource()->getAttribute($_code)->getStoreLabel();
}
if ($_attributeType && $_attributeType == 'text') {
    $_attributeValue = ($_helper->productAttribute($_product, $_product->$_call(), $_code))
        ? $_product->getAttributeText($_code)
        : '';
} else {
    $_attributeValue = $_product->$_call();
}
$jsonLoader = $this->getViewFileUrl('images/animation-onboard.json');
?>

<?php if ($_attributeValue) :?>
<div class="product attribute <?= $block->escapeHtmlAttr($_className) ?>">
    <div class="content" <?= /* @noEscape */ $_attributeAddAttribute ?>>
        <?php if ($renderLabel) :?>
            <h6 class="title"><?= $block->escapeHtml($_attributeTitle) ?></h6>
        <?php endif; ?>
        <?= /* @noEscape */ $_attributeValue ?>
    </div>
    <div class="onboard-icon">
        <dotlottie-player class="player" src="<?= $jsonLoader ?>" background="transparent" speed="1" direction="1" playMode="normal" loop autoplay style="width: 200px; height: auto;"></dotlottie-player>
    </div>
</div>
<?php endif; ?>
