<?php
/**
 *
 * @category    Branch8
 * @package     Branch8_Blog
 */

use Branch8\Blog\Block\Topic\Widget;
use Magento\Framework\Escaper;

/** @var Widget $block */
/** @var Escaper $escaper */
$topics = $block->getTopicList();
if ($topics && $topics->getSize()) : ?>
    <div class="mp-sidebar mpcss">
        <div class="row">
            <div class="block-title col-xs-12 sidebar-categories">
                <p class="block-mp-sidebar-heading" role="heading" aria-level="2"><?= $escaper->escapeHtml(__('Topics')) ?></p>
            </div>
            <div class="col-xs-12">
                <ul class="block-content menu-categories">
                    <?php foreach ($topics as $topic) : ?>
                        <li class="category-item">
                            <a class="list-categories" href="<?= $escaper->escapeUrl($block->getTopicUrl($topic)) ?>">
                                <i class="fa fa-folder-o" aria-hidden="true">&nbsp;</i>
                                <?= $escaper->escapeHtml(ucfirst($topic->getName())) ?>
                            </a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
<?php endif; ?>
