<?php
/**
 *
 * @category    Branch8
 * @package     Branch8_Blog
 */

use Branch8\Blog\Block\Sidebar\Search;
use Magento\Framework\Escaper;

/** @var Search $block */
/** @var Escaper $escaper */
?>
<style>
    .sidebar.sidebar-main:before {
        content: unset;
    }
</style>
<div class="blog-search">
    <div class="field search">
        <label class="label" for="blog-search-box" data-role="minisearch-label">
            <span><?= $escaper->escapeHtml(__('Search')) ?></span>
        </label>
        <div class="control">
            <input id="blog-search-box"
                   type="text"
                   name="query"
                   value="<?= $escaper->escapeHtmlAttr($block->getRequest()->getParam('query')) ?>"
                   placeholder="<?= $escaper->escapeHtmlAttr(__('Search blogs here...')) ?>"
                   class="input-text"
                   role="combobox"
                   aria-haspopup="false"
                   aria-autocomplete="both"
            />
        </div>
    </div>
    <div class="actions">
        <button type="submit" title="<?= $escaper->escapeHtmlAttr(__('Search')) ?>" class="action search">
            <i class="fa fa-search" aria-hidden="true" style="font-size: 16px;margin-top: 5px;"></i>
        </button>
    </div>
</div>
<script>
    require(['jquery', 'mpDevbridgeAutocomplete'], function ($) {
        var visibleImage = <?= /** @noEscape */ $block->getSidebarConfig('search/show_image') ?>;

        $('#blog-search-box').autocomplete({
            lookup: <?= /** @noEscape */ $block->getSearchBlogData() ?>,
            lookupLimit: <?= $block->getSidebarConfig('search/search_limit') ?: 10; ?>,
            maxHeight: 2000,
            minChars: <?= $block->getSidebarConfig('search/min_chars') ?: 1; ?>,
            autoSelectFirst: true,
            showNoSuggestionNotice: true,
            triggerSelectOnValidInput: false,
            onSelect: function (suggestion) {
                window.location.href = suggestion.url;
            },
            formatResult: function (suggestion, currentValue) {
                var additionClass = '',
                    html          = "<div class='blog-suggestion'>";

                if (visibleImage) {
                    html += "<div class='blog-suggestion-left'><img class='img-responsive' src='" + suggestion.image + "' /></div>";
                    additionClass = 'image-visible';
                }

                html += "<div class='blog-suggestion-right " + additionClass + "'>" +
                    "<div class='blog-product-line blog-product-name'>" + suggestion.value + "</div>" +
                    "<div class='blog-product-des'><p class='blog-short-des'>" + suggestion.desc + "</p></div></div></div>";

                return html;
            }
        });
    });
</script>
