<?php
/** @var \Branch8\MicrosoftClarity\Block\SellerScript $block */
$userId = $block->getSellerId();
$email = $block->getSellerEmail();
$role = "seller";
$clarityCode = $block->getClarityCode();
if ($block->isSellerBoard() && $clarityCode): ?>
<script type="text/javascript">     
    (function(c,l,a,r,i,t,y){         
        c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)}; 
        
        c[a]("set", "user_id", "<?= $block->escapeHtml($userId) ?>");
        c[a]("set", "email", "<?= $block->escapeHtml($email) ?>");
        c[a]("set", "role", "<?= $block->escapeHtml($role) ?>");

        t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;         
        y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);     
    })(window, document, "clarity", "script", "<?= $block->escapeHtml($clarityCode) ?>"); 
     // custom data（after script loaded）
    if(typeof clarity === "undefined") {
        console.error("Clarity script not loaded");
    } else {
        clarity("set", "user_id", "<?= $block->escapeHtml($userId) ?>");
        clarity("set", "email", "<?= $block->escapeHtml($email) ?>");
        clarity("set", "role", "<?= $block->escapeHtml($role) ?>");
    }
</script>
<?php endif; ?>