<?php
namespace Branch8\MarketPlaceParentOrderFrontendUi\Block\ParentOrder\SubOrderItem;

use Branch8\MarketPlaceParentOrderFrontendUi\Block\ParentOrder\SubOrderItems;
use Magento\Catalog\Api\ProductRepositoryInterface;
use Magento\Catalog\Helper\Image;
use Magento\Catalog\Helper\ImageFactory;
use Magento\Catalog\Model\Product\OptionFactory;
use Magento\Framework\Registry;
use Magento\Framework\Stdlib\StringUtils;
use Magento\Framework\View\Element\Template\Context;
use Magento\Sales\Model\OrderRepository;
use Magento\Sales\Model\ResourceModel\Order\Item\CollectionFactory;

class Item extends SubOrderItems
{
    protected $_template = 'Branch8_MarketPlaceParentOrderFrontendUi::parent_order/suborder-items.phtml';


    public function _prepareLayout()
    {
        $this->setOrderProgressBlock();
        parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }

    public function setOrderProgressBlock()
    {
       $this->setChild('order_progress', $this->getLayout()->createBlock(SubOrderProgress::class));
        $this->setChild(
            'marketplace_seller_chat_link',
            $this->getLayout()->createBlock(SellerChatLink::class)
        );
    }
}
