<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Branch8\MarketPlaceParentOrderFrontendUi\Block\ParentOrder\Info\Buttons
 */
// phpcs:disable Magento2.Templates.ThisInTemplate

?>
<div class="actions">
    <?php $_order = $block->getOrder() ?>
    <?php if ($block->canReorder($_order)) : ?>
        <a href="#" data-post='<?=
        /* @noEscape */ $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
            ->getPostData($block->getReorderUrl($_order))
        ?>' class="action order">
            <span><?= $block->escapeHtml(__('Reorder')) ?></span>
        </a>
    <?php endif ?>
    <a href="<?= $block->escapeUrl($block->getPrintUrl($_order)) ?>"
       class="action print"
       target="_blank"
       rel="noopener">
        <span><?= $block->escapeHtml(__('Print Order')) ?></span>
    </a>
    <?= $block->getChildHtml() ?>
</div>
