<?php
/** @var \Branch8\Mmegamenu\Block\Mmegamenu $block */
/** @var \Magento\Framework\Escaper $escaper */

$megaMenu = $block->getMegamenuItems();
?>
<?php $themeHelper = $this->helper('Branch8\Mmegamenu\Helper\Data') ?>
<?php $objectManager =  \Magento\Framework\App\ObjectManager::getInstance(); ?>
<?php $logo = $objectManager->get('\Magento\Theme\Block\Html\Header\Logo'); ?>

<?php if((count($megaMenu)>0) || $themeHelper->getStoreConfig('megamenu/general/home')):?>
    <?php if($themeHelper->getStoreConfig('megamenu/general/homeposition') == "" || $themeHelper->getStoreConfig('megamenu/general/homeposition') == 0): ?>
        <?php $positionHomeLink = 0; ?>
    <?php else: ?>
        <?php $positionHomeLink = $themeHelper->getStoreConfig('megamenu/general/homeposition'); ?>
    <?php endif ?>
    <nav class="navigation" role="navigation">
        <ul id="mainMenu" class="nav nav-main nav-main-menu">
            <?php if(count($megaMenu)>0): ?>

                <?php if($themeHelper->getStoreConfig('megamenu/general/home')): ?>
                    <?php if($positionHomeLink <= 0): ?>
                        <li class="mega-menu-item megamenu-homelink<?php if($themeHelper->getStoreConfig('megamenu/general/homelogo')): ?> logo-item<?php endif ?><?php if($block->isHomePage()): ?> active<?php endif ?>">
                            <?php if($themeHelper->getStoreConfig('megamenu/general/homelogo')): ?>
                                <?php if(!$block->isHomePage()): ?>
                                    <a href="<?= $escaper->escapeUrl($block->getUrl()) ?>" class="level0">
                                <?php else: ?>
                                    <strong class="logo">
                                <?php endif ?>
                                <img src="<?= $escaper->escapeHtmlAttr($logo->getLogoSrc()) ?>"
                                     alt="<?= $escaper->escapeHtmlAttr($logo->getLogoAlt()) ?>"
                                     width="<?= $escaper->escapeHtmlAttr($logo->getLogoWidth()) ?>"
                                     height="<?= $escaper->escapeHtmlAttr($logo->getLogoHeight()) ?>"
                                >
                                <?php if(!$block->isHomePage()): ?>
                                    </a>
                                <?php else: ?>
                                    </strong>
                                <?php endif ?>
                            <?php else: ?>
                                <a href="<?= $escaper->escapeUrl($block->getUrl()) ?>" class="level0">
                                    <?= $escaper->escapeHtml($themeHelper->getStoreConfig('megamenu/general/hometext')) ?>
                                </a>
                            <?php endif ?>
                        </li>
                        <?php $i=0; foreach($megaMenu as $item): $i++ ?>
                            <li class="<?= $escaper->escapeHtmlAttr($block->getClass($item)) ?>">
                                <?= /* @noEscape */ $block->getMenuHtml($item) ?>
                            </li>
                        <?php endforeach ?>
                    <?php else: ?>
                        <?php foreach($megaMenu as $item): ?>
                            <?php if($item->getPosition() < $positionHomeLink): ?>
                                <li class="<?= $escaper->escapeHtmlAttr($block->getClass($item)) ?>">
                                    <?= /* @noEscape */ $block->getMenuHtml($item) ?>
                                </li>
                            <?php endif ?>
                        <?php endforeach ?>

                        <li class="mega-menu-item megamenu-homelink<?php if($themeHelper->getStoreConfig('megamenu/general/homelogo')): ?> logo-item<?php endif ?><?php if($block->isHomePage()): ?> active<?php endif ?>">
                            <?php if($themeHelper->getStoreConfig('megamenu/general/homelogo')): ?>
                                <?php if(!$block->isHomePage()): ?>
                                    <a href="<?= $escaper->escapeUrl($block->getUrl()) ?>" class="level0">
                                <?php else: ?>
                                    <strong class="logo">
                                <?php endif ?>
                                <img src="<?= $escaper->escapeHtmlAttr($logo->getLogoSrc()) ?>"
                                     alt="<?= $escaper->escapeHtmlAttr($logo->getLogoAlt()) ?>"
                                     width="<?= $escaper->escapeHtmlAttr($logo->getLogoWidth()) ?>"
                                     height="<?= $escaper->escapeHtmlAttr($logo->getLogoHeight()) ?>"
                                >
                                <?php if(!$block->isHomePage()): ?>
                                    </a>
                                <?php else: ?>
                                    </strong>
                                <?php endif ?>
                            <?php else: ?>
                                <a href="<?= $escaper->escapeHtmlAttr($block->getUrl()) ?>" class="level0">
                                    <?= /* @noEscape */ $escaper->escapeHtml($themeHelper->getStoreConfig('megamenu/general/hometext')) ?>
                                </a>
                            <?php endif ?>
                        </li>

                        <?php foreach($megaMenu as $item): ?>
                            <?php if($item->getPosition() >= $positionHomeLink): ?>
                                <li class="<?= $escaper->escapeHtmlAttr($block->getClass($item)) ?>">
                                    <?= /* @noEscape */ $block->getMenuHtml($item) ?>
                                </li>
                            <?php endif ?>
                        <?php endforeach ?>
                    <?php endif ?>
                <?php else: ?>
                    <?php $i=0; foreach($megaMenu as $item): $i++ ?>
                        <li class="<?= $escaper->escapeHtmlAttr($block->getClass($item)) ?> item-<?= $escaper->escapeHtmlAttr($item->getId()) ?>">
                            <?= /* @noEscape */ $block->getMenuHtml($item) ?>
                        </li>
                    <?php endforeach ?>
                <?php endif ?>
            <?php endif ?>
        </ul>
    </nav>
<?php endif ?>
