<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_CustomOptionTemplate
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2020 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
/** @var $block \Magento\Catalog\Block\Adminhtml\Product\Edit\Tab\Options\Type\Select */

// @codingStandardsIgnoreFile
$product = $block->getParentBlock()?->getProduct();
$set = $product?->getAttributeSetId();
$allowedSets = $this->helper(\Webkul\Marketplace\Helper\Data::class)->getAllowedSets();
$set = $block->getRequest()->getParam('set') ?? $set;
$hideCustomOptions = false;
$virtualImportSetMap = ['ticket_yoxi', 'ticket_fami', 'ticket_redeem', 'ticket_non_redeem'];
foreach ($allowedSets as $allowedSet) {
    if ($allowedSet['value'] == $set && in_array($allowedSet['label'], $virtualImportSetMap)) {
        $hideCustomOptions = true;
        break;
    }
}
?>

<?php /** @var $block \Magento\Catalog\Block\Adminhtml\Product\Edit\Tab\Options\Type\Select */ ?>
<script id="custom-option-select-type-template" type="text/x-magento-template">
    <div id="product_option_<%- data.option_id %>_type_<%- data.group %>" class="fieldset">
        <table class="data-table">
            <thead>
            <tr>
                <th class="col-draggable">&nbsp;</th>
                <th class="col-name required">
                    <?php /* @escapeNotVerified */ echo __('Title') ?><span class="required">*</span>
                </th>
                <?php if ($block->getCanReadPrice() !== false) : ?>
                    <th class="col-price col-hide required"><?php /* @escapeNotVerified */ echo __('Price') ?></th>
                    <th class="col-price-type col-hide"><?php /* @escapeNotVerified */ echo __('Price Type') ?></th>
                <?php endif; ?>
                <th class="col-sku<?php if(!$hideCustomOptions): ?> required<?php endif; ?>"><?php /* @escapeNotVerified */ echo __('SKU') ?><?php if(!$hideCustomOptions): ?><span class="required">*</span><?php endif; ?></th>
                <th class="col-visible"><?php /* @escapeNotVerified */ echo __('Is Visible') ?></th>
                <th class="col-actions">&nbsp;</th>
            </tr>
            </thead>
            <tbody id="select_option_type_row_<%- data.option_id %>"></tbody>
            <tfoot>
            <tr>
                <td colspan="6"><?php echo $block->getAddButtonHtml() ?>
                    <input name="validation_<%- data.option_id %>_result" class="required-option-select-type-rows" type="hidden" value="">
                </td>
            </tr>
            <tr>
                <td colspan="6" class="note">
                    <p class="nm"><?php /* @escapeNotVerified */ echo __('Please set the specification price in Management Specifications (Variation SKU).') ?></p>
                </td>
            </tr>
            </tfoot>
        </table>
    </div>
</script>
<script id="custom-option-select-type-row-template" type="text/x-magento-template">
    <table>
        <tbody>
            <tr id="product_option_<%- data.id %>_select_<%- data.select_id %>" class="determined-location">
                <td class="col-draggable">
                    <div data-role="draggable-handle" class="draggable-handle"
                        title="<?php /* @escapeNotVerified */ echo __('Sort Custom Option'); ?>"></div>
                    <input name="product[options][<%- data.id %>][values][<%- data.select_id %>][sort_order]" type="hidden" value="<%- data.sort_order %>">
                </td>
                <td class="col-name select-opt-title field-option-title">
                    <input name="product[options][<%- data.id %>][values][<%- data.select_id %>][option_type_id]" type="hidden" value="<%- data.option_type_id %>">
                    <input id="product_option_<%- data.id %>_select_<%- data.select_id %>_is_delete" name="product[options][<%- data.id %>][values][<%- data.select_id %>][is_delete]" type="hidden" value="">
                    <input id="product_option_<%- data.id %>_select_<%- data.select_id %>_title"
                        <% if ((typeof data.scopeTitleDisabled != 'undefined' && data.scopeTitleDisabled != null) || (typeof data.is_bought != 'undefined' && data.is_bought == 1)) { %> disabled="disabled" <% } %>
                        name="product[options][<%- data.id %>][values][<%- data.select_id %>][title]"
                        class="required-entry input-text select-type-title <% if ((typeof data.scopeTitleDisabled != 'undefined' && data.scopeTitleDisabled != null) || (typeof data.is_bought != 'undefined' && data.is_bought == 1)) { %> disabled <% } %>"
                        type="text" value="<%- data.title %>" data-store-label="<%- data.title %>"><%= data.checkboxScopeTitle %>
                </td>
                <?php if ($block->getCanReadPrice() !== false) : ?>
                <td class="col-price select-opt-price col-hide">
                    <input id="product_option_<%- data.id %>_select_<%- data.select_id %>_price"
                           disabled="disabled"
                           name="product[options][<%- data.id %>][values][<%- data.select_id %>][price]"
                           class="input-text validate-number integer product-option-price"
                           type="text" value="<%- data.price %>" data-store-label="<%- data.price %>"
                           disabled="disabled"
                           name="product[options][<%- data.id %>][values][<%- data.select_id %>][price]"
                           class="input-text validate-number integer product-option-price"
                           type="text" value="<%- data.price %>" data-store-label="<%- data.price %>"
                        <?php if ($block->getCanEditPrice() === false) : ?>
                            disabled="disabled"
                            disabled="disabled"
                        <?php endif; ?>>
                </td>
                <td class="col-price-type select-opt-price-type col-hide">
                    <?php /* @escapeNotVerified */ echo $block->getPriceTypeSelectHtml('data-attr="price-type" disabled="disabled"') ?><%- data.checkboxScopePrice %>
                </td>
                <?php else : ?>
                    <input id="product_option_<%- data.id %>_select_<%- data.select_id %>_price" name="product[options][<%- data.id %>][values][<%- data.select_id %>][price]" type="hidden">
                    <input id="product_option_<%- data.id %>_select_<%- data.select_id %>_price_type" name="product[options][<%- data.id %>][values][<%- data.select_id %>][price_type]" type="hidden">
                <?php endif; ?>
                <td class="col-sku">
                    <input name="product[options][<%- data.id %>][values][<%- data.select_id %>][sku]" data-store-label="<%- data.sku %>"
                    <% if (typeof data.is_bought != 'undefined' && data.is_bought == 1) { %> disabled="disabled" <% } %>
                    class="input-text<?php if(!$hideCustomOptions): ?> required-entry<?php endif; ?> sku-unique" type="text" value="<%- data.sku %>">
                </td>
                <td class="col-visible">
                    <input name="product[options][<%- data.id %>][values][<%- data.select_id %>][is_bought]" data-store-label="<%- data.is_bought %>"
                        class="input-text" type="hidden" value="<%- data.is_bought %>">
                    <input name="product[options][<%- data.id %>][values][<%- data.select_id %>][is_visible]" data-store-label="<%- data.is_visible %>"
                    <% if (typeof data.is_visible != 'undefined' && data.is_visible == 1) { %> checked="checked" <% } %>
                    class="input-text" type="checkbox" value="1">
                </td>
                <td class="col-actions col-delete">
                    <% if (typeof data.is_bought != 'undefined' && data.is_bought != 1) { %>
                    <?php echo $block->getDeleteButtonHtml() ?>
                    <% } %>
                </td>
            </tr>
        </tbody>
    </table>
</script>
<script id="custom-option-select-type-row-template-add" type="text/x-magento-template">
    <table>
        <tbody>
        <tr id="product_option_<%- data.id %>_select_<%- data.select_id %>" class="determined-location">
            <td class="col-draggable">
                <div data-role="draggable-handle" class="draggable-handle"
                     title="<?php /* @escapeNotVerified */ echo __('Sort Custom Option'); ?>"></div>
                <input name="product[options][<%- data.id %>][values][<%- data.select_id %>][sort_order]" type="hidden" value="<%- data.sort_order %>">
            </td>
            <td class="col-name select-opt-title field-option-title">
                <input id="product_option_<%- data.id %>_select_<%- data.select_id %>_is_delete" name="product[options][<%- data.id %>][values][<%- data.select_id %>][is_delete]" type="hidden" value="">
                <input id="product_option_<%- data.id %>_select_<%- data.select_id %>_title" <% if (typeof data.scopeTitleDisabled != 'undefined' && data.scopeTitleDisabled != null) { %> disabled="disabled" <% } %> name="product[options][<%- data.id %>][values][<%- data.select_id %>][title]" class="required-entry input-text select-type-title <% if (typeof data.scopeTitleDisabled != 'undefined' && data.scopeTitleDisabled != null) { %> disabled <% } %>" type="text" value="<%- data.title %>" data-store-label="<%- data.title %>"><%= data.checkboxScopeTitle %>
            </td>
            <?php if ($block->getCanReadPrice() !== false) : ?>
                <td class="col-price select-opt-price col-hide">
                    <input id="product_option_<%- data.id %>_select_<%- data.select_id %>_price"
                           disabled="disabled"
                           name="product[options][<%- data.id %>][values][<%- data.select_id %>][price]"
                           class="input-text validate-number integer product-option-price"
                           type="text" value="<%- data.price %>" data-store-label="<%- data.price %>"
                        <?php if ($block->getCanEditPrice() === false) : ?>
                            disabled="disabled"
                        <?php endif; ?>>
                </td>
                <td class="col-price-type select-opt-price-type col-hide">
                    <?php /* @escapeNotVerified */ echo $block->getPriceTypeSelectHtml('data-attr="price-type" disabled="disabled"') ?><%- data.checkboxScopePrice %>
                </td>
            <?php else : ?>
                <input id="product_option_<%- data.id %>_select_<%- data.select_id %>_price" name="product[options][<%- data.id %>][values][<%- data.select_id %>][price]" type="hidden">
                <input id="product_option_<%- data.id %>_select_<%- data.select_id %>_price_type" name="product[options][<%- data.id %>][values][<%- data.select_id %>][price_type]" type="hidden">
            <?php endif; ?>
            <td class="col-sku">
                <input name="product[options][<%- data.id %>][values][<%- data.select_id %>][sku]" data-store-label="<%- data.sku %>"
                       class="input-text<?php if(!$hideCustomOptions): ?> required-entry<?php endif; ?> sku-unique" type="text" value="<%- data.sku %>"/>
            </td>
            <td class="col-visible">
                <input name="product[options][<%- data.id %>][values][<%- data.select_id %>][is_bought]" data-store-label="<%- data.is_bought %>"
                       class="input-text" type="hidden" value="<%- data.is_bought %>"/>
                <input name="product[options][<%- data.id %>][values][<%- data.select_id %>][is_visible]"
                       data-store-label="<%- data.is_visible %>"
                <% if ((typeof data.is_visible != 'undefined' && data.is_visible == 1) || (typeof data.is_visible == 'undefined')) { %> checked="checked" <% } %>
                value="1"
                class="input-text" type="checkbox"/>
            </td>
            <td class="col-actions col-delete"> <?php echo $block->getDeleteButtonHtml() ?></td>
        </tr>
        </tbody>
    </table>
</script>
