<?php
/**
 * @var $block \Branch8\SalesRule\Block\ProductCategory
 * @var $escaper \Magento\Framework\Escaper
 */
$componentId = rand(0, 10000000);
?>
<div class="admin__fieldset-wrapper opened" id="cart-rule-category<?php echo $componentId;?>">
    <div class="admin__fieldset-wrapper-content">
        <fieldset class="admin__fieldset">
            <div class="admin__field field">
                <div class="admin__field-control control">
                    <div id="assign-category-select" class="admin__field" data-bind="scope:'cartRuleCategory<?php echo $componentId;?>'" data-index="index">
                        <!-- ko foreach: elems() -->
                        <input name="seller_category_ids" data-bind="value: value" id="category_id" data-form-part="customer_form" type="hidden"/>
                        <!-- ko template: elementTmpl --><!-- /ko -->
                        <!-- /ko -->
                    </div>
                </div>
            </div>
        </fieldset>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "cartRuleCategory<?php echo $componentId;?>": {
                        "component": "uiComponent",
                        "children": {
                            "select_category": {
                                "component": "Branch8_SalesRule/js/components/categories",
                                "config": {
                                    "filterOptions": true,
                                    "disableLabel": true,
                                    "chipsEnabled": true,
                                    "levelsVisibility": "1",
                                    "elementTmpl": "ui/grid/filters/elements/ui-select",
                                    "options": <?= json_encode($this->getCategoriesTree()) ?>,
                                    "value": <?= json_encode($escaper->escapeHtml($block->getSelectedCategory())); ?>,
                                    "listens": {
                                        "index=create_category:responseData": "setParsed",
                                        "newOption": "toggleOptionSelected"
                                    },
                                    "config": {
                                        "dataScope": "select_category",
                                        "sortOrder": 10
                                    },
                                    "jsFormObject": "<?php echo $this->getJsFormObject();?>"
                                }
                            }
                        }
                    }
                }
            }
        }
    }
</script>
<script>
    require([
        "jquery"
    ], function(jQuery) {
        jQuery("#cart-rule-category<?php echo $componentId;?>").applyBindings();
        jQuery("#cart-rule-category<?php echo $componentId;?>").trigger('contentUpdated');
    });
</script>
