<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block Point */

use Branch8\HotaiPoint\Block\Header\Point;
$b8CustomerHelper = $this->helper(\Branch8\Customer\Helper\Data::class);
$subAccountHelper = $this->helper(\Webkul\SellerSubAccount\Helper\Data::class);
?>
<div class="dropdown hotai-toplink" style="display: none;" id="header-dropdown-hotaipoints" data-bind="scope: 'hotaipoints'">
    <span class="action dropdown-toggle"
        role="link"
        tabindex="0"
        data-mage-init='{"dropdown":{}}'
        data-toggle="dropdown"
        data-trigger-keypress-button="true"
        data-bind="scope: 'hotaipoints'">
        <span data-bind="html: hotaipoints().customer_point_icon" class="hotai-totalpoints"></span>
    </span>

    <div class="hotai-point-menu dropdown-list dropdown-center" data-target="dropdown" data-bind="scope: 'hotaipoints'">
        <!-- ko if: hotaipoints().totalorders  -->
            <span class="total-orders"
                    data-bind="text: hotaipoints().totalorders">
            </span>
        <!-- /ko -->
        <!-- ko if: hotaipoints().totalamount  -->
            <span class="total-orders-amount"
                    data-bind="text: hotaipoints().totalamount">
            </span>
        <!-- /ko -->
        <?= $block->getChildHtml() ?>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "hotaipoints": {
                        "component": "Branch8_HotaiPoint/js/view/rewards"
                    }
                }
            }
        }
    }
</script>
